Repository pagopa/pagopa-infra, pull requests merged in 2021-12, with the labels that each got.

#82 [PCFG-85] XML Schema for ICA variable
  src/api_config.tf
  src/env/dev/terraform.tfvars
  src/env/prod/terraform.tfvars
  src/env/uat/terraform.tfvars
  src/variables.tf
Labels: status: apply in progress

#83 [PCFG-98] login ad
  src/.terraform.lock.hcl
  src/README.md
  src/api/apiconfig_api/v1/_base_policy.xml.tpl
  src/api_config_fe.tf
  src/apim_api_config.tf
  src/azuread_api_config.tf
  src/checkout_fe.tf
  src/checkout_function.tf
  src/main.tf
  src/security.tf
  src/variables.tf
Labels: status: applied

#84 [PM-384] func buyer banks
  src/buyerbanks_function.tf
  src/env/dev/terraform.tfvars
  src/env/prod/terraform.tfvars
  src/env/uat/terraform.tfvars
  src/variables.tf
Labels: env: dev

#86 Web availability tests with SSL expiry check
  src/README.md
  src/api_config_fe.tf
  src/checkout_fe.tf
  src/monitor.tf
  src/terraform.sh
Labels: status: applied

#88 Update cdn and web test module to fix some tests
  .terraform-version
  src/.terraform.lock.hcl
  src/README.md
  src/api_config_fe.tf
  src/checkout_fe.tf
  src/main.tf
  src/monitor.tf
Labels: status: applied
