Repository pagopa/pagopa-infra, pull requests merged in 2022-01, with the labels that each got.

#92 [PAG-1098] add sas sia for test RE su ehub
  src/env/dev/terraform.tfvars
Labels: env: dev

#102 Apim diagnostic settings to send log to security subscription
  src/README.md
  src/apim.tf
Labels: status: applied

#110 [INFRA-500] Send activity log to security
  src/monitor.tf
Labels: status: applied

#98 [IOPAY-405] update apim policy for new checkout APIs
  src/README.md
  src/api/checkout/checkout_nodo_ws/v1/_base_policy.xml.tpl
  src/api/checkout/checkout_payment_activations/v1/_base_policy.xml.tpl
  src/api/checkout/checkout_payment_activations/v1/_idpayment_check.xml.tpl
  src/api/checkout/checkout_payment_activations/v1/_recaptcha_check.xml.tpl
  src/api/checkout/checkout_payment_activations/v1/_swagger.json.tpl
  src/api/checkout/checkout_transactions/v1/_swagger.json.tpl
  src/apim.tf
  src/apim_checkout.tf
  src/checkout_function.tf
  src/env/dev/terraform.tfvars
  src/env/prod/terraform.tfvars
  src/env/uat/terraform.tfvars
  src/monitor.tf
  src/pagopa_proxy.tf
  src/security.tf
  src/variables.tf
Labels: env: uat, no merge, status: partially applied

#128 add deny paths on app gateway
  src/appgateway.tf
  src/env/dev/terraform.tfvars
  src/env/prod/terraform.tfvars
  src/env/uat/terraform.tfvars
  src/variables.tf
Labels: env: dev, env: uat, env: prod, status: apply in progress

#125 [IOPAY-400] New api used by PM
  src/api/nodopagamenti_api/nodoPerPM/_base_policy.xml.tpl
  src/api/nodopagamenti_api/nodoPerPM/_swagger.json.tpl
  src/api/payment_manager_api/clients/bpd/v1/_base_policy.xml.tpl
  src/api/payment_manager_api/clients/bpd/v1/_openapi.json.tpl
  src/api/payment_manager_api/clients/cobadge/v4/_base_policy.xml.tpl
  src/api/payment_manager_api/clients/cobadge/v4/_swagger.json.tpl
  src/api/payment_manager_api/clients/fesp/_base_policy.xml.tpl
  src/api/payment_manager_api/clients/fesp/_swagger.json.tpl
  src/api/payment_manager_api/clients/io-bpd/_base_policy.xml.tpl
  src/api/payment_manager_api/clients/io-bpd/_swagger.json.tpl
  src/api/payment_manager_api/clients/paypal-psp/v1/_base_policy.xml.tpl
  src/api/payment_manager_api/clients/paypal-psp/v1/_openapi.json.tpl
  src/api/payment_manager_api/clients/xpay/v1/_base_policy.xml.tpl
  src/api/payment_manager_api/clients/xpay/v1/_swagger.json.tpl
  src/apim_nodo_services.tf
  src/apim_payment_manager.tf
  src/env/dev/terraform.tfvars
  src/env/prod/terraform.tfvars
  src/env/uat/terraform.tfvars
  src/variables.tf
Labels: status: apply in progress

#132 [IOPAY-404] add slot staging for pagopa-proxy
  src/pagopa_proxy.tf
Labels: status: applied
