Repository pagopa/pagopa-infra, pull requests merged in 2022-05, with the labels that each got.

#250 fix delete cache activate reservation + fix content type fdr
  src/api/nodopagamenti_api/nodeForPsp/v1/activate_nm3.xml
  src/api/nodopagamenti_api/nodoPerPsp/v1/fdr_nodoinvia_flussorendicontazione_flow.xml
Labels: status: applied

#249 [CHK-365] Disable pagopaproxy io
  src/api/checkout/checkout_payment_activations/v1/_idpayment_check.xml.tpl
  src/api/checkout/checkout_payment_activations_auth/v1/_idpayment_check.xml.tpl
  src/api/checkout/checkout_payment_activations_auth/v2/_idpayment_check.xml.tpl
  src/api/checkout/checkout_payments/v1/_base_policy.xml.tpl
  src/api/checkout/checkout_payments/v1/_swagger.json.tpl
  src/api_logs.tf
  src/apim_checkout.tf
  src/natgateway.tf
Labels: status: applied

#251 add PDA apim group
  src/apim.tf
Labels: status: applied

#254 [PAG-1526] add nodo-dei-pagamenti-biz-evt topic on ehub
  src/env/dev/terraform.tfvars
  src/env/prod/terraform.tfvars
  src/env/uat/terraform.tfvars
Labels: status: applied

#258 [PAG-1526] add consumer to nodo-dei-pagamenti-biz-evt
  src/env/dev/terraform.tfvars
  src/env/prod/terraform.tfvars
  src/env/uat/terraform.tfvars
Labels: status: applied

#259 replace undeclaration xml namespace
  src/api/nodopagamenti_api/nodoPerPsp/v1/fdr_nodoinvia_flussorendicontazione_flow.xml
Labels: status: applied

#265 ApiConfig-swagger-update
  src/api/apiconfig_api/v1/_openapi.json.tpl
Labels: status: applied

#266 [PPD-175] add reporting autoscaling
  src/gpd_reporting.tf
Labels: status: applied

#261 [PPD-180] Payments az alert
  src/gpd_payments.tf
Labels: status: applied

#273 ApiConfig-swagger-update
  src/api/apiconfig_api/v1/_openapi.json.tpl
Labels: status: apply in progress

#277 [PCFG-225] Enabled ApiConfig for Production
  src/README.md
  src/api_config.tf
  src/apim_api_config.tf
  src/env/dev/terraform.tfvars
  src/env/prod/terraform.tfvars
  src/env/uat/terraform.tfvars
  src/variables.tf
Labels: status: applied

#278 [ApiConfig] added AutoScaling
  src/api_config.tf
Labels: status: applied, status: apply in progress
