Repository pagopa/pagopa-infra, pull requests merged in 2022-08, with the labels that each got.

#339 Storage account to backup apim
  src/README.md
  src/data.tf
Labels: status: applied :hand:

#332 New Payments WSDL
  src/api/gpd_api/payments/v1/soap/paForNode.wsdl
Labels: status: applied :hand:

#345 upd cosmos vnet rules
  src/gps-common/03_cosmosdb.tf
  src/shared-common/03_cosmosdb_iuvgenerator.tf
Labels: status: applied :hand:

#353 feat: Disable nodo onprem DEV
  src/env/dev/terraform.tfvars
Labels: status: applied :hand:

#334 Point payment-transactions-gateway APIs to on-cloud instance
  src/api/payment_transactions_gateway_api/external/v1/_base_policy.xml.tpl
  src/api/payment_transactions_gateway_api/internal/v1/_base_policy.xml.tpl
  src/api/payment_transactions_gateway_api/update/v1/_base_policy.xml.tpl
Labels: status: apply in progress

#362 fix: Split deny path strings
  src/appgateway.tf
  src/env/dev/terraform.tfvars
  src/env/prod/terraform.tfvars
  src/env/uat/terraform.tfvars
  src/variables.tf
Labels: status: applied :hand:

#358 fix: update policy for pgs
  src/api/payment_transactions_gateway_api/external/v1/_base_policy.xml.tpl
  src/api/payment_transactions_gateway_api/internal/v1/_base_policy.xml.tpl
  src/api/payment_transactions_gateway_api/update/v1/_base_policy.xml.tpl
  src/apim_payment_transactions_gateway.tf
Labels: status: applied
