Repository pagopa/pagopa-infra, pull requests merged in 2022-04, with the labels that each got.

#224 update PSP list for verificatore UAT and PROD (FactorCoop)
  src/env/prod/terraform.tfvars
  src/env/uat/terraform.tfvars
Labels: status: applied

#225 [donations for 🇺🇦 ] CESVI transferCategory
  src/api/nodopagamenti_api/paForNode/v1/donationsCfg/dev/donazioni_ucraina.json
  src/api/nodopagamenti_api/paForNode/v1/donationsCfg/prod/donazioni_ucraina.json
  src/api/nodopagamenti_api/paForNode/v1/donationsCfg/uat/donazioni_ucraina.json
Labels: status: applied

#226 Update callback 3ds esito fo dev checkout
  src/checkout_function.tf
Labels: status: applied

#228 [donations for 🇺🇦 ] CESVI change name and position
  src/api/donations/v1/logos/logo1
  src/api/donations/v1/logos/logo2
  src/api/donations/v1/logos/logo3
  src/api/nodopagamenti_api/paForNode/v1/donationsCfg/dev/donazioni_ucraina.json
  src/api/nodopagamenti_api/paForNode/v1/donationsCfg/prod/donazioni_ucraina.json
  src/api/nodopagamenti_api/paForNode/v1/donationsCfg/uat/donazioni_ucraina.json
Labels: env: prod

#229 update callback checkout 3ds with the final values
  src/checkout_function.tf
Labels: env: uat, no merge

#235 [GPD] Autoscaling
  src/gpd.tf
  src/gpd_payments.tf
Labels: status: applied

#241 update PSP list for verificatore UAT and PROD (Telepass Pay)
  src/env/prod/terraform.tfvars
  src/env/uat/terraform.tfvars
Labels: status: applied

#246 update mock ec config
  src/env/uat/terraform.tfvars
  src/mock_ec.tf
Labels: env: uat

#245 add fdr out blob
  src/fdr.tf
  src/reporting_function.tf
Labels: status: applied

#234 [PM-690] Add update-status and sendPaymentResult for PM
  src/api/payment_manager_api/restapi-cd/v1/_internal_policy.xml.tpl
  src/api/payment_manager_api/restapi-cd/v1/_swagger.json.tpl
  src/api/payment_manager_api/restapi-cd/v2/_internal_policy.xml.tpl
  src/api/payment_manager_api/restapi-cd/v2/_swagger.json.tpl
  src/apim_payment_manager.tf
  src/env/prod/terraform.tfvars
  src/env/uat/terraform.tfvars
Labels: status: applied
