Repository pagopa/pagopa-infra, pull requests merged in 2022-12, with the labels that each got.

#567 upd apim Biz-Events Service
  src/domains/bizevents-app/api/bizevents-service/v1/_openapi.json.tpl
Labels: env: dev, env: uat, status: applied :hand:

#565 [PPR-501] enrich biz event: added security variables
  .gitignore
  src/domains/bizevents-common/01_events.tf
  src/domains/bizevents-common/02_security.tf
  src/domains/bizevents-common/README.md
Labels: env: dev, env: uat, status: applied :hand:

#568 feat: [PAGOPA-392] Autoscaling node-forwarder
  src/core/node_forwarder.tf
Labels: env: uat, status: ready to apply, status: applied :hand:

#576 feat: Add checkPosition NODO_4_PM
  src/core/api/nodopagamenti_api/nodoPerPM/v1/_base_policy.xml.tpl
  src/core/api/nodopagamenti_api/nodoPerPM/v1/_base_policy_dev.xml.tpl
  src/core/api/nodopagamenti_api/nodoPerPM/v1/_closepayment_policy.xml.tpl
  src/core/api/nodopagamenti_api/nodoPerPM/v1/_closepayment_policy_dev.xml.tpl
  src/core/api/nodopagamenti_api/nodoPerPM/v1/_swagger.json.tpl
  src/core/api/nodopagamenti_api/nodoPerPM/v2/_base_policy.xml.tpl
  src/core/api/nodopagamenti_api/nodoPerPM/v2/_base_policy_dev.xml.tpl
  src/core/apim_nodo_services_dev.tf
Labels: env: dev, env: uat, status: applied :hand:

#559 Small Fix
  src/domains/afm-app/04_apim_afm_calculator.tf
  src/domains/afm-common/env/weu-uat/terraform.tfvars
Labels: env: dev, env: uat, env: prod, status: applied

#582 fix: Missing nodo oncloud ref on activate policy
  src/core/README.md
  src/core/api/nodopagamenti_api/monitoring/v1/_base_policy.xml
  src/core/api/nodopagamenti_api/monitoring/v1/_base_policy.xml.tpl
  src/core/api/nodopagamenti_api/monitoring/v1/_base_policy_dev.xml
  src/core/api/nodopagamenti_api/nodeForPsp/v1/activate_nm3.xml
  src/core/api/nodopagamenti_api/nodoPerPsp/v1/fdr_nodoinvia_flussorendicontazione_flow.xml
  src/core/apim_nodo_services.tf
  src/core/apim_nodo_services_auth.tf
  src/core/apim_nodo_services_dev.tf
Labels: env: dev, env: uat, status: applied :hand:

#586 fix: Apim 500 activatePaymentNotice and nodoInviaFlussoRendicontazione
  src/core/api/nodopagamenti_api/nodeForPsp/v1/activate_nm3.xml
  src/core/api/nodopagamenti_api/nodoPerPsp/v1/fdr_nodoinvia_flussorendicontazione_flow.xml
Labels: env: dev, env: uat, status: applied :hand:

#588 [PM-1250] feat: update swagger definition
  src/core/api/tkm_api/tkm-ms-card-manager/v1/_openapi.json.tpl
Labels: env: dev, env: uat, env: prod, status: applied

#555 feat: [PPR-504] add sp to kv for nodo deploy
  .gitignore
  src/domains/nodo-app/04_apim_nodo_pg.tf
  src/domains/nodo-app/README.md
  src/domains/nodo-app/api/nodopg-service/v1/_NodoDeiPagamenti.openapi.json.tpl
  src/domains/nodo-app/api/nodopg-service/v1/_base_policy.xml
  src/domains/nodo-app/api_product/_base_policy.xml
  src/domains/nodo-app/api_product/nodopg-service/_base_policy.xml
  src/domains/nodo-common/02_security.tf
  src/domains/nodo-secret/02_security.tf
  src/domains/nodo-secret/99_main.tf
  src/domains/nodo-secret/99_variables.tf
  src/domains/nodo-secret/README.md
  src/domains/nodo-secret/env/weu-dev/backend.ini
  src/domains/nodo-secret/env/weu-dev/terraform.tfvars
  src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/nodo-secret/storageaccount.tf
  src/psql/migrations/DEV-pagoPA/nodo/liquibase/changelog/cfg/db.changelog-20221128151200_view canali_canali_nodo.xml
  src/psql/migrations/DEV-pagoPA/nodo/liquibase/changelog/cfg/db.changelog-20221205102000_replace_elenco_servizi_view_canali_nodo.xml
  src/psql/migrations/DEV-pagoPA/nodo/liquibase/changelog/cfg/db.changelog-20221205102100_delete_unused_keys_column.xml
  src/psql/migrations/DEV-pagoPA/nodo/liquibase/changelog/cfg/db.changelog-20221205161400_delete_key_chiediElencoFlussiRendicontazioneDayLimit.xml
  src/psql/migrations/DEV-pagoPA/nodo/liquibase/changelog/cfg/db.changelog-20221212091400_delete_unused_keys_column-2.xml
  src/psql/migrations/DEV-pagoPA/nodo/liquibase/changelog/cfg/db.changelog-dev-data-ftp_server.xml
  src/psql/migrations/DEV-pagoPA/nodo/liquibase/changelog/cfg/db.changelog-dev-data-psp-pa.xml
  src/psql/migrations/DEV-pagoPA/nodo/liquibase/changelog/cfg/db.changelog-master.xml
  src/psql/migrations/DEV-pagoPA/nodo/liquibase/changelog/offline/db.changelog-0.xml
  src/psql/migrations/DEV-pagoPA/nodo/liquibase/changelog/offline/db.changelog-202212120933_drop_view_storni_revoche.xml
  src/psql/migrations/DEV-pagoPA/nodo/liquibase/changelog/offline/db.changelog-master.xml
  src/psql/migrations/DEV-pagoPA/nodo/liquibase/changelog/online/db.changelog-20221110162200_modify_positionRetrySendPaymentResult_table.xml
  src/psql/migrations/DEV-pagoPA/nodo/liquibase/changelog/online/db.changelog-20221111115000_modify_outcome_positionRetrySendPaymentResult_table.xml
  src/psql/migrations/DEV-pagoPA/nodo/liquibase/changelog/online/db.changelog-202211140000000_views_payments_mbd_grants.xml
  src/psql/migrations/DEV-pagoPA/nodo/liquibase/changelog/online/db.changelog-202211210000000_busy_column.xml
  src/psql/migrations/DEV-pagoPA/nodo/liquibase/changelog/online/db.changelog-20221122142200_retryPending_rptActivations.xml
  src/psql/migrations/DEV-pagoPA/nodo/liquibase/changelog/online/db.changelog-202211301458000_index_transactionId_payment.xml
  src/psql/migrations/DEV-pagoPA/nodo/liquibase/changelog/online/db.changelog-2022120510210000_delete_unused_column_table.xml
  src/psql/migrations/DEV-pagoPA/nodo/liquibase/changelog/online/db.changelog-master.xml
Labels: env: dev, status: applied :hand:

#566 [PAGOPA-67] New Container CDI
  src/core/README.md
  src/core/api_config.tf
  src/core/security.tf
  src/domains/afm-common/02_security.tf
  src/domains/afm-common/03_cosmosdb_afm.tf
  src/domains/afm-common/README.md
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#573 Feat apikey pm events
  src/core/README.md
  src/core/api/payment_manager_api/payment-events/v1/_base_policy.xml.tpl
  src/core/api/payment_manager_api/payment-events/v1/_openapi.json.tpl
  src/core/apim_payment_manager.tf
Labels: env: dev, env: uat, env: prod, status: applied

#574 feat (GPS): Add APIM and storage [PAGOPA-350]
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
  src/domains/gps-app/03_serviceaccounts_azure_devops.tf
  src/domains/gps-app/04_apim_external_payments.tf
  src/domains/gps-app/04_apim_internal_payments.tf
  src/domains/gps-app/README.md
  src/domains/gps-app/api/payments-service/v1/rest/external/_base_policy.xml
  src/domains/gps-app/api/payments-service/v1/rest/external/_openapi.json.tpl
  src/domains/gps-app/api/payments-service/v1/rest/internal/_base_policy.xml
  src/domains/gps-app/api/payments-service/v1/rest/internal/_openapi.json.tpl
  src/domains/gps-app/api/payments-service/v1/soap/_base_policy.xml.tpl
  src/domains/gps-app/api/payments-service/v1/soap/paForNode.wsdl
  src/domains/gps-app/api_product/payments-service/_base_policy.xml
  src/domains/gps-app/api_product/payments-service/external/_base_policy.xml
  src/domains/gps-common/00_monitor.tf
  src/domains/gps-common/02_security.tf
  src/domains/gps-common/03_storage_account.tf
  src/domains/gps-common/99_variables.tf
  src/domains/gps-common/README.md
Labels: env: dev, env: uat, status: applied :hand:
