Repository pagopa/pagopa-infra, pull requests merged in 2022-06, with the labels that each got.

#279 upd apiconfig vnet integration
  src/api_config.tf
Labels: status: applied :hand:

#282 Update Checkout API v2 documentation with new `category` error field
  src/api/checkout/checkout_payment_activations_auth/v2/_swagger.json.tpl
Labels: status: applied

#268 [PPD-189] resize Postgres Flexible UAT and PROD
  src/env/uat/terraform.tfvars
Labels: status: applied

#285 upd dns_a_reconds_dbnodo_ips
  src/env/prod/terraform.tfvars
Labels: status: applied

#263 Ecommerce profile
  src/aks/04_rbac.tf
  src/dns_private.tf
  src/ecommerce-common/.terraform.lock.hcl
  src/ecommerce-common/00_azuread.tf
  src/ecommerce-common/00_monitor.tf
  src/ecommerce-common/01_network.tf
  src/ecommerce-common/02_security.tf
  src/ecommerce-common/99_locals.tf
  src/ecommerce-common/99_main.tf
  src/ecommerce-common/99_variables.tf
  src/ecommerce-common/README.md
  src/ecommerce-common/env/weu-dev/backend.ini
  src/ecommerce-common/env/weu-dev/backend.tfvars
  src/ecommerce-common/env/weu-dev/terraform.tfvars
  src/ecommerce-common/terraform.sh
  src/ecommerce/.terraform.lock.hcl
  src/ecommerce/00_azuread.tf
  src/ecommerce/00_network.tf
  src/ecommerce/01_aks.tf
  src/ecommerce/01_monitor.tf
  src/ecommerce/02_namespace.tf
  src/ecommerce/02_security.tf
  src/ecommerce/03_serviceaccounts_azure_devops.tf
  src/ecommerce/99_locals.tf
  src/ecommerce/99_main.tf
  src/ecommerce/99_variables.tf
  src/ecommerce/README.md
  src/ecommerce/env/weu-dev/backend.ini
  src/ecommerce/env/weu-dev/backend.tfvars
  src/ecommerce/env/weu-dev/terraform.tfvars
  src/ecommerce/terraform.sh
Labels: status: apply in progress

#283 [PPR-353] fix content-type verificatore
  src/api/nodopagamenti_api/nodeForPsp/v1/activate_nm3.xml
Labels: status: applied :hand:

#293 set acr public
  src/container_registry.tf
Labels: status: applied :hand:

#301 feat: Add azurerm_storage_management_policy fdr
  src/fdr.tf
  src/variables.tf
Labels: status: applied :hand:

#299 feat: Add demandPaymentNotice nodoChiediCatalogoServiziV2 nodeForPsp
  src/api/nodopagamenti_api/nodeForPsp/v1/nodeForPsp.wsdl
Labels: status: applied :hand:

#309 add avaliabilty test status page
  src/monitor.tf
Labels: env: dev, env: uat, env: prod, status: apply in progress

#308 Fix app service autoscale instances
  src/api_config.tf
  src/env/uat/terraform.tfvars
  src/variables.tf
Labels: env: dev, env: uat, env: prod, status: applied

#302 feat: Add activateIO reservation policy
  src/api/nodopagamenti_api/nodeForIO/v1/activateIO_reservation_nm3.xml
  src/apim_nodo_services.tf
Labels: status: applied :hand:
