Repository pagopa/pagopa-infra, pull requests merged in 2022-02, with the labels that each got.

#136 Add routes to Payment Manager
  src/network.tf
Labels: env: dev, env: uat, env: prod, status: apply in progress

#138 [PM-477] update alerting rules (buyerbanks)
  src/buyerbanks_function.tf
Labels: status: applied

#141 [IOPAY-404] fix checkout policy
  src/api/checkout/checkout_payment_activations/v1/_idpayment_check.xml.tpl
  src/api/checkout/checkout_payment_activations_auth/v1/_idpayment_check.xml.tpl
Labels: status: apply in progress

#152 Fix recaptcha policy - checkout
  src/api/checkout/checkout_payment_activations/v1/_recaptcha_check.xml.tpl
Labels: status: applied

#155 [PMF-15] add fdr ehub topic var to fdr function
  src/messages.tf
  src/reporting_function.tf
Labels: status: ready to apply

#151 Update PSP list for "verificatore" UAT and PROD
  src/env/prod/terraform.tfvars
  src/env/uat/terraform.tfvars
Labels: status: ready to apply

#147 Fix Health Check mock EC
  src/mock_ec.tf
Labels: status: ready to apply

#160 Add nodo ip for NodeForPM
  src/api/nodopagamenti_api/nodoPerPM/_base_policy.xml.tpl
  src/apim.tf
  src/env/dev/terraform.tfvars
  src/env/prod/terraform.tfvars
  src/env/uat/terraform.tfvars
  src/variables.tf
Labels: status: ready to apply

#143 Update appgtw denypaths
  src/env/uat/terraform.tfvars
Labels: status: apply in progress

#173 update NodoPerPa soap service
  src/api/nodopagamenti_api/nodoPerPa/v1/NodoPerPa.wsdl
Labels: status: apply in progress

#172 Update nodoPerPsp and new NodoPerPspRichiestaAvvisi
  src/api/nodopagamenti_api/nodoPerPsp/v1/nodoPerPsp.wsdl
  src/api/nodopagamenti_api/nodoPerPspRichiestaAvvisi/v1/_base_policy.xml
  src/api/nodopagamenti_api/nodoPerPspRichiestaAvvisi/v1/nodoPerPspRichiestaAvvisi.wsdl
  src/apim_nodo_services.tf
Labels: status: applied

#175 fix nodoPerPA apim import
  src/api/nodopagamenti_api/nodoPerPa/v1/NodoPerPa.wsdl
Labels: status: applied

#177 Fix pagopa-proxy (checkout) policy and add client-io group
  src/api/checkout/checkout_payment_activations_auth/v1/_base_policy.xml.tpl
  src/api/checkout/checkout_payment_activations_auth/v2/_base_policy.xml.tpl
  src/apim.tf
Labels: env: dev, env: uat, env: prod

#178 Add apim logs for pagopaproxy
  src/api_logs.tf
  src/apim_checkout.tf
Labels: env: dev, env: uat, env: prod, status: applied
