Repository pagopa/pagopa-infra, pull requests merged in 2022-11, with the labels that each got.

#474 [PGEC-83] Add touchpoint container
  src/domains/afm-common/03_cosmosdb_marketplace.tf
  src/domains/afm-common/README.md
  src/domains/bizevents-app/99_locals.tf
  src/domains/bizevents-app/README.md
  src/domains/bizevents-common/env/weu-dev/terraform.tfvars
  src/domains/bizevents-common/env/weu-prod/terraform.tfvars
  src/domains/bizevents-common/env/weu-uat/terraform.tfvars
Labels: env: dev, env: uat, status: applied

#517 feat: Expose on apim SIT mock Nexi PM
  src/core/apim_mock_ec_psp_pm_nexi.tf
Labels: env: dev, status: applied :hand:

#521 [Biz-Events] feat: add missing config for biz events datastore deploy
  src/core/outputs.tf
  src/domains/bizevents-common/02_security.tf
Labels: env: dev, status: applied :hand:

#523 feat: API-CFG update swagger
  src/core/api/apiconfig_api/v1/_openapi.json.tpl
Labels: env: dev, env: uat, status: applied :hand:

#537 Scale out app gateway
  src/core/env/prod/terraform.tfvars
Labels: env: prod, status: applied

#545 feat: Modifica auto scaling DB EXP - PPR-506
  src/core/env/dev/terraform.tfvars
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
Labels: status: applied :hand:

#539 feat: Add ehub nodo-dei-pagamenti-biz-evt-pdnd
  src/core/env/dev/terraform.tfvars
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
Labels: status: applied :hand:

#493 feat: Grafana Admin Permission to Pagopa Adgroup Developers
  src/domains/load-test/02_iam.tf
  src/domains/load-test/README.md
Labels: env: dev, status: applied :hand:, gilda-k6

#551 feat: Added kv to node-forwarder
  src/core/node_forwarder.tf
Labels: env: dev, env: uat, status: applied :hand:

#550 Policy Influxdb
  src/domains/shared-app/.terraform.lock.hcl
  src/domains/shared-app/04_apim_influxdb.tf
  src/domains/shared-app/README.md
  src/domains/shared-app/api_product/_influxdb_policy.xml
Labels: env: dev, status: applied, gilda-k6

#557 Agent Pool Load Test
  src/domains/shared-common/env/weu-uat/terraform.tfvars
Labels: env: dev, env: uat, status: applied

#556 fix: Nodo-dev closepayment backend ref
  src/core/README.md
  src/core/apim_nodo_services_dev.tf
  src/core/node_forwarder.tf
Labels: env: dev, status: applied :hand:

#535 fix: update open api descriptors for payment-request carts requests
  src/core/api/checkout/checkout_ecommerce/v1/_openapi.json.tpl
  src/domains/ecommerce-app/api/ecommerce-payment-requests-service/v1/_openapi.json.tpl
  src/domains/nodo-common/README.md
Labels: env: dev, status: applied
