Repository pagopa/pagopa-infra, pull requests merged in 2022-07, with the labels that each got.

#306 ApiConfig-swagger-update
  src/api/apiconfig_api/v1/_openapi.json.tpl
Labels: status: apply in progress

#315 [PPR-351] AFM Marketplace - Add archived container
  src/advanced_fees_management.tf
Labels: env: dev, status: applied

#307 feat: Add openapi-link for apim_api_config_api
  src/apim_api_config.tf
Labels: status: ready to apply, status: applied :hand:
