Repository pagopa/pagopa-infra, pull requests merged in 2022-03, with the labels that each got.

#200 Add cdInfoWisp in app_gateway_deny_paths
  src/env/prod/terraform.tfvars
  src/env/uat/terraform.tfvars
Labels: status: apply in progress

#206 [donations for 🇺🇦] add avsi
  src/api/donations/v1/donazioni_ucraina.xml
  src/api/donations/v1/logos/logo2
  src/api/nodopagamenti_api/paForNode/v1/donationsCfg/dev/donazioni_ucraina.json
  src/api/nodopagamenti_api/paForNode/v1/donationsCfg/prod/donazioni_ucraina.json
  src/api/nodopagamenti_api/paForNode/v1/donationsCfg/uat/donazioni_ucraina.json
  src/apim_donations.tf
Labels: env: uat, env: prod

#214 [GPD] Staging Slot
  src/gpd_reporting.tf
Labels: status: applied
