Repository pagopa/pagopa-infra, pull requests merged in 2022-09, with the labels that each got.

#367 feat: Apiconfig multi env auth
  src/apim_api_config.tf
  src/apim_payment_transactions_gateway.tf
Labels: status: applied :hand:

#368 feat: Upd swagger payments
  src/gps/api/spontaneous-payments-service/v1/_openapi.json.tpl
Labels: env: dev, status: applied :hand:

#377 Code cleaning and AKS ingress fix
  src/aks-platform/03_ingress.tf
  src/aks-platform/env/weu-dev/terraform.tfvars
  src/core/advanced_fees_management.tf
  src/core/api/afm_api/marketplace/v1/_base_policy.xml.tpl
  src/core/api/afm_api/marketplace/v1/_openapi.json.tpl
  src/core/api_product/afm_api/_base_policy.xml
  src/core/apim_advanced_fees_management.tf
  src/domains/afm-app/api_product/calculator/env/weu-dev/backend.ini
  src/domains/afm-app/api_product/calculator/env/weu-dev/backend.tfvars
  src/domains/afm-app/api_product/calculator/env/weu-dev/terraform.tfvars
  src/domains/afm-app/api_product/marketplace/env/weu-dev/backend.ini
  src/domains/afm-app/api_product/marketplace/env/weu-dev/backend.tfvars
  src/domains/afm-app/api_product/marketplace/env/weu-dev/terraform.tfvars
Labels: status: applied :hand:

#378 [PAP-19] Add `api.prf.platform.pagopa.it`
  src/core/README.md
  src/core/api/nodopagamenti_api/nodoServices/v1/_base_policy_uat_prf.xml
  src/core/api/payment_manager_api/admin-panel/_base_policy.xml.tpl
  src/core/api/payment_manager_api/logging/v1/_base_policy.xml.tpl
  src/core/api/payment_manager_api/payment-transactions-gateway/v1/_base_policy.xml.tpl
  src/core/api/payment_manager_api/pm-per-nodo/v1/_base_policy.xml.tpl
  src/core/api/payment_manager_api/restapi-cd-assets/_base_policy.xml.tpl
  src/core/api/payment_manager_api/restapi-cd-internal/v1/_base_policy.xml.tpl
  src/core/api/payment_manager_api/restapi-cd-internal/v2/_base_policy.xml.tpl
  src/core/api/payment_manager_api/restapi-cd/v1/_base_policy.xml.tpl
  src/core/api/payment_manager_api/restapi-cd/v2/_base_policy.xml.tpl
  src/core/api/payment_manager_api/restapi-cd/v3/_base_policy.xml.tpl
  src/core/api/payment_manager_api/restapi-rtd/v1/_base_policy.xml.tpl
  src/core/api/payment_manager_api/restapi-rtd/v2/_base_policy.xml.tpl
  src/core/api/payment_manager_api/restapi-server/v4/_base_policy.xml.tpl
  src/core/api/payment_manager_api/restapi/v4/_base_policy.xml.tpl
  src/core/api/payment_manager_api/wisp/_base_policy.xml.tpl
  src/core/api/payment_transactions_gateway_api/external/v1/_base_policy.xml.tpl
  src/core/api/payment_transactions_gateway_api/internal/v1/_base_policy.xml.tpl
  src/core/api/payment_transactions_gateway_api/update/v1/_base_policy.xml.tpl
  src/core/apim.tf
  src/core/apim_nodo_services.tf
  src/core/apim_payment_manager.tf
  src/core/apim_payment_transactions_gateway.tf
  src/core/appgateway.tf
  src/core/dns_private.tf
  src/core/dns_public.tf
  src/core/env/uat/terraform.tfvars
  src/core/security.tf
  src/core/variables.tf
Labels: env: uat, status: applied :hand:

#402 SpontaneousPayments-swagger-update
  src/domains/gps-app/api/spontaneous-payments-service/v1/_openapi.json.tpl
Labels: status: applied :hand:

#405 feat: Add mock EC-PSP-PM Nexi via UAT/PRF
  src/core/README.md
  src/core/api/mock_nexi/ec/v1/_base_policy.xml
  src/core/api/mock_nexi/ec/v1/mock.openapi.json.tpl
  src/core/api/mock_nexi/pm/v1/_base_policy.xml
  src/core/api/mock_nexi/pm/v1/mock.openapi.json.tpl
  src/core/api/mock_nexi/psp/v1/_base_policy.xml
  src/core/api/mock_nexi/psp/v1/mock.openapi.json.tpl
  src/core/api_product/mock_nexi/_base_policy.xml
  src/core/apim_mock_ec_psp_pm_nexi.tf
Labels: env: uat, status: applied :hand:

#404 IuvGeneratorService-swagger-update
  src/domains/shared-app/api/iuv-generator-service/v1/_openapi.json.tpl
Labels: env: dev, env: uat, env: prod, status: apply in progress, status: applied :hand:

#395 AFM-Calculator-swagger-update
  src/domains/afm-app/api/calculator-service/v1/_openapi.json.tpl
Labels: env: dev, env: uat, status: applied :hand:

#396 AFM-Calculator-Node-swagger-update
  src/domains/afm-app/api/calculator-service/node/v1/_openapi.json.tpl
Labels: env: dev, env: uat, status: applied :hand:

#417 feat: [AFM] Product subscription, kv
  src/domains/afm-app/04_apim_afm_marketplace.tf
  src/domains/afm-common/02_security.tf
Labels: env: dev, env: uat, status: applied :hand:

#410 feat: Add `X-Orginal-Host-For` header in app-gw rewrite rules
  src/core/README.md
  src/core/appgateway.tf
Labels: status: applied :hand:

#399 [CHK-617] Add test client for notifications-service
  src/domains/afm-common/README.md
  src/domains/selc-common/README.md
  src/domains/shared-app/04_apim_pagopa_notifications_service.tf
  src/domains/shared-app/README.md
  src/domains/shared-app/api/pagopa-notifications-service/v1/_base_policy.xml.tpl
Labels: env: dev, env: uat, status: applied

#419 Add ACL to enable access to web-bo and admin-panel from PagoPA on prem vpn
  src/core/README.md
  src/core/appgateway.tf
  src/core/env/dev/terraform.tfvars
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
  src/core/variables.tf
Labels: status: applied

#431 feat: [AFM] Change SNET
  src/domains/afm-common/env/weu-dev/terraform.tfvars
Labels: env: dev, status: applied :hand:

#433 fix: Deny path rules on appge UAT and PROD env
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
Labels: env: uat, env: prod, status: applied :hand:
