Repository pagopa/pagopa-infra, pull requests merged in 2022-10, with the labels that each got.

#428 [ApiConfig] Add group for Writer
  src/core/README.md
  src/core/api/apiconfig_api/auth/v1/_base_policy.xml.tpl
  src/core/apim.tf
Labels: status: applied :hand:

#445 Allow admin-panel and web-bo only from onprem vpn
  src/core/api/nodopagamenti_api/nodoServices/web-bo/v1/_base_policy.xml
  src/core/api/payment_manager_api/admin-panel/_base_policy.xml.tpl
  src/core/apim_nodo_3p_services.tf
  src/core/apim_payment_manager.tf
  src/core/appgateway.tf
Labels: status: applied :hand:

#446 feat: [AFM Calculator] Mock policy
  src/domains/afm-app/api/calculator-service/node/v1/_base_policy.xml
Labels: status: applied :hand:

#452 fix selfcare issuer
  src/domains/selc-app/04_apim_token_exchange.tf
Labels: env: dev, env: prod, status: applied :hand:

#372 [CHK-594] Add checkout for eCommerce verify payment API
  src/core/README.md
  src/core/api/checkout/checkout_ecommerce/v1/_base_policy.xml.tpl
  src/core/api/checkout/checkout_ecommerce/v1/_openapi.json.tpl
  src/core/api/checkout/checkout_ecommerce/v1/_recaptcha_check.xml.tpl
  src/core/apim_checkout.tf
Labels: env: dev, env: uat, env: prod, status: applied

#457 [CHK-672] cdn platform assets
  src/core/README.md
  src/core/assets_cdn_platform.tf
Labels: env: prod, status: applied

#468 Creare tabelle FAULT_CODE da ReEvent
  src/core/scripts/create_table_fault_code.dexp
  src/core/scripts/create_table_function.dexp
  src/core/scripts/create_table_re_event.dexp
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#463 [CHK-664] fix: update cors for UAT
  src/core/api/checkout/checkout_ecommerce/v1/_openapi.json.tpl
  src/core/apim_checkout.tf
Labels: env: uat, status: ready to apply

#453 feat: [AFM] Mock policy
  src/domains/afm-app/api/calculator-service/node/v1/_base_policy.xml
Labels: env: dev, env: uat, status: ready to apply

#444 ApiConfig-swagger-update
  src/core/api/apiconfig_api/v1/_openapi.json.tpl
Labels: env: dev, env: uat, env: prod, status: ready to apply, status: needs review

#484 [PGEC-92] Rename AFM-Utils
  src/domains/afm-app/04_apim_afm_calculator_data.tf
  src/domains/afm-app/README.md
  src/domains/afm-app/api/calculator-data-service/v1/_base_policy.xml
  src/domains/afm-app/api/calculator-data-service/v1/_openapi.json.tpl
  src/domains/afm-app/api_product/calculator_data/_base_policy.xml
Labels: env: dev, env: uat, env: prod, status: applied, status: needs review
