Repository pagopa/pagopa-infra, pull requests merged in 2023-04, with the labels that each got.

#850 feat: Poc fdr
  src/domains/fdr-app/04_apim_fdr.tf
  src/domains/fdr-app/05_tls_checker.tf
  src/domains/fdr-app/api/fdr-service/v1/_base_policy.xml.tpl
  src/domains/fdr-app/api/fdr-service/v1/_openapi.json.tpl
  src/domains/fdr-app/api_product/fdr-service/_base_policy.xml
  src/domains/fdr-app/templates/tls-cert.yaml.tpl
  src/elk-monitoring/05_elastic_stack.tf
  src/elk-monitoring/05_kibana_log_ndp.tf
  src/elk-monitoring/05_kibana_log_pagopafdr.tf
  src/elk-monitoring/env/opentelemetry_operator_helm/otel.yaml
  src/elk-monitoring/env/weu-dev/terraform.tfvars
  src/elk-monitoring/fdr/component_logs-fdr-mappings.json
  src/elk-monitoring/fdr/component_logs-fdr-settings.json
  src/elk-monitoring/fdr/ilm_policy_logs-fdr.json
  src/elk-monitoring/fdr/index_template_logs-fdr.json
  src/elk-monitoring/fdr/space.json
  src/elk-monitoring/log-template/component@custom.json
  src/elk-monitoring/log-template/component@package.json
  src/elk-monitoring/log-template/data-view.json
  src/elk-monitoring/log-template/ilm-policy.json
  src/elk-monitoring/log-template/index-template.json
  src/elk-monitoring/log-template/ingest-pipeline.json
  src/elk-monitoring/log-template/space.json
  src/elk-monitoring/ndp/nodo/ingest-pipeline.json
  src/elk-monitoring/ndp/nodocron/ingest-pipeline.json
  src/elk-monitoring/ndp/nodocronreplica/ingest-pipeline.json
  src/elk-monitoring/ndp/nodoreplica/ingest-pipeline.json
  src/elk-monitoring/ndp/pagopawebbo/ingest-pipeline.json
  src/elk-monitoring/ndp/pagopawfespwfesp/ingest-pipeline.json
  src/elk-monitoring/nodo/pipeline/component_logs-kubernetes.container_logs@custom.json
  src/elk-monitoring/nodo/pipeline/ingest_rule_pipeline.json
Labels: env: dev, status: applied :hand:

#857 fix: Update ligthbend key
  src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
Labels: status: applied :hand:

#826 PAGOPA-814 feat: Enable `p` nodo monitoring apim and update allow path
  src/core/api/nodopagamenti_api/monitoring/v1/_NodoDeiPagamenti.openapi.json.tpl
  src/core/api_config.tf
  src/core/apim_nodo_services.tf
  src/core/apim_nodo_services_dev.tf
  src/core/env/prod/terraform.tfvars
Labels: status: ready to apply

#848 [PAGOPA-841] fix: set reporting analysis subkey validation
  src/core/.terraform.lock.hcl
  src/core/apim_gpd_reporting.tf
Labels: status: applied :hand:

#845 feat: Update AFM Marketplace /Utils openapi
  src/domains/afm-app/api/marketplace-service/utils/_openapi.json.tpl
  src/domains/afm-app/api/marketplace-service/v1/_openapi.json.tpl
Labels: status: applied :hand:

#839 feat: Added cache replica apim
  src/domains/apiconfig-app/.terraform.lock.hcl
  src/domains/apiconfig-app/04_apim_api_apiconfig-cache-replica-node.tf
  src/domains/apiconfig-app/04_apim_product_apiconfig-cache-replica.tf
  src/domains/apiconfig-app/99_locals.tf
  src/domains/apiconfig-app/README.md
  src/domains/apiconfig-app/api/apiconfig-cache-replica/node/_base_policy.xml
  src/domains/apiconfig-app/api/apiconfig-cache-replica/node/_openapi_nodev1.json.tpl
  src/domains/apiconfig-app/api/apiconfig-cache-replica/node/generate_cache_fragment.xml
  src/domains/apiconfig-app/api_product/apiconfig-cache-replica/_base_policy.xml
Labels: env: dev, env: uat, status: applied :hand:

#860 feat: [PAGOPA-796] Authorizer - Multi-entity Sub-Key caching authorizator
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
  src/domains/gps-app/.terraform.lock.hcl
  src/domains/gps-app/00_data.tf
  src/domains/gps-app/04_apim_external_payments.tf
  src/domains/gps-app/99_main.tf
  src/domains/gps-app/README.md
  src/domains/gps-app/api/payments-service/v1/rest/external/_base_policy.xml
  src/domains/shared-app/.terraform.lock.hcl
  src/domains/shared-app/00_data.tf
  src/domains/shared-app/00_network.tf
  src/domains/shared-app/04_apim_authorizer.tf
  src/domains/shared-app/04_apim_reporting_orgs_enrollment.tf
  src/domains/shared-app/05_authorizer_functions.tf
  src/domains/shared-app/99_locals.tf
  src/domains/shared-app/99_main.tf
  src/domains/shared-app/99_variables.tf
  src/domains/shared-app/README.md
  src/domains/shared-app/api/authorizer/authorizer-check.xml
  src/domains/shared-app/api/authorizer/v1/_base_policy.xml
  src/domains/shared-app/api/authorizer/v1/_openapi.json.tpl
  src/domains/shared-app/api_product/_authorizer_policy.xml
  src/domains/shared-app/env/weu-dev/terraform.tfvars
  src/domains/shared-app/env/weu-prod/terraform.tfvars
  src/domains/shared-app/env/weu-uat/terraform.tfvars
  src/domains/shared-common/03_cosmosdb_authorizer.tf
  src/domains/shared-common/99_locals.tf
  src/domains/shared-common/99_variables.tf
  src/domains/shared-common/README.md
  src/domains/shared-common/env/weu-dev/terraform.tfvars
  src/domains/shared-common/env/weu-prod/terraform.tfvars
  src/domains/shared-common/env/weu-uat/terraform.tfvars
Labels: env: dev, status: applied :hand:

#875 CHK-1398-added-cartId
  src/domains/ecommerce-app/api/ecommerce-checkout/v1/_openapi.json.tpl
  src/domains/ecommerce-app/api/ecommerce-transactions-service/v1/_openapi.json.tpl
Labels: env: dev, env: uat, status: apply in progress

#863 feat: [NOD-167] Cache for dev Nexi [Only Dev env]
  src/domains/apiconfig-app/04_apim_api_apiconfig-cache-node-nexi.tf
  src/domains/apiconfig-common/02_security.tf
Labels: env: dev, status: ready to apply, status: applied :hand:

#885 CHK-1377-apim-configuration-for-openapi
  src/domains/wallet-app/04_apim_wallet.tf
  src/domains/wallet-app/api/wallet-service/v1/_base_policy.xml.tpl
  src/domains/wallet-app/api/wallet-service/v1/_openapi.json.tpl
Labels: env: dev, env: uat, status: applied

#895 [PAGOPA-868] add ENV to apiconfig
  src/core/api_config.tf
  src/domains/apiconfig-common/00_github_runner.tf
  src/domains/apiconfig-common/README.md
Labels: env: prod, status: applied :hand:

#864 fix: Error APIM on missing field req
  src/core/README.md
  src/core/api_product/nodo_pagamenti_api/decoupler/base_policy.xml.tpl
  src/core/api_product/nodo_pagamenti_api/on_error_soap_req.xml
  src/core/apim_nodo_services.tf
Labels: env: dev, env: uat, status: applied :hand:

#903 [CHK-1423] feat: update wallet api
  src/domains/wallet-app/api/wallet-service/v1/_openapi.json.tpl
Labels: env: dev, status: applied

#578 [CHK-822] Update checkout function runtime
  src/core/README.md
  src/core/checkout_function.tf
Labels: env: dev, status: applied

#866 feat: GPD-reporting migration [PAGOPA-695]
  src/aks-platform/scripts/setup.sh
  src/core/README.md
  src/core/api/gpd_api/payments-receipts/v1/_base_policy.xml
  src/core/api/gpd_api/payments-receipts/v1/_openapi.json.tpl
  src/core/api/gpd_api/payments/v1/_openapi.json.tpl
  src/core/api/gpd_api/payments/v1/rest/_base_policy.xml
  src/core/api/gpd_api/payments/v1/rest/_openapi.json.tpl
  src/core/api/gpd_api/payments/v1/soap/_base_policy.xml.tpl
  src/core/api/gpd_api/payments/v1/soap/paForNode.wsdl
  src/core/api_product/gpd/payments/rest/_base_policy.xml
  src/core/api_product/gpd/payments/soap/_base_policy.xml
  src/core/api_product/gpd/reporting_analysis/_base_policy.xml
  src/core/buyerbanks_function.tf
  src/core/env/dev/terraform.tfvars
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
  src/core/gpd.tf
  src/core/gpd_common.tf
  src/core/gpd_payments.tf
  src/core/variables.tf
  src/domains/gps-app/00_network.tf
  src/domains/gps-app/02_security.tf
  src/domains/gps-app/04_apim_gpd_reporting.tf
  src/domains/gps-app/05_gpd_reporting_functions.tf
  src/domains/gps-app/99_locals.tf
  src/domains/gps-app/99_variables.tf
  src/domains/gps-app/README.md
  src/domains/gps-app/api/payments-service/v1/rest/external/_base_policy.xml
  src/domains/gps-app/api/reporting-analysis/v1/_base_policy.xml
  src/domains/gps-app/api/reporting-analysis/v1/_openapi.json.tpl
  src/domains/gps-app/api_product/reporting-analysis/_base_policy.xml
  src/domains/gps-app/env/weu-dev/terraform.tfvars
  src/domains/gps-app/env/weu-prod/terraform.tfvars
  src/domains/gps-app/env/weu-uat/terraform.tfvars
  src/domains/gps-common/02_security.tf
  src/domains/gps-common/03_reporting_storage_account.tf
  src/domains/gps-common/99_variables.tf
  src/domains/gps-common/README.md
  src/domains/gps-common/env/weu-dev/terraform.tfvars
  src/domains/gps-common/env/weu-prod/terraform.tfvars
  src/domains/gps-common/env/weu-uat/terraform.tfvars
Labels: env: dev, env: uat, status: apply in progress, status: applied :hand:
