Repository pagopa/pagopa-infra, pull requests merged in 2023-12, with the labels that each got.

#1564 chore: Upd openapi api-config
  src/domains/apiconfig-app/api/apiconfig-selfcare-integration-service/v1/_openapi.json.tpl
  src/domains/apiconfig-app/api/apiconfig_api/v1/_openapi.json.tpl
Labels: status: applied :hand:

#1542 [PRDP-243] feat: updated receipt apim openapi
  src/domains/receipts-app/api/receipt-helpdesk/v1/_openapi.json.tpl
Labels: status: applied :hand:

#1568 Update helpdesk openapi response body
  src/domains/ecommerce-app/api/ecommerce-helpdesk-api/v1/_openapi.json.tpl
  src/domains/ecommerce-app/api/ecommerce-technical-helpdesk-api/v1/_openapi.json.tpl
Labels: env: dev, env: uat, env: prod, status: applied

#1573 feat: Fix sa backup retention configuration
  src/domains/afm-common/03_storage_account_afm.tf
  src/domains/apiconfig-common/03_storage_account.tf
  src/domains/canoneunico/03_storage_account.tf
  src/domains/fdr-common/03_storage_account_fdr.tf
  src/domains/gps-common/03_reporting_storage_account.tf
  src/domains/gps-common/03_storage_account.tf
  src/domains/nodo-common/03_storage_account_nodo_storico.tf
  src/domains/nodo-secret/storageaccount.tf
  src/domains/receipts-common/03_storage.tf
  src/domains/shared-common/03_storage_account_taxonomy.tf
  src/next-aks/01_velero.tf
Labels: status: applied :hand:

#1550 feat: [PagoPa-1361] bulk loading
  src/domains/gps-app/04_apim_gpd_core.tf
  src/domains/gps-app/05_gpd_reporting_functions.tf
  src/domains/gps-app/README.md
  src/domains/gps-app/api/gpd_api/debt-position-services/v2/_base_policy.xml
  src/domains/gps-app/api/gpd_api/debt-position-services/v2/_openapi.json.tpl
Labels: status: applied :hand:

#1582 feat(secret): add wallet paypal api key
  src/domains/wallet-common/02_security.tf
  src/domains/wallet-common/README.md
Labels: env: dev, env: uat, status: applied :hand:

#1593 [PRDP-287] chore: Add new env to pdf engine app service
  src/domains/shared-app/99_locals.tf
Labels: status: applied :hand:

#1572 fix: changed container registry reference, from ACR to GHCR
  src/domains/shared-app/05_authorizer_functions.tf
Labels: env: dev, env: uat, status: applied :hand:

#1578 [CHK-2236] feat(wallet-webview): add API endpoint to compute fees for APMs when onboarding
  src/domains/wallet-app/04_apim_payment_wallet.tf
  src/domains/wallet-app/README.md
  src/domains/wallet-app/api/webview-payment-wallet/v1/_openapi.json.tpl
  src/domains/wallet-app/api/webview-payment-wallet/v1/get_psps_policy.xml.tpl
Labels: env: dev, status: applied

#1581 add new pipeline for KPI FDR
  src/domains/observability/04_datafactory_dataset.tf
  src/domains/observability/04_datafactory_dataset_cosmos.tf
  src/domains/observability/04_datafactory_pipeline.tf
  src/domains/observability/datafactory/cosmos/BIZEVENTS_OK.json
  src/domains/observability/datafactory/cosmos/type_properties/BIZEVENTS_OK.json
  src/domains/observability/datafactory/datasets/KPI_ESITI_DAILY.json
  src/domains/observability/datafactory/datasets/KPI_RENDICONTAZIONI.json
  src/domains/observability/datafactory/datasets/KPI_RENDICONTAZIONI_DETAILS.json
  src/domains/observability/datafactory/datasets/type_properties/KPI_ESITI_DAILY.json
  src/domains/observability/datafactory/datasets/type_properties/KPI_RENDICONTAZIONI.json
  src/domains/observability/datafactory/datasets/type_properties/KPI_RENDICONTAZIONI_DETAILS.json
  src/domains/observability/datafactory/pipelines/KPI_FDR_IMPORT_ESITI.json
  src/domains/observability/datafactory/pipelines/KPI_FDR_IMPORT_ESITI_DAILY_Manuale.json
  src/domains/observability/datafactory/pipelines/KPI_FDR_IMPORT_ESITI_Manuale.json
  src/domains/observability/datafactory/pipelines/KPI_FDR_RENDICONTAZIONI.json
Labels: status: applied :hand:

#1580 feat: added Selfcare Backoffice (BE and FE) for version info
  src/domains/shared-app/04_apim_statuspage.tf
  src/domains/shared-app/README.md
  src/domains/shared-app/api/status-page-service/v1/_base_policy.xml
Labels: env: dev, env: uat, status: applied :hand:

#1608 [PRDP-302] feat: updated receipt helpdesk openapi
  src/domains/receipts-app/api/receipt-helpdesk/v1/_openapi.json.tpl
Labels: env: dev, env: uat, env: prod
