Repository pagopa/pagopa-infra, pull requests merged in 2023-08, with the labels that each got.

#1203 feat: Update openapi
  src/domains/fdr-app/api/fdr-service-internal/v1/_openapi.json.tpl
  src/domains/fdr-app/api/fdr-service/v1/_openapi.json.tpl
Labels: env: dev, env: uat, status: applied :hand:

#1207 [PRDP-95] Updated 02_security.tf
  src/domains/shared-common/02_security.tf
Labels: env: dev, env: uat, status: applied :hand:

#1206 bug:[PAGOPA-1125] unique iban
  CODEOWNERS
  src/psql/nodo/liquibase/changelog/cfg/3.22.0/db.changelog-20230705163700_update_database_object.xml
Labels: env: dev, status: applied :hand:

#1205 feat: NOD-404: Nomi storageAccount senza env nel nome
  src/domains/fdr-common/03_cosmos_mongodb_fdr.tf
  src/domains/fdr-common/03_cosmos_mongodb_fdr_re.tf
  src/domains/fdr-common/03_storage_account_fdr.tf
  src/domains/fdr-common/03_storage_account_fdr_re.tf
  src/domains/fdr-common/99_variables.tf
  src/domains/fdr-common/README.md
  src/domains/fdr-common/env/weu-prod/terraform.tfvars
  src/domains/fdr-common/env/weu-uat/terraform.tfvars
Labels: env: dev, env: uat, status: applied, tested

#1208 chore: Delete GPD-Core App Service [PAGOPA-1132]
  src/domains/gps-app/05_gpd_app_service.tf
  src/domains/gps-app/99_locals.tf
  src/domains/gps-app/README.md
  src/domains/gps-app/env/weu-dev/terraform.tfvars
  src/domains/gps-app/env/weu-prod/terraform.tfvars
  src/domains/gps-app/env/weu-uat/terraform.tfvars
  src/domains/gps-common/README.md
Labels: status: applied :hand:

#1202 feat: Add rate limit by subscription in GPD policy [PAGOPA-1130 ]
  src/domains/gps-app/04_apim_external_payments.tf
  src/domains/gps-app/04_apim_gpd_payments.tf
  src/domains/gps-app/api/gpd_api/debt-position-services/v1/_base_policy.xml
  src/domains/gps-app/api/payments-service/v1/rest/_base_policy.xml
  src/domains/gps-app/api/payments-service/v1/rest/_openapi.json.tpl
  src/domains/gps-app/api/payments-service/v1/rest/internal/_base_policy.xml
  src/domains/gps-app/api/payments-service/v1/rest/internal/_openapi.json.tpl
  src/domains/gps-app/api/reporting-analysis/v1/_base_policy.xml
Labels: status: applied :hand:

#1209 feat: Azure function xml to json
  src/domains/fdr-app/00_network.tf
  src/domains/fdr-app/02_security.tf
  src/domains/fdr-app/04_apim_fdr_xml_to_json.tf
  src/domains/fdr-app/05_fdr_xml_to_json_fn.tf
  src/domains/fdr-app/99_locals.tf
  src/domains/fdr-app/99_variables.tf
  src/domains/fdr-app/api/fdr-xml-to-json/v1/_base_policy.xml.tpl
  src/domains/fdr-app/api/fdr-xml-to-json/v1/_openapi.json.tpl
  src/domains/fdr-app/api_product/fdr-xml-to-json/_base_policy.xml
  src/domains/fdr-app/env/weu-dev/terraform.tfvars
  src/domains/fdr-app/env/weu-uat/terraform.tfvars
  src/domains/fdr-common/03_storage_account_fdr.tf
  src/domains/fdr-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/fdr-secret/secret/weu-uat/noedit_secret_enc.json
Labels: env: dev, env: uat, status: applied :hand:

#1192 [PASELC-412] create new product apim with subkey
  .gitignore
  src/domains/selfcare-app/.terraform.lock.hcl
  src/domains/selfcare-app/04_apim_selc_jwt.tf
  src/domains/selfcare-app/04_apim_selc_subkey.tf
  src/domains/selfcare-app/README.md
  src/domains/selfcare-app/api/pagopa-selfcare-ms-backoffice/jwt/v1/_base_policy.xml
  src/domains/selfcare-app/api/pagopa-selfcare-ms-backoffice/jwt/v1/_openapi.json.tpl
  src/domains/selfcare-app/api/pagopa-selfcare-ms-backoffice/subkey/v1/_base_policy.xml
  src/domains/selfcare-app/api/pagopa-selfcare-ms-backoffice/subkey/v1/_openapi.json.tpl
  src/domains/selfcare-app/terraform.sh
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#1220 feat: Taxonomy
  src/domains/shared-app/.terraform.lock.hcl
  src/domains/shared-app/00_network.tf
  src/domains/shared-app/04_apim_taxonomy.tf
  src/domains/shared-app/05_taxonomy_fn.tf
  src/domains/shared-app/99_locals.tf
  src/domains/shared-app/99_variables.tf
  src/domains/shared-app/api/taxonomy/v1/_base_policy.xml.tpl
  src/domains/shared-app/api/taxonomy/v1/_openapi.json.tpl
  src/domains/shared-app/api_product/taxonomy/_base_policy.xml
  src/domains/shared-app/env/weu-dev/terraform.tfvars
  src/domains/shared-common/.terraform.lock.hcl
  src/domains/shared-common/01_network.tf
  src/domains/shared-common/02_security.tf
  src/domains/shared-common/03_storage_account_taxonomy.tf
  src/domains/shared-common/99_variables.tf
  src/domains/shared-common/env/weu-dev/terraform.tfvars
  src/domains/shared-common/env/weu-prod/terraform.tfvars
  src/domains/shared-common/env/weu-uat/terraform.tfvars
Labels: env: dev, status: applied :hand:

#1225 [PAGOPA-1143] feat: added API set for authorizer configurator
  src/domains/shared-app/04_apim_authorizer.tf
  src/domains/shared-app/04_apim_authorizer_config.tf
  src/domains/shared-app/api/authorizer-config/v1/_base_policy.xml
  src/domains/shared-app/api/authorizer-config/v1/_openapi.json.tpl
  src/domains/shared-common/02_security.tf
Labels: env: dev, status: applied :hand:

#1097 Kibana pagopa
  src/elk-monitoring/05_elastic_stack.tf
  src/elk-monitoring/05_kibana_log_pagopa_general.tf
  src/elk-monitoring/README.md
  src/elk-monitoring/pagopa/data-view.json
  src/elk-monitoring/pagopa/ingest-pipeline.json
  src/elk-monitoring/pagopa/logs-kubernetes.container_logs@custom.json
  src/elk-monitoring/pagopa/space.json
  src/elk-monitoring/terraform.sh
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#1231 feat: Fdr
  src/domains/fdr-app/api/fdr-service-internal/v1/_openapi.json.tpl
  src/domains/fdr-app/api/fdr-service/v1/_openapi.json.tpl
Labels: env: dev, status: applied

#1190 feat: [Nodo][NOD-400] Added node tech support secrets(re cosmos connection string)
  src/domains/nodo-app/04_apim_nodo_technical_support.tf
  src/domains/nodo-secret/02_security.tf
  src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
  src/elk-monitoring/05_kibana_log_ndp_tech_support.tf
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#1216 [PAGOPA-1099] Switch APICONFIG to AKS
  src/domains/apiconfig-app/00_alert_apiconfig_cache.tf
  src/domains/apiconfig-app/00_alert_apiconfig_core.tf
  src/domains/apiconfig-app/04_apim_api_apiconfig-selfcare-integration.tf
  src/domains/apiconfig-app/04_apim_api_config.tf
  src/domains/apiconfig-app/README.md
  src/domains/apiconfig-app/api/apiconfig_api/jwt/v1/_base_policy.xml.tpl
  src/domains/apiconfig-app/api/apiconfig_api/subkey/v1/_base_policy.xml.tpl
  src/domains/apiconfig-app/remove_apiconfig_resources.sh
Labels: status: applied :hand:

#1238 chore: Update alert logic [GPD]
  src/domains/gps-app/00_alert_gpd_core.tf
  src/domains/gps-app/00_alert_gpd_payments.tf
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#1215 chore: Update GPD-Core OpenAPI
  src/domains/gps-app/api/gpd_api/debt-position-services/v1/_openapi.json.tpl
  src/domains/gps-app/api/gpd_api/v1/_openapi.json.tpl
Labels: env: dev, status: applied

#1240 feat: Fix_function_url
  src/domains/shared-app/05_taxonomy_fn.tf
  src/domains/shared-app/99_locals.tf
Labels: env: dev, status: applied :hand:

#1245 [NOD-415] Taxonomy alarms
  src/domains/shared-app/00_alert_taxonomy.tf
  src/domains/shared-app/00_monitor.tf
  src/domains/shared-app/99_locals.tf
Labels: env: dev, status: applied :hand:

#1247 feat: Add secret for prf test ReceiptGeneratorService
  src/domains/receipts-secrets/secret/weu-dev/noedit_secret_enc.json
  src/domains/receipts-secrets/secret/weu-uat/noedit_secret_enc.json
Labels: status: applied :hand:

#1242 feat: Account SES to sent mail bo platform pagoPA
  src/core/README.md
  src/core/dns_selfcare_backoffice_plaftorm.tf
Labels: status: applied :hand:

#1253 fix: Dkim aws ses backoffice-platform-pagopa-it
  src/core/dns_selfcare_backoffice_plaftorm.tf
Labels: status: applied :hand:

#1257 feat: Add webhook receipt secrets
  src/domains/receipts-secrets/secret/weu-dev/noedit_secret_enc.json
  src/domains/receipts-secrets/secret/weu-uat/noedit_secret_enc.json
Labels: status: applied :hand:

#1258 feat(secret): [CHK-1823] add secrets for NPG cards method keys
  src/domains/ecommerce-common/02_security.tf
  src/domains/ecommerce-common/README.md
Labels: env: dev, env: uat, env: prod, status: apply in progress

#1261 feat: Fix apim json to xml
  src/domains/fdr-app/04_apim_fdr_json_to_xml.tf
  src/domains/fdr-app/04_apim_fdr_xml_to_json.tf
  src/domains/fdr-app/99_locals.tf
Labels: env: dev, env: uat, status: applied :hand:

#1264 [PAGOPA-1109] Authorizer - Adding metadata on authorization strings
  src/domains/shared-app/api/authorizer/authorizer-check.xml
  src/domains/shared-app/api/authorizer/v1/_base_policy.xml
  src/domains/shared-app/api/authorizer/v1/_openapi.json.tpl
Labels: env: dev, env: uat, status: applied :hand:
