Repository pagopa/pagopa-infra, pull requests merged in 2023-06, with the labels that each got.

#977 feat: Migrate GPD from core to GPS domain [DIS-3-gpd-core]
  src/core/README.md
  src/core/api/gpd_api/debt-position-services/v1/_openapi.json.tpl
  src/core/api/gpd_api/v1/_openapi.json.tpl
  src/core/api_logs.tf
  src/core/env/dev/terraform.tfvars
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
  src/core/gpd.tf
  src/core/gpd_common.tf
  src/core/postgresql.tf
  src/core/postgresql_gpd.tf
  src/core/security.tf
  src/domains/gps-app/00_data.tf
  src/domains/gps-app/00_network.tf
  src/domains/gps-app/02_security.tf
  src/domains/gps-app/04_apim_gpd_core.tf
  src/domains/gps-app/04_apim_logs.tf
  src/domains/gps-app/05_gpd_app_service.tf
  src/domains/gps-app/99_locals.tf
  src/domains/gps-app/99_variables.tf
  src/domains/gps-app/README.md
  src/domains/gps-app/api/gpd_api/debt-position-services/v1/_base_policy.xml
  src/domains/gps-app/api/gpd_api/debt-position-services/v1/_openapi.json.tpl
  src/domains/gps-app/api/gpd_api/v1/_base_policy.xml
  src/domains/gps-app/api/gpd_api/v1/_openapi.json.tpl
  src/domains/gps-app/api/payments-service/v1/rest/external/_base_policy.xml
  src/domains/gps-app/api_product/gpd/_base_policy.xml
  src/domains/gps-app/api_product/gpd/debt-position-services/_base_policy.xml
  src/domains/gps-app/env/weu-dev/terraform.tfvars
  src/domains/gps-app/env/weu-prod/terraform.tfvars
  src/domains/gps-app/env/weu-uat/terraform.tfvars
  src/domains/gps-common/.terraform.lock.hcl
  src/domains/gps-common/02_security.tf
  src/domains/gps-common/03_postgresql_gpd.tf
  src/domains/gps-common/99_variables.tf
  src/domains/gps-common/README.md
  src/domains/gps-common/env/weu-dev/terraform.tfvars
  src/domains/gps-common/env/weu-prod/terraform.tfvars
  src/domains/gps-common/env/weu-uat/terraform.tfvars
Labels: status: applied :hand:

#1003 PAGOPA-976 creating new product and inserting apis
  src/domains/gps-app/04_apim_gpd_for_pn.tf
  src/domains/gps-app/api/pn-integration/_base_policy.xml
  src/domains/gps-app/api/pn-integration/_openapi.json.tpl
  src/domains/gps-app/api_product/pn-integration/_base_policy.xml
  src/domains/shared-app/04_apim_enrolled_ec.tf
Labels: status: applied :hand:

#858 feat: adding cosmos db and table PAGOPA-848
  src/domains/gps-app/api/payments-service/v1/rest/external/_openapi.json.tpl
  src/domains/gps-common/.terraform.lock.hcl
  src/domains/gps-common/02_security.tf
  src/domains/gps-common/03_cosmosdb.tf
  src/domains/gps-common/03_storage_account.tf
  src/domains/gps-common/99_main.tf
  src/domains/gps-common/99_variables.tf
  src/domains/gps-common/README.md
  src/domains/gps-common/env/weu-dev/terraform.tfvars
  src/domains/gps-common/env/weu-prod/terraform.tfvars
  src/domains/gps-common/env/weu-uat/terraform.tfvars
Labels: env: dev, env: uat, status: applied :hand:

#981 Pagopa 911 biz evt test gestione eventi negativi per pdnd
  src/domains/bizevents-common/01_events.tf
  src/domains/bizevents-common/02_security.tf
  src/domains/bizevents-common/README.md
Labels: env: dev, status: applied :hand:

#946 fix: Selfcare mongo access
  src/domains/selfcare-common/03_cosmosdb_bopagopa_datastore.tf
Labels: env: uat, status: applied :hand:

#962 feat: NOD-260-change-node-pool-number-user
  src/aks-platform/01_network.tf
  src/aks-platform/env/weu-dev/terraform.tfvars
  src/aks-platform/env/weu-prod/terraform.tfvars
  src/aks-platform/env/weu-uat/terraform.tfvars
Labels: status: applied :hand:

#1012 [PAGOPA-974] feat: added new API for retrieve application codes
  src/domains/apiconfig-app/api/apiconfig-selfcare-integration/v1/_openapi.json.tpl
  src/domains/gps-app/04_apim_gpd_for_pn.tf
  src/domains/gps-app/api/pn-integration/_base_policy.xml
  src/domains/shared-app/04_apim_enrolled_ec.tf
Labels: status: applied :hand:

#732 AFM-Calculator-swagger-update
  src/domains/afm-app/api/calculator-service/v1/_openapi.json.tpl
Labels: env: dev, env: uat, no apply, status: applied :hand:

#928 new wsdl for GPS payments
  src/domains/gps-app/api/payments-service/v1/soap/paForNode.wsdl
  src/domains/shared-common/00_github_runner.tf
Labels: status: applied :hand:

#1021 fix: add aks dns record
  src/core/README.md
  src/domains/aca-common/01_network.tf
  src/domains/aca-common/99_locals.tf
  src/domains/aca-common/README.md
Labels: env: dev, env: uat, status: applied

#1017 CHK-1582-openapi-aca
  src/domains/aca-app/04_apim_aca.tf
  src/domains/aca-app/README.md
  src/domains/aca-app/api/aca/v1/_base_policy.xml.tpl
  src/domains/aca-app/api/aca/v1/_openapi.json.tpl
  src/domains/aca-common/02_security.tf
Labels: status: needs review

#1038 feat: Add ses aws dns config `platform.pagopa.it`
  src/core/README.md
  src/core/apim_mock_ec.tf
  src/core/apim_mock_payment_gateway.tf
  src/core/dns_plaftorm.tf
Labels: status: applied :hand:

#1035 feat: NOD-299: Fix connection string blob storage
  src/domains/fdr-secret/secret/weu-dev/noedit_secret_enc.json
Labels: env: dev, status: applied

#1031 [PAGOPA-997] Change on Authorizer HTTP response status
  src/domains/shared-app/api/authorizer/authorizer-check.xml
Labels: env: dev, env: uat, status: applied :hand:

#1037 [PAGOPA-973] feat: added new API for retrieve segregation codes
  src/domains/apiconfig-app/api/apiconfig-selfcare-integration/v1/_openapi.json.tpl
  src/domains/apiconfig-app/env/weu-prod/terraform.tfvars
Labels: status: applied :hand:

#1034 [PRDP-34] feat: Introducing pdf_engine apim in shared domain
  src/core/apim_mock_ec.tf
  src/core/apim_mock_payment_gateway.tf
  src/domains/shared-app/04_apim_iuvgenerator.tf
  src/domains/shared-app/04_apim_pdf_engine.tf
  src/domains/shared-app/04_apim_reporting_orgs_enrollment.tf
  src/domains/shared-app/README.md
  src/domains/shared-app/api/pdf-engine/v1/_base_policy.xml
  src/domains/shared-app/api/pdf-engine/v1/_openapi.json.tpl
  src/domains/shared-app/api_product/_base_policy.xml
  src/domains/shared-app/api_product/_base_policy_forbid.xml
  src/domains/shared-app/terraform.sh
Labels: env: dev, env: uat, status: applied :hand:

#1042 chore: Update api-config-core OpenAPI JSON
  src/domains/apiconfig-app/04_apim_api_config.tf
  src/domains/apiconfig-app/api/apiconfig-core/oauth/v1/_openapi.json.tpl
  src/domains/apiconfig-app/api/apiconfig-core/subkey/v1/_openapi.json.tpl
  src/domains/apiconfig-app/api/apiconfig_api/v1/_openapi.json.tpl
Labels: status: applied :hand:

#1045 [PRDP-34] fix: Update pdf-engine openapi specs
  src/domains/shared-app/api/pdf-engine/v1/_openapi.json.tpl
Labels: env: dev, env: uat, status: applied :hand:

#1050 [PRDP-35] feat: add receipt secrets
  src/domains/receipts-secrets/secret/weu-dev/noedit_secret_enc.json
Labels: env: dev, status: applied :hand:

#1054 [PAGOPA-996] feat: updated Authorizer enrolled EC's API
  src/domains/shared-app/02_keyvault.tf
  src/domains/shared-app/05_authorizer_functions.tf
  src/domains/shared-app/api/enrolled-orgs/v1/_openapi.json.tpl
  src/domains/shared-common/02_security.tf
Labels: env: dev, env: uat, status: applied :hand:

#1058 feat: PAGOPA-1027 nuovo prodotto aca
  src/domains/apiconfig-app/04_apim_api_config.tf
  src/domains/apiconfig-app/README.md
  src/domains/gps-app/04_apim_gpd_core.tf
  src/domains/gps-app/04_apim_gpd_for_pn_aca.tf
  src/domains/gps-app/README.md
  src/domains/gps-app/api_product/aca-integration/_base_policy.xml
Labels: status: applied :hand:

#1061 feat(ecommerce): add api key auth header
  src/domains/aca-common/README.md
  src/domains/ecommerce-app/README.md
  src/domains/ecommerce-app/api/ecommerce-payment-methods-service/v1/_openapi.json.tpl
  src/domains/ecommerce-app/api/ecommerce-payment-requests-service/v1/_openapi.json.tpl
  src/domains/ecommerce-app/api/ecommerce-transaction-auth-requests-service/v1/_openapi.json.tpl
  src/domains/ecommerce-app/api/ecommerce-transaction-user-receipts-service/v1/_openapi.json.tpl
  src/domains/ecommerce-app/api/ecommerce-transactions-service/v1/_openapi.json.tpl
  src/domains/ecommerce-common/02_security.tf
  src/domains/ecommerce-common/README.md
Labels: env: dev, env: uat, env: prod, status: applied

#1068 fix: Receipt domain dev secret
  src/domains/receipts-secrets/secret/weu-dev/noedit_secret_enc.json
Labels: env: dev, status: applied :hand:

#1070 [PAGOPA-1022] Adding missing microservice status indicators
  src/domains/shared-app/.terraform.lock.hcl
  src/domains/shared-app/04_apim_statuspage.tf
Labels: env: dev, env: uat, status: applied :hand:

#1074 Fix receipt domain dev secret
  src/domains/receipts-secrets/secret/weu-dev/noedit_secret_enc.json
Labels: env: dev, status: applied :hand:

#1077 [PAGOPA-1031] Resolving static setting of GPD reporting's KeyVault secrets
  src/domains/gps-common/.terraform.lock.hcl
  src/domains/gps-common/02_security.tf
Labels: status: applied :hand:

#1072 Pagopa 960 sviluppo migrazione dati storage to cosmos e applicazione in uat e prod
  src/domains/gps-app/api/payments-service/v1/rest/external/_openapi.json.tpl
  src/domains/gps-common/02_security.tf
Labels: status: applied :hand:

#1073 chore: Update gpd-core settings [PAGOPA-1038]
  src/domains/gps-app/00_data.tf
  src/domains/gps-app/99_locals.tf
Labels: env: dev, status: applied :hand:

#1078 feat: creazione table storage per api cfg PAGOPA-1009
  src/domains/apiconfig-common/02_security.tf
  src/domains/apiconfig-common/03_storage_account.tf
  src/domains/apiconfig-common/99_variables.tf
  src/domains/apiconfig-common/README.md
Labels: status: applied :hand:

#1080 [PRDP-48] feat: introducing receipt uat secrets
  src/domains/receipts-secrets/02_security.tf
  src/domains/receipts-secrets/secret/weu-dev/noedit_secret_enc.json
  src/domains/receipts-secrets/secret/weu-uat/noedit_secret_enc.json
Labels: env: uat

#1084 [PRDP-43] feat: update receipt domain with notifier components
  src/domains/receipts-common/.terraform.lock.hcl
  src/domains/receipts-common/03_cosmosdb.tf
  src/domains/receipts-common/03_storage.tf
Labels: env: dev, env: uat

#1096 fix: Refactor 3.22 3.21 nodo's liquibase into 3.20 for iban tables
  src/psql/nodo/liquibase/changelog/cfg/3.20.0/db.changelog-20230609153200_new_iban_tables.xml
  src/psql/nodo/liquibase/changelog/cfg/3.21.0/db.changelog-20230616115000_add_column_duedate_to_iban.xml
  src/psql/nodo/liquibase/changelog/cfg/3.22.0/db.changelog-20230619163000_add_column_and_drop_foreignkey.xml
  src/psql/nodo/liquibase/changelog/cfg/db.changelog-master-3.21.0.xml
  src/psql/nodo/liquibase/changelog/cfg/db.changelog-master-3.22.0.xml
  src/psql/nodo/liquibase/changelog/offline/db.changelog-master-3.21.0.xml
  src/psql/nodo/liquibase/changelog/offline/db.changelog-master-3.22.0.xml
  src/psql/nodo/liquibase/changelog/online/db.changelog-master-3.21.0.xml
  src/psql/nodo/liquibase/changelog/online/db.changelog-master-3.22.0.xml
  src/psql/nodo/liquibase/changelog/re/db.changelog-master-3.21.0.xml
  src/psql/nodo/liquibase/changelog/re/db.changelog-master-3.22.0.xml
  src/psql/nodo/liquibase/changelog/wfesp/db.changelog-master-3.21.0.xml
  src/psql/nodo/liquibase/changelog/wfesp/db.changelog-master-3.22.0.xml
  src/psql/nodo/liquibase/run.sh
Labels: env: dev, status: applied :hand:

#1095 [PRDP-55] chore: refactored internal secrets to be managed through re…
  src/domains/receipts-secrets/02_security.tf
  src/domains/receipts-secrets/secret/weu-dev/noedit_secret_enc.json
Labels: env: dev, env: uat, status: applied :hand:

#1062 feat: creation of Mocker domain
  src/domains/mock-app/.terraform.lock.hcl
  src/domains/mock-app/00_azuread.tf
  src/domains/mock-app/00_data.tf
  src/domains/mock-app/00_monitor.tf
  src/domains/mock-app/00_network.tf
  src/domains/mock-app/01_aks.tf
  src/domains/mock-app/02_namespace.tf
  src/domains/mock-app/02_security.tf
  src/domains/mock-app/03_serviceaccounts_azure_devops.tf
  src/domains/mock-app/04_apim_mocker.tf
  src/domains/mock-app/04_apim_product_mocker.tf
  src/domains/mock-app/06_aks_middleware_tools.tf
  src/domains/mock-app/99_locals.tf
  src/domains/mock-app/99_main.tf
  src/domains/mock-app/99_variables.tf
  src/domains/mock-app/README.md
  src/domains/mock-app/api/mocker-core/v1/_base_policy.xml
  src/domains/mock-app/api/mocker-core/v1/_openapi.json.tpl
  src/domains/mock-app/api_product/v1/_base_policy.xml
  src/domains/mock-app/env/weu-dev/backend.tfvars
  src/domains/mock-app/env/weu-dev/terraform.tfvars
  src/domains/mock-app/env/weu-uat/terraform.tfvars
  src/domains/mock-app/helm/cert-mounter.yaml.tpl
  src/domains/mock-app/k8setup.sh
  src/domains/mock-common/.terraform.lock.hcl
  src/domains/mock-common/00_azuread.tf
  src/domains/mock-common/00_monitor.tf
  src/domains/mock-common/01_network.tf
  src/domains/mock-common/02_security.tf
  src/domains/mock-common/03_postgresql.tf
  src/domains/mock-common/99_locals.tf
  src/domains/mock-common/99_variables.tf
  src/domains/mock-common/README.md
  src/domains/mock-common/env/weu-dev/terraform.tfvars
  src/domains/mock-common/env/weu-uat/terraform.tfvars
Labels: env: dev, status: applied :hand:

#1089 feat: adding env variable to api-cfg PAGOPA-1010
  src/domains/apiconfig-app/00_data.tf
  src/domains/apiconfig-app/99_variables.tf
  src/domains/apiconfig-app/README.md
  src/domains/apiconfig-app/api_config.tf
Labels: env: dev, status: apply in progress

#1108 feat: Disable lmi on pagopa apim platform
  src/core/env/dev/terraform.tfvars
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
Labels: status: applied :hand:

#1110 feat: Add `description` iban master table
  src/psql/nodo/liquibase/changelog/cfg/3.21.0/db.changelog-20230628150500_upd_iban_master_table.xml
  src/psql/nodo/liquibase/changelog/cfg/db.changelog-master-3.21.0.xml
  src/psql/nodo/liquibase/changelog/offline/db.changelog-master-3.21.0.xml
  src/psql/nodo/liquibase/changelog/online/db.changelog-master-3.21.0.xml
  src/psql/nodo/liquibase/changelog/re/db.changelog-master-3.21.0.xml
  src/psql/nodo/liquibase/changelog/wfesp/db.changelog-master-3.21.0.xml
  src/psql/nodo/liquibase/run.sh
Labels: env: dev, status: applied :hand:

#1099 [PRDP-54] feat: updated storage policies
  src/domains/receipts-common/03_storage.tf
  src/domains/receipts-common/99_variables.tf
  src/domains/receipts-common/README.md
Labels: env: dev, env: uat

#1109 [PRDP-56] feat: introducing receipt error container in cosmosdb.tf
  src/domains/receipts-common/03_cosmosdb.tf
Labels: env: dev, env: uat, status: applied :hand:

#1101 Chk 1669 gec mock
  src/domains/ecommerce-app/04_apim_ecommerce_mock.tf
  src/domains/ecommerce-app/README.md
  src/domains/ecommerce-app/api/ecommerce-mock/gec/v1/_base_policy.xml.tpl
  src/domains/ecommerce-app/api/ecommerce-mock/gec/v1/_openapi.json.tpl
  src/domains/fdr-app/02_function.tf
  src/domains/fdr-app/README.md
  src/domains/nodo-app/README.md
  src/domains/receipts-secrets/README.md
  src/domains/wallet-app/README.md
Labels: env: uat, status: applied :hand:
