Repository pagopa/pagopa-infra, pull requests merged in 2023-07, with the labels that each got.

#1090 [PAGOPA-1028] New API for retrieve enrolled CI's station
  src/domains/shared-app/.terraform.lock.hcl
  src/domains/shared-app/04_apim_statuspage.tf
  src/domains/shared-app/05_authorizer_functions.tf
  src/domains/shared-app/api/enrolled-orgs/v1/_openapi.json.tpl
  src/domains/shared-app/env/weu-prod/terraform.tfvars
  src/domains/shared-common/.terraform.lock.hcl
  src/domains/shared-common/00_monitor.tf
  src/domains/shared-common/02_security.tf
  src/domains/shared-common/99_locals.tf
  src/domains/shared-common/README.md
  src/domains/shared-common/env/weu-uat/terraform.tfvars
Labels: status: applied :hand:

#961 feat: Add nodo api alert responsetime + availability
  .gitignore
  src/domains/nodo-app/00_alert.tf
  src/domains/nodo-app/00_data.tf
  src/domains/nodo-app/00_monitor.tf
  src/domains/nodo-app/99_locals.tf
  src/domains/nodo-app/README.md
  src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json
Labels: env: prod, status: applied :hand:

#1055 feat: [NOD-150] API-CFG Alarms
  src/core/README.md
  src/core/security.tf
  src/domains/apiconfig-app/00_alert_apiconfig_cache.tf
  src/domains/apiconfig-app/00_alert_apiconfig_core.tf
  src/domains/apiconfig-app/00_monitor.tf
  src/domains/apiconfig-app/02_security.tf
  src/domains/apiconfig-app/99_locals.tf
  src/domains/apiconfig-app/README.md
  src/domains/apiconfig-app/api_config.tf
Labels: status: applied :hand:

#1118 [PAGOPA-1012] feat: updated ApiConfig's OpenAPI
  src/domains/apiconfig-app/.terraform.lock.hcl
  src/domains/apiconfig-app/api/apiconfig-core/oauth/v1/_openapi.json.tpl
  src/domains/apiconfig-app/api/apiconfig-core/subkey/v1/_openapi.json.tpl
Labels: status: applied :hand:

#1123 [PRDP-58] feat: appinsight datastore logs
  src/domains/receipts-app/.terraform.lock.hcl
  src/domains/receipts-app/00_alert.tf
  src/domains/receipts-app/00_azuread.tf
  src/domains/receipts-app/README.md
Labels: env: dev, env: uat

#1126 feat: Add mock-io appi 4 pdf-receipt
  src/domains/mock-app/04_apim_mock_4_receipt_pdf.tf
  src/domains/mock-app/README.md
  src/domains/mock-app/api/mock_4_receipt_pdf/v1/_base_policy.xml
  src/domains/mock-app/api/mock_4_receipt_pdf/v1/_swagger.json.tpl
  src/domains/mock-app/api_product/mock_4_receipt_pdf/_base_policy.xml
Labels: env: dev, env: uat, status: applied :hand:

#1127 [PAGOPA-1073] feat: Exposing /info API for Status Page
  src/domains/shared-app/04_apim_statuspage.tf
  src/domains/shared-app/api/enrolled-orgs/v1/_openapi.json.tpl
Labels: status: applied :hand:

#1132 feat: updated mocks for receipt pdf
  src/domains/mock-app/api/mock_4_receipt_pdf/v1/_base_policy.xml
Labels: env: dev, env: uat, status: applied :hand:

#1039 feat: [NOD-241][NOD-242] riversamento re
  src/core/README.md
  src/core/dns_private.tf
  src/core/env/dev/terraform.tfvars
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
  src/domains/nodo-app/.terraform.lock.hcl
  src/domains/nodo-app/00_network.tf
  src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
  src/domains/nodo-app/99_locals.tf
  src/domains/nodo-app/99_variables.tf
  src/domains/nodo-app/README.md
  src/domains/nodo-app/env/weu-dev/terraform.tfvars
  src/domains/nodo-app/env/weu-prod/terraform.tfvars
  src/domains/nodo-app/env/weu-uat/terraform.tfvars
  src/domains/nodo-common/.terraform.lock.hcl
  src/domains/nodo-common/01_network.tf
  src/domains/nodo-common/03_cosmos_mongo_db.tf
  src/domains/nodo-common/03_storage_account_nodo_re.tf
  src/domains/nodo-common/03_storage_account_nodo_storico.tf
  src/domains/nodo-common/04_datafactory_dataflow.tf
  src/domains/nodo-common/04_datafactory_dataset.tf
  src/domains/nodo-common/04_datafactory_pipeline.tf
  src/domains/nodo-common/04_datafactory_trigger.tf
  src/domains/nodo-common/99_locals.tf
  src/domains/nodo-common/99_variables.tf
  src/domains/nodo-common/README.md
  src/domains/nodo-common/env/weu-dev/terraform.tfvars
  src/domains/nodo-common/env/weu-prod/terraform.tfvars
  src/domains/nodo-common/env/weu-uat/terraform.tfvars
Labels: env: dev, env: uat, env: prod, status: ready to apply, status: applied :hand:

#1102 fix(configuration) GPD and API-CONFIG for ACA
  src/domains/apiconfig-app/api/apiconfig_api/subkey/v1/_base_policy.xml.tpl
  src/domains/gps-app/api/gpd_api/debt-position-services/v1/_base_policy.xml
Labels: env: dev, env: uat, status: applied :hand:

#1133 [PAGOPA-1075] feat: add enhancement for Status Page
  src/domains/canoneunico/02_function.tf
  src/domains/canoneunico/99_variables.tf
  src/domains/canoneunico/env/dev/terraform.tfvars
  src/domains/canoneunico/env/prod/terraform.tfvars
  src/domains/canoneunico/env/uat/terraform.tfvars
  src/domains/shared-app/04_apim_statuspage.tf
Labels: env: dev, env: uat, status: applied :hand:

#1135 [PRDP-42] feat: add service apim in receipt-app
  src/domains/mock-app/.terraform.lock.hcl
  src/domains/receipts-app/04_apim_receipts.tf
  src/domains/receipts-app/README.md
  src/domains/receipts-app/api/receipt-service/v1/_base_policy.xml
  src/domains/receipts-app/api/receipt-service/v1/_openapi.json.tpl
  src/domains/receipts-app/api_product/_base_policy.xml
  src/domains/receipts-app/api_product/receipt-service/_base_policy.xml
Labels: env: dev, env: uat, status: applied :hand:

#1128 [PRDP-45] feat: Introducing io apim subkey secret
  src/domains/receipts-secrets/secret/weu-dev/noedit_secret_enc.json
  src/domains/receipts-secrets/secret/weu-uat/noedit_secret_enc.json
Labels: env: dev, env: uat, status: applied :hand:

#1134 feat: Enable link redis cache on apim prod
  src/core/env/prod/terraform.tfvars
Labels: status: applied :hand:

#1138 fix: Add fdr monitoring on nodo-auth nodo_per_psp
  src/core/README.md
  src/core/api/nodopagamenti_api/nodoPerPsp/v1/fdr_nodoinvia_flussorendicontazione_flow.xml
  src/core/apim_nodo_services.tf
  src/core/apim_nodo_services_auth.tf
  src/core/apim_nodo_services_dev.tf
  src/core/env/dev/terraform.tfvars
  src/domains/fdr-app/00_data.tf
  src/domains/fdr-app/04_apim_fdr.tf
  src/domains/fdr-app/README.md
Labels: status: applied :hand:

#1140 [PRDP-53] feat: Updated notifier secrets
  src/domains/receipts-secrets/secret/weu-uat/noedit_secret_enc.json
Labels: env: uat, status: applied :hand:

#1141 [PRDP-62] feat: add pdf-engine alerts
  src/domains/shared-app/00_apim_pdf_engine_alert.tf
  src/domains/shared-app/README.md
Labels: env: prod, status: applied :hand:

#1142 [PAGOPA-1023] fix: updated OpenAPI for AFM-Calculator
  src/domains/afm-app/api/calculator-service/node/v1/_openapi.json.tpl
  src/domains/afm-app/api/calculator-service/v1/_openapi.json.tpl
Labels: env: dev, env: uat, status: applied :hand:

#1129 feat: [PAGOPA-978] iban integration: update database for new iban tables
  src/psql/nodo/liquibase/changelog/cfg/3.22.0/db.changelog-20230705163700_add_unique_to_id_dominio.xml
  src/psql/nodo/liquibase/changelog/cfg/3.22.0/db.changelog-20230705163700_update_database_object.xml
  src/psql/nodo/liquibase/changelog/cfg/db.changelog-master-3.22.0.xml
  src/psql/nodo/liquibase/run.sh
Labels: env: dev, status: applied :hand:

#1149 feat: [APIConfig Cache] Added alert on jdbc connection
  src/domains/apiconfig-app/00_alert_apiconfig_cache.tf
  src/domains/apiconfig-app/99_locals.tf
Labels: env: dev, env: uat, env: prod, status: ready to apply, status: applied :hand:

#1107 feat: [NOD-264] API assistenza product
  src/domains/apiconfig-app/04_apim_api_config.tf
  src/domains/nodo-app/04_apim_apiconfig.tf
  src/domains/nodo-app/04_apim_nodo_technical_support.tf
  src/domains/nodo-app/api/technical-support-service/v1/_base_policy.xml
  src/domains/nodo-app/api/technical-support-service/v1/_openapi.json.tpl
  src/domains/shared-app/04_apim_technical_support.tf
  src/domains/shared-app/api_product/_technical_support_policy.xml
Labels: env: dev, env: uat, env: prod, status: ready to apply, status: applied :hand:

#1150 feat: [NODO] Added key apim-subscription-key in prod
  src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json
Labels: env: prod, status: applied :hand:

#1147 feat: create GPD integration product [PAGOPA-1057]
  src/domains/gps-app/04_apim_external_payments.tf
  src/domains/gps-app/04_apim_gpd.tf
  src/domains/gps-app/04_apim_gpd_core.tf
  src/domains/gps-app/04_apim_gpd_reporting.tf
  src/domains/gps-app/README.md
Labels: status: applied :hand:

#1153 fix: Api backend receipt service
  src/domains/receipts-app/api/receipt-service/v1/_base_policy.xml
Labels: env: dev, env: uat, status: applied :hand:

#1159 fix: Alert config nodo apicfg forwarder
  src/core/node_forwarder.tf
  src/domains/apiconfig-app/00_alert_apiconfig_core.tf
  src/domains/apiconfig-app/README.md
  src/domains/nodo-app/00_alert.tf
  src/domains/nodo-app/04_apim_nodo_technical_support.tf
  src/domains/nodo-app/README.md
Labels: status: applied :hand:

#1155 feat: [NOD-387] NODO-RE: added staging and autoscale
  src/domains/nodo-app/00_network.tf
  src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
  src/domains/nodo-app/99_variables.tf
  src/domains/nodo-app/env/weu-dev/terraform.tfvars
  src/domains/nodo-app/env/weu-prod/terraform.tfvars
  src/domains/nodo-app/env/weu-uat/terraform.tfvars
  src/domains/nodo-common/01_network.tf
  src/domains/nodo-common/03_cosmos_mongo_db.tf
  src/domains/nodo-common/03_storage_account_nodo_re.tf
  src/domains/nodo-common/03_storage_account_nodo_storico.tf
  src/domains/nodo-common/99_locals.tf
  src/domains/nodo-common/env/weu-prod/terraform.tfvars
  src/domains/nodo-common/env/weu-uat/terraform.tfvars
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#1158 feat: [Nodo] Added node tech support secrets
  src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#1169 feat: Add GPD OpsGenie alerts [PAGOPA-1069]
  src/domains/gps-app/00_alert_gpd_core.tf
  src/domains/gps-app/00_alert_gpd_payments.tf
  src/domains/gps-app/00_monitor.tf
  src/domains/gps-app/99_locals.tf
  src/domains/gps-app/README.md
  src/domains/gps-common/00_monitor.tf
  src/domains/gps-common/03_postgresql_gpd.tf
  src/domains/gps-common/99_locals.tf
  src/domains/gps-common/99_variables.tf
  src/domains/gps-common/README.md
  src/domains/gps-common/env/weu-dev/terraform.tfvars
  src/domains/gps-common/env/weu-prod/terraform.tfvars
  src/domains/gps-common/env/weu-uat/terraform.tfvars
Labels: status: applied :hand:

#1171 Chore: updated receipts APIM
  src/domains/mock-app/api/mock_4_receipt_pdf/v1/_base_policy.xml
  src/domains/receipts-app/api/receipt-service/v1/_base_policy.xml
  src/domains/receipts-app/api/receipt-service/v1/_openapi.json.tpl
Labels: env: dev, env: uat, status: applied :hand:

#1175 feat: add receipts secrets
  src/domains/receipts-secrets/02_security.tf
  src/domains/receipts-secrets/README.md
Labels: env: dev, env: uat, status: applied :hand:

#1176 fix: [NOD-387] Autoscaling improvements
  src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
Labels: env: prod, status: applied :hand:

#1154 chore: gpd-core from app-service to aks [PAGOPA-692]
  src/domains/gps-app/04_apim_gpd_core.tf
  src/domains/gps-app/99_locals.tf
  src/domains/gps-app/api/gpd_api/debt-position-services/v1/_base_policy.xml
Labels: env: dev, env: uat, status: applied :hand:

#1178 upd: update gpd pmnts cosmos table tp PAGOPA-1083
  src/domains/gps-common/03_cosmosdb.tf
Labels: status: applied :hand:

#1179 [PAGOPA-1112] fix: resolved bug on locked internal state
  src/domains/shared-app/api/authorizer/authorizer-check.xml
  src/domains/shared-app/api/authorizer/v1/_base_policy.xml
Labels: status: applied :hand:

#1185 fix: [NOD-357] Update openapi Nodo TS
  src/domains/nodo-app/04_apim_nodo_technical_support.tf
  src/domains/nodo-app/api/technical-support-service/v1/_openapi.json.tpl
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#1174 fix(open-api): fix checkout openapi def
  src/domains/ecommerce-app/api/ecommerce-checkout/v1/_openapi.json.tpl
Labels: env: dev, env: uat, env: prod, status: apply in progress

#1181 ci: Add secret for GPD-Core GHA pipeline
  src/domains/gps-app/04_apim_gpd_core.tf
  src/domains/gps-app/04_apim_gpd_for_pn_aca.tf
  src/domains/gps-app/99_locals.tf
  src/domains/gps-common/02_security.tf
  src/domains/gps-common/99_locals.tf
  src/domains/gps-common/README.md
  src/domains/gps-common/env/weu-dev/terraform.tfvars
  src/domains/shared-app/04_apim_statuspage.tf
Labels: env: dev, env: uat, status: applied :hand:

#1137 feat: [FdR] release/fdr-0.0.1
  README.md
  scripts/terraform.sh
  src/core/env/dev/terraform.tfvars
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
  src/domains/fdr-app/00_network.tf
  src/domains/fdr-app/05_fdr_re_fn.tf
  src/domains/fdr-app/99_locals.tf
  src/domains/fdr-app/99_variables.tf
  src/domains/fdr-app/env/weu-dev/terraform.tfvars
  src/domains/fdr-app/env/weu-prod/terraform.tfvars
  src/domains/fdr-app/env/weu-uat/terraform.tfvars
  src/domains/fdr-common/01_network.tf
  src/domains/fdr-common/03_cosmos_mongodb_fdr.tf
  src/domains/fdr-common/03_cosmos_mongodb_fdr_re.tf
  src/domains/fdr-common/03_storage_account_fdr.tf
  src/domains/fdr-common/03_storage_account_fdr_re.tf
  src/domains/fdr-common/03_storage_account_reporting_fdr.tf
  src/domains/fdr-common/99_variables.tf
  src/domains/fdr-common/env/weu-dev/terraform.tfvars
  src/domains/fdr-common/env/weu-prod/terraform.tfvars
  src/domains/fdr-common/env/weu-uat/terraform.tfvars
  src/domains/fdr-common/k8setup.sh
  src/domains/fdr-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/fdr-secret/secret/weu-prod/noedit_secret_enc.json
  src/domains/fdr-secret/secret/weu-uat/noedit_secret_enc.json
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#1116 feat: [NODO] added key apim for nodo in uat
  src/domains/nodo-secret/02_security.tf
  src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
Labels: env: uat, status: applied :hand:

#1194 [PAGOPA-1123] Fixes and activations on Authorizer
  src/domains/gps-app/api/gpd_api/debt-position-services/v1/_base_policy.xml
  src/domains/gps-app/api/payments-service/v1/rest/external/_base_policy.xml
  src/domains/shared-app/05_authorizer_functions.tf
  src/domains/shared-app/api/authorizer/authorizer-check.xml
Labels: env: dev, env: uat, status: applied :hand:

#1201 feat: Add web availability test forwarder[.env].platform.pagopa.it
  src/core/monitor.tf
Labels: status: applied :hand:

#1193 [PRDP-64] feat_ add elk secret placeholder in shared
  src/domains/shared-common/02_security.tf
  src/domains/shared-common/README.md
Labels: env: dev, env: uat, status: applied :hand:
