Repository pagopa/pagopa-infra, pull requests merged in 2023-02, with the labels that each got.

#686 feat: Add afm Storage Account PAGOPA-641
  src/domains/afm-common/02_security.tf
  src/domains/afm-common/03_storage_account_afm.tf
  src/domains/afm-common/99_variables.tf
  src/domains/afm-common/README.md
Labels: env: dev, env: uat, status: applied :hand:

#715 bug: PAGOPA-634 Added all api to nodo-auth, fix policy
  src/core/api/nodopagamenti_api/nodeForPsp/v1/auth/nodeForPsp.wsdl
  src/core/api/nodopagamenti_api/nodoPerPa/v1/auth/NodoPerPa.wsdl
  src/core/api/nodopagamenti_api/nodoPerPsp/v1/auth/nodoPerPsp.wsdl
  src/core/api_product/nodo_pagamenti_api/auth/_base_policy.xml
  src/core/apim_api_config.tf
  src/core/apim_nodo_3p_services.tf
Labels: status: applied :hand:

#714 fix: Ingress controller scaling cfg nginx
  src/aks-platform/03_ingress.tf
  src/aks-platform/99_variables.tf
  src/aks-platform/README.md
  src/aks-platform/env/weu-dev/terraform.tfvars
  src/aks-platform/env/weu-prod/terraform.tfvars
  src/aks-platform/env/weu-uat/terraform.tfvars
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#720 fix: Webbo history endpoint ( onprem and oncloud )
  src/core/README.md
  src/core/api/nodopagamenti_api/nodoServices/web-bo-history-on-prem/v1/_NodoDeiPagamenti.openapi.json.tpl
  src/core/api/nodopagamenti_api/nodoServices/web-bo-history-on-prem/v1/_base_policy.xml
  src/core/apim_nodo_3p_services.tf
Labels: status: applied :hand:

#725 feat: Add jobs to cluster role
  src/aks-platform/04_rbac.tf
Labels: status: applied :hand:

#724 [CHK-993] fix: openapi definition for checkout codegen
  src/domains/ecommerce-app/api/ecommerce-checkout/v1/_openapi.json.tpl
Labels: env: dev, env: uat, status: applied

#719 feat: API-CFG swagger x cache
  src/core/api/apiconfig_api/v1/_openapi.json.tpl
  src/core/apim_api_config.tf
Labels: status: applied :hand:

#726 Status Page for pagoPA-Core
  .devops/shared-deploy-pipelines.yml
  src/domains/shared-app/04_apim_influxdb.tf
  src/domains/shared-app/04_apim_statuspage.tf
  src/domains/shared-app/README.md
  src/domains/shared-app/api/status-page-service/v1/_base_policy.xml
  src/domains/shared-app/api/status-page-service/v1/_openapi.json.tpl
  src/domains/shared-app/api_product/_statuspage_policy.xml
Labels: status: ready to apply

#741 [CHK-1126] feat: ecommerce transactions-service openapi
  src/domains/ecommerce-app/api/ecommerce-checkout/v1/_openapi.json.tpl
  src/domains/ecommerce-app/api/ecommerce-transactions-service/v1/_openapi.json.tpl
Labels: env: dev, env: uat, status: applied

#746 [CHK-1081] Add mock for nodeForPsp API
  src/domains/ecommerce-app/04_apim_ecommerce_mock.tf
  src/domains/ecommerce-app/README.md
  src/domains/ecommerce-app/api/ecommerce-mock/nodeForPsp/v1/_base_policy.xml.tpl
  src/domains/ecommerce-app/api/ecommerce-mock/nodeForPsp/v1/nodeForPsp.wsdl
Labels: env: uat, on hold

#731 feat: Adding gpd subscription key PAGOPA-705
  src/core/README.md
  src/core/appgateway.tf
  src/core/gpd.tf
  src/core/security.tf
Labels: env: dev, env: uat, status: applied :hand:

#747 feat: add confidential data encryption key secret
  src/domains/ecommerce-common/02_security.tf
  src/domains/ecommerce-common/README.md
  src/elk-monitoring/README.md
Labels: env: dev, env: uat, status: apply in progress
