Repository pagopa/pagopa-infra, pull requests merged in 2023-05, with the labels that each got.

#905 [PAGOPA-859] Multi-entity subscription key authorizer
  src/core/api/gpd_api/debt-position-services/v1/_base_policy.xml
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
  src/domains/gps-app/.terraform.lock.hcl
  src/domains/gps-app/04_apim_external_payments.tf
  src/domains/gps-app/api/gpd-reporting-orgs-enrollment-service/v1/_base_policy.xml
  src/domains/gps-app/api/payments-service/v1/rest/external/_base_policy.xml
  src/domains/gps-app/api/reporting-analysis/v1/_base_policy.xml
  src/domains/gps-app/api/spontaneous-payments-service/v1/_base_policy.xml
  src/domains/shared-app/.terraform.lock.hcl
  src/domains/shared-app/02_keyvault.tf
  src/domains/shared-app/04_apim_authorizer.tf
  src/domains/shared-app/05_authorizer_functions.tf
  src/domains/shared-app/99_locals.tf
  src/domains/shared-app/README.md
  src/domains/shared-app/api/authorizer/authorizer-check.xml
  src/domains/shared-app/api/authorizer/v1/_base_policy.xml
  src/domains/shared-common/02_security.tf
  src/domains/shared-common/03_cosmosdb_authorizer.tf
  src/domains/shared-common/03_storage_account.tf
  src/domains/shared-common/98_agent.tf
  src/domains/shared-common/99_variables.tf
  src/domains/shared-common/README.md
  src/domains/shared-common/env/weu-dev/terraform.tfvars
  src/domains/shared-common/env/weu-uat/terraform.tfvars
Labels: env: dev, env: uat, status: applied :hand:

#897 feat: Fdr pagoPA service apim mng
  src/core/README.md
  src/core/api/nodopagamenti_api/nodoPerPa/v1/fdr_pagopa.xml.tpl
  src/core/api/nodopagamenti_api/nodoPerPsp/v1/fdr_nodoinvia_flussorendicontazione_flow.xml
  src/core/apim_nodo_services.tf
  src/core/env/dev/terraform.tfvars
  src/core/variables.tf
  src/domains/fdr-app/04_apim_fdr.tf
  src/domains/fdr-app/04_apim_fdr_nodo_legacy_services.tf
  src/domains/fdr-app/05_aks_middleware_tools.tf
  src/domains/fdr-app/99_locals.tf
  src/domains/fdr-app/README.md
  src/domains/fdr-app/api/nodoPerPa/v1/NodoPerPa.wsdl
  src/domains/fdr-app/api/nodoPerPa/v1/_base_policy.xml.tpl
  src/domains/fdr-app/api_product/nodoPerPa/_base_policy.xml
Labels: env: dev, status: applied :hand:

#877 feat: [NOD-208] Added Negative Biz-Evt
  src/core/env/dev/terraform.tfvars
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
  src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
Labels: status: applied :hand:

#914 [CHK-1371] fix: update external pgs api policy
  src/core/api/payment_transactions_gateway_api/external/v1/_base_policy.xml.tpl
  src/core/api/payment_transactions_gateway_api/external/v1/_openapi.json.tpl
  src/core/apim_payment_transactions_gateway.tf
  src/core/env/uat/terraform.tfvars
  src/elk-monitoring/05_elastic_stack.tf
  src/elk-monitoring/README.md
Labels: on hold

#913 [CHK-1212] feat: remove unused resources (ecommerce)
  src/domains/ecommerce-common/03_storage.tf
  src/domains/ecommerce-common/README.md
Labels: on hold

#923 [PAGOPA-925] fix: resolved bug on APIM-Redis connectivity
  src/core/README.md
  src/core/api/gpd_api/debt-position-services/v1/_base_policy.xml
  src/core/env/uat/terraform.tfvars
  src/core/redis_cache.tf
  src/core/variables.tf
Labels: env: dev, env: uat, tested, status: applied :hand:

#927 feat: NOD-231 INFRA fdr-secrets allineare uat con dev
  src/domains/fdr-secret/secret/weu-uat/noedit_secret_enc.json
Labels: env: dev, env: uat, status: applied :hand:

#929 fix: Fdr nodo psql
  .devops/fdr-db-migration-pipelines.yml
  src/domains/fdr-common/env/weu-uat/terraform.tfvars
Labels: env: uat, status: applied :hand:

#930 feat: Enabled apim_fdr_nodo_pagopa_enable UAT
  src/core/env/uat/terraform.tfvars
  src/domains/fdr-app/05_aks_middleware_tools.tf
  src/domains/fdr-app/99_locals.tf
Labels: env: uat, status: applied :hand:

#947 feat: add ecommerce collection indexes
  src/domains/ecommerce-common/03_cosmosdb.tf
Labels: env: uat, status: apply in progress

#912 feat: Add negative biz-events resources [PAGOPA-783]
  src/core/README.md
  src/core/env/dev/terraform.tfvars
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
  src/core/messages.tf
  src/core/variables.tf
  src/domains/bizevents-common/01_events.tf
  src/domains/bizevents-common/02_security.tf
  src/domains/bizevents-common/03_cosmosdb_bizevents_datastore.tf
  src/domains/bizevents-common/03_cosmosdb_negative_bizevents_datastore.tf
  src/domains/bizevents-common/99_variables.tf
  src/domains/bizevents-common/README.md
  src/domains/bizevents-common/env/weu-dev/terraform.tfvars
  src/domains/bizevents-common/env/weu-prod/terraform.tfvars
  src/domains/bizevents-common/env/weu-uat/terraform.tfvars
Labels: status: applied :hand:

#910 feat: [PAG-2552] Added field flag_psp_cp to canali_nodo
  .devops/nodo-db-migration-pipelines.yml
  src/psql/nodo/liquibase/changelog/cfg/3.10.0/db.changelog-0-colums-to-delete.xml
  src/psql/nodo/liquibase/changelog/cfg/3.18.0/db.changelog-20230502104500_aggiunta_flag_psp_cp.xml
  src/psql/nodo/liquibase/changelog/cfg/db.changelog-master-3.10.0.xml
  src/psql/nodo/liquibase/changelog/cfg/db.changelog-master-3.18.0.xml
  src/psql/nodo/liquibase/changelog/offline/db.changelog-master-3.18.0.xml
  src/psql/nodo/liquibase/changelog/online/db.changelog-master-3.18.0.xml
  src/psql/nodo/liquibase/changelog/re/db.changelog-master-3.18.0.xml
  src/psql/nodo/liquibase/changelog/wfesp/db.changelog-master-3.18.0.xml
  src/psql/nodo/liquibase/run.sh
Labels: status: ready to apply

#966 GitHub runner
  src/domains/apiconfig-common/99_variables.tf
  src/domains/apiconfig-common/README.md
  src/domains/gps-app/.terraform.lock.hcl
  src/domains/shared-common/.terraform.lock.hcl
  src/domains/shared-common/00_github_runner.tf
  src/domains/shared-common/02_security.tf
  src/domains/shared-common/03_cosmosdb_authorizer.tf
  src/domains/shared-common/03_cosmosdb_iuvgenerator.tf
  src/domains/shared-common/03_storage_account.tf
  src/domains/shared-common/98_agent.tf
  src/domains/shared-common/99_main.tf
  src/domains/shared-common/99_variables.tf
  src/domains/shared-common/README.md
Labels: env: dev, status: ready to apply, status: applied :hand:, status: needs review

#982 fix: [NOD-261] Removed cache policy on apim
  src/domains/apiconfig-app/api/apiconfig-cache/node_fdr/_base_policy.xml
  src/domains/apiconfig-app/api/apiconfig-cache/node_fdr/_base_policy_cache_on_apim.xml
  src/domains/apiconfig-app/api/apiconfig-cache/node_fdr/generate_cache_fragment.xml
Labels: status: applied :hand:

#980 feat: Shift observability from `core` to its `observability` domain
  src/core/README.md
  src/core/env/dev/terraform.tfvars
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
  src/core/variables.tf
  src/domains/observability/.terraform.lock.hcl
  src/domains/observability/00_monitor.tf
  src/domains/observability/01_observability.tf
  src/domains/observability/99_locals.tf
  src/domains/observability/99_main.tf
  src/domains/observability/99_variables.tf
  src/domains/observability/README.md
  src/domains/observability/env/weu-dev/backend.ini
  src/domains/observability/env/weu-dev/backend.tfvars
  src/domains/observability/env/weu-dev/terraform.tfvars
  src/domains/observability/env/weu-prod/backend.ini
  src/domains/observability/env/weu-prod/backend.tfvars
  src/domains/observability/env/weu-prod/terraform.tfvars
  src/domains/observability/env/weu-uat/backend.ini
  src/domains/observability/env/weu-uat/backend.tfvars
  src/domains/observability/env/weu-uat/terraform.tfvars
  src/domains/observability/scripts/create_table_config.dexp
  src/domains/observability/scripts/create_table_fault_code.dexp
  src/domains/observability/scripts/create_table_function.dexp
  src/domains/observability/scripts/create_table_nm3_states.dexp
  src/domains/observability/scripts/create_table_re_event.dexp
  src/domains/observability/scripts/create_table_vm3_states.dexp
  src/domains/observability/scripts/ingestion_grants.dexp
  src/domains/observability/terraform.sh
Labels: status: applied :hand:

#989 afm utils props
  src/core/api_config.tf
  src/domains/selfcare-app/.terraform.lock.hcl
Labels: status: applied :hand:

#941 [PAGOPA-930] feat: added API for APIConfig Selfcare integration
  src/domains/apiconfig-app/.terraform.lock.hcl
  src/domains/apiconfig-app/04_apim_api_apiconfig-selfcare-integration.tf
  src/domains/apiconfig-app/04_apim_product_apiconfig-selfcare-integration.tf
  src/domains/apiconfig-app/99_locals.tf
  src/domains/apiconfig-app/README.md
  src/domains/apiconfig-app/api/apiconfig-selfcare-integration/v1/_base_policy.xml
  src/domains/apiconfig-app/api/apiconfig-selfcare-integration/v1/_openapi.json.tpl
  src/domains/apiconfig-app/api_product/apiconfig-selfcare-integration/_base_policy.xml
Labels: status: applied :hand:

#991 feat: PAG-2532 parked pm
  src/core/api/nodopagamenti_api/nodoPerPM/v1/_swagger.json.tpl
  src/core/apim_nodo_services.tf
  src/core/apim_nodo_services_auth.tf
  src/core/apim_nodo_services_dev.tf
  src/domains/nodo-app/api/nodopagamenti_api/nodoPerPM/v1/_swagger.json.tpl
  src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
  src/psql/nodo/liquibase/changelog/cfg/3.19.0/db.changelog-20230517153200_parked_rtps_config.xml
  src/psql/nodo/liquibase/changelog/cfg/db.changelog-master-3.19.0.xml
  src/psql/nodo/liquibase/changelog/offline/db.changelog-master-3.19.0.xml
  src/psql/nodo/liquibase/changelog/online/db.changelog-master-3.19.0.xml
  src/psql/nodo/liquibase/changelog/re/db.changelog-master-3.19.0.xml
  src/psql/nodo/liquibase/changelog/wfesp/db.changelog-master-3.19.0.xml
  src/psql/nodo/liquibase/run.sh
Labels: env: dev, env: uat, status: applied :hand:

#975 feat: [PAG-2579] Nodo product
  src/core/apim_mock_ec_psp_pm_nexi.tf
  src/core/apim_node_forwarder.tf
  src/core/apim_payment_manager.tf
  src/core/locals.tf
  src/domains/afm-app/04_apim_afm_calculator.tf
  src/domains/afm-app/99_locals.tf
  src/domains/apiconfig-app/00_data.tf
  src/domains/apiconfig-app/04_apim_api_apiconfig-cache-node-nexi.tf
  src/domains/apiconfig-app/04_apim_api_apiconfig-cache-node.tf
  src/domains/apiconfig-app/04_apim_api_apiconfig-cache-replica-node.tf
  src/domains/apiconfig-app/99_locals.tf
  src/domains/nodo-app/.terraform.lock.hcl
  src/domains/nodo-app/00_data.tf
  src/domains/nodo-app/04_apim_apiconfig.tf
  src/domains/nodo-app/04_apim_mock_ec.tf
  src/domains/nodo-app/04_apim_mock_ec_replica.tf
  src/domains/nodo-app/04_apim_mock_ec_secondary-replica.tf
  src/domains/nodo-app/04_apim_mock_ec_secondary.tf
  src/domains/nodo-app/04_apim_mock_pm.tf
  src/domains/nodo-app/04_apim_mock_psp.tf
  src/domains/nodo-app/04_apim_mock_psp_replica.tf
  src/domains/nodo-app/04_apim_mock_psp_secondary.tf
  src/domains/nodo-app/04_apim_mock_psp_secondary_replica.tf
  src/domains/nodo-app/04_apim_nodo_pg.tf
  src/domains/nodo-app/04_apim_nodo_services_ndp.tf
  src/domains/nodo-app/04_apim_product_apim_for_node.tf
  src/domains/nodo-app/04_apim_prometheus.tf
  src/domains/nodo-app/04_apim_webbo.tf
  src/domains/nodo-app/04_apim_wfesp.tf
  src/domains/nodo-app/04_apim_wfesp_replica.tf
  src/domains/nodo-app/06_aks_middleware_tools.tf
  src/domains/nodo-app/99_locals.tf
  src/domains/nodo-app/99_main.tf
  src/domains/nodo-app/README.md
  src/domains/nodo-app/env/weu-dev/terraform.tfvars
Labels: env: dev, env: uat, env: prod, status: partially applied, status: ready to apply, status: applied :hand:

#988 CHK-1556-added-jwt-policy-fees
  src/domains/ecommerce-app/04_apim_ecommerce_checkout.tf
  src/domains/ecommerce-app/README.md
  src/domains/ecommerce-app/api/ecommerce-checkout/v1/_base_policy.xml.tpl
  src/domains/ecommerce-app/api/ecommerce-checkout/v1/_openapi.json.tpl
  src/domains/ecommerce-app/api/ecommerce-checkout/v1/_validate_transactions_jwt_token.tpl
  src/domains/ecommerce-app/api/ecommerce-payment-methods-service/v1/_openapi.json.tpl
  src/domains/ecommerce-common/README.md
Labels: status: needs review
