Repository pagopa/pagopa-infra, pull requests merged in 2023-01, with the labels that each got.

#598 PAGOPA-599 subkeys generation
  src/domains/gps-common/02_security.tf
Labels: env: dev, env: uat, status: applied :hand:

#604 fix: Refact pm api event
  src/core/api/payment_manager_api/payment-events/v1/_openapi.json.tpl
Labels: status: applied :hand:

#610 feat: Add pn to ehub biz enrich
  src/core/env/dev/terraform.tfvars
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
Labels: env: dev, env: uat, status: applied :hand:

#607 [CHK-919] feat: add transaction origin header apim policy
  src/core/api/checkout/checkout_ecommerce/v1/_base_policy.xml.tpl
  src/core/apim_checkout.tf
  src/domains/ecommerce-app/api/ecommerce-transactions-service/v1/_base_policy.xml.tpl
  src/domains/gps-common/README.md
Labels: env: dev, status: applied

#587 Feat: [CART] update ecommerce transactions openapi
  src/core/api/checkout/checkout_ecommerce/v1/_openapi.json.tpl
  src/domains/ecommerce-app/api/ecommerce-transactions-service/v1/_openapi.json.tpl
Labels: env: dev, status: applied

#603 PAGOPA-599 payments subscription key split
  src/domains/gps-common/02_security.tf
  src/domains/gps-common/README.md
Labels: status: applied :hand:

#609 Update devops Agent
  src/core/README.md
  src/core/azure_devops_agent.tf
  src/domains/gps-common/00_monitor.tf
Labels: env: dev, status: ready to apply, status: applied :hand:, status: needs review

#571 feat: alert availability for pp-restapi
  src/core/README.md
  src/core/payment_manager_monitor.tf
Labels: env: prod, status: applied

#613 PAGOPA-238 URLs update for api config
  src/core/env/dev/terraform.tfvars
  src/core/variables.tf
Labels: status: applied :hand:

#611 feat: Add policy req [PAGOPA-608]
  src/core/api_product/nodo_pagamenti_api/auth/_base_policy.xml
  src/core/apim_nodo_services_auth.tf
  src/core/env/dev/terraform.tfvars
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
  src/core/variables.tf
Labels: status: applied :hand:

#617 feat: PAGOPA-209 Added kv [API CFG]
  src/core/api_config_fe.tf
Labels: status: applied :hand:

#614 fix : Align prod core phase#1
  src/core/README.md
  src/core/api_config.tf
  src/core/apim_nodo_3p_services.tf
  src/core/dns_private.tf
  src/core/env/prod/terraform.tfvars
  src/core/vpn.tf
Labels: status: applied :hand:

#627 feat: add cacerts config map
  src/domains/nodo-secret/.terraform.lock.hcl
  src/domains/nodo-secret/02_security.tf
  src/domains/nodo-secret/99_main.tf
  src/domains/nodo-secret/99_variables.tf
  src/domains/nodo-secret/env/dev/backend.tfvars
  src/domains/nodo-secret/env/dev/terraform.tfvars
  src/domains/nodo-secret/env/prod/backend.tfvars
  src/domains/nodo-secret/env/prod/terraform.tfvars
  src/domains/nodo-secret/env/uat/backend.tfvars
  src/domains/nodo-secret/env/uat/terraform.tfvars
  src/domains/nodo-secret/env/weu-dev/resources/cacerts
  src/domains/nodo-secret/env/weu-dev/terraform.tfvars
  src/domains/nodo-secret/env/weu-prod/resources/cacerts
  src/domains/nodo-secret/env/weu-uat/resources/cacerts
  src/domains/nodo-secret/env/weu-uat/terraform.tfvars
  src/domains/nodo-secret/storageaccount.tf
Labels: env: dev, status: applied :hand:

#625 updated open api selfcare
  src/domains/selfcare-app/api/pagopa-selfcare-ms-backoffice/v1/_openapi.json.tpl
Labels: env: dev, env: uat, status: applied :hand:

#631 fix : Add nodo-cron perm aks
  src/aks-platform/04_rbac.tf
  src/domains/nodo-app/03_serviceaccounts_azure_devops.tf
  src/domains/nodo-app/README.md
  src/domains/nodo-cron/03_serviceaccounts_azure_devops.tf
  src/domains/nodo-cron/README.md
Labels: env: dev, status: applied :hand:

#632 fix: Remove useless nodo kv vars
  src/domains/nodo-secret/.terraform.lock.hcl
  src/domains/nodo-secret/README.md
  src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
Labels: env: dev, status: applied :hand:

#628 fix: Ip-filter for env align core final phase
  .gitignore
  src/core/README.md
  src/core/api/nodopagamenti_api/nodeForPsp/v1/activate_nm3.xml
  src/core/api/nodopagamenti_api/nodoPerPsp/v1/fdr_nodoinvia_flussorendicontazione_flow.xml
  src/core/api_product/nodo_pagamenti_api/_base_policy.xml
  src/core/apim_donazione_ucraina.tf
  src/core/apim_nodo_3p_services.tf
  src/core/apim_nodo_3p_services_dev.tf
  src/core/apim_nodo_services.tf
  src/core/apim_nodo_services_all_in_one.tf
  src/core/apim_nodo_services_auth.tf
  src/core/apim_nodo_services_dev.tf
  src/core/env/prod/terraform.tfvars
  src/domains/nodo-app/04_apim_nodo_services_ndp.tf
Labels: status: applied :hand:

#634 fix: Verificatore
  src/core/api/nodopagamenti_api/nodeForPsp/v1/activate_nm3.xml
Labels: env: uat, env: prod, status: applied :hand:

#638 feat: Add apim monitorin nodo ndp + AKS Blueprint upgrade from v1 to v2
  src/domains/nodo-app/.terraform.lock.hcl
  src/domains/nodo-app/02_namespace.tf
  src/domains/nodo-app/04_apim_nodo_services_ndp.tf
  src/domains/nodo-app/README.md
Labels: env: dev, status: applied :hand:

#637 fix: Apim wfesp web-bo uat
  src/core/README.md
  src/core/apim_nodo_3p_services.tf
Labels: env: uat, status: applied :hand:

#513 [CHK-687] Update tkm api
  src/core/api/tkm_api/tkm-mock-circuit-api/v1/_base_policy.xml.tpl
  src/core/apim_tkm.tf
Labels: env: dev, status: applied

#629 feat: PAGOPA-44 Update Nodo-Auth WSDL to SANP 3.3.0
  src/core/api/nodopagamenti_api/nodeForIO/v1/auth/nodeForIO.wsdl
  src/core/api/nodopagamenti_api/nodeForPsp/v1/auth/nodeForPsp.wsdl
  src/core/api/nodopagamenti_api/nodoPerPa/v1/auth/NodoPerPa.wsdl
  src/core/api/nodopagamenti_api/nodoPerPsp/v1/auth/nodoPerPsp.wsdl
  src/core/api/nodopagamenti_api/nodoPerPspRichiestaAvvisi/v1/auth/nodoPerPspRichiestaAvvisi.wsdl
  src/core/apim_nodo_3p_services.tf
  src/core/env/uat/terraform.tfvars
Labels: env: uat, env: prod, status: applied :hand:

#651 feat: NOD-56-migrazione-mocks-pa-psp
  src/domains/nodo-app/04_apim_mock_ec.tf
  src/domains/nodo-app/04_apim_mock_psp.tf
  src/domains/nodo-app/04_apim_prometheus.tf
  src/domains/nodo-app/04_apim_webbo.tf
  src/domains/nodo-app/README.md
  src/domains/nodo-app/api/mock-ec-service/v1/_base_policy.xml
  src/domains/nodo-app/api/mock-ec-service/v1/_mock-ec.openapi.json.tpl
  src/domains/nodo-app/api/mock-psp-service/v1/_base_policy.xml
  src/domains/nodo-app/api/mock-psp-service/v1/_mock-psp.openapi.json.tpl
  src/domains/nodo-app/api_product/mock-ec-service/_base_policy.xml
  src/domains/nodo-app/api_product/mock-psp-service/_base_policy.xml
Labels: status: applied :hand:

#666 feat: Fix module.apim_nodo_per_pm
  src/domains/nodo-app/04_apim_nodo_services_ndp.tf
Labels: env: dev, status: applied :hand:

#667 feat: Add new firmatore pem
  src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/nodo-secret/storageaccount.tf
Labels: env: dev, status: applied :hand:

#665 feat: Add sftp nodo
  src/core/dns_private.tf
  src/domains/nodo-common/01_network.tf
  src/domains/nodo-common/07_sftp.tf
  src/domains/nodo-common/99_locals.tf
  src/domains/nodo-common/99_variables.tf
  src/domains/nodo-common/README.md
  src/domains/nodo-common/env/weu-dev/terraform.tfvars
  src/domains/nodo-common/env/weu-uat/terraform.tfvars
Labels: env: dev, status: applied :hand:

#674 feat: Align uat nodo ndp
  src/core/README.md
  src/core/dns_private.tf
  src/core/env/dev/terraform.tfvars
  src/domains/nodo-app/04_apim_nodo_pg.tf
  src/domains/nodo-common/env/weu-uat/terraform.tfvars
Labels: env: uat, status: applied :hand:

#675 fix: Align wsdl auth to SANP 3.3.0
  src/core/api/nodopagamenti_api/nodeForPsp/v1/auth/nodeForPsp.wsdl
  src/core/api/nodopagamenti_api/nodoPerPa/v1/auth/NodoPerPa.wsdl
Labels: status: applied :hand:

#644 AFM-Util Openapi
  src/domains/afm-app/04_apim_afm_marketplace.tf
  src/domains/afm-app/README.md
  src/domains/afm-app/api/marketplace-service/utils/_base_policy.xml
  src/domains/afm-app/api/marketplace-service/utils/_openapi.json.tpl
Labels: status: applied :hand:

#653 feat: added kv e vars [API-CFG]
  src/core/api_config.tf
  src/core/security.tf
Labels: env: dev, env: uat, status: ready to apply, status: applied :hand:

#673 feat: Change prometheus namespace
  src/aks-platform/05_monitoring.tf
  src/aks-platform/env/weu-uat/kube-prometheus-stack-helm/prometheus-basic-auth
  src/aks-platform/env/weu-uat/kube-prometheus-stack-helm/values.yaml
  src/aks-platform/env/weu-uat/terraform.tfvars
Labels: env: dev, env: uat, status: applied :hand:, warning

#670 create new resource apim for api apiConfig for auth
  src/domains/selfcare-app/04_apim_api_config.tf
  src/domains/selfcare-app/README.md
  src/domains/selfcare-app/api/pagopa-api-config/v1/_base_policy.xml
  src/domains/selfcare-app/api/pagopa-api-config/v1/_openapi.json.tpl
Labels: status: applied :hand:

#656 feat: NOD-63 added api cfg kv secrets
  src/domains/nodo-secret/env/weu-uat/terraform.tfvars
  src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
Labels: status: applied :hand:

#678 feat: Add pem firmatore sftp ndp uat
  src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
Labels: env: uat, status: applied :hand:

#693 feat: [NOD-6] Added secrets for api-cfg UAT
  src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
Labels: env: uat, status: ready to apply, status: applied :hand:
