Repository pagopa/pagopa-infra, pull requests merged in 2023-03, with the labels that each got.

#763 feat: editing gpd scaling thresholds
  src/core/gpd.tf
Labels: env: uat, status: applied :hand:

#745 feat: Add apim and kv secret for gpd-reporting PAGOPA-719
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
  src/domains/gps-app/04_apim_reporting_enrollment.tf
  src/domains/gps-app/README.md
  src/domains/gps-app/api/gpd-reporting-orgs-enrollment-service/v1/_base_policy.xml
  src/domains/gps-app/api/gpd-reporting-orgs-enrollment-service/v1/_openapi.json.tpl
  src/domains/gps-app/api_product/gpd-reporting-orgs-enrollment-service/_base_policy.xml
  src/domains/gps-common/02_security.tf
  src/domains/gps-common/03_storage_account.tf
  src/domains/gps-common/README.md
Labels: status: applied

#770 Chk 1193 ecommerce queues refactoring
  src/domains/ecommerce-common/03_storage.tf
  src/domains/ecommerce-common/README.md
  src/elk-monitoring/README.md
Labels: env: dev, env: uat, status: applied

#775 [PAGOPA-769] swagger ApiConfig
  src/core/api/apiconfig_api/v1/_openapi.json.tpl
Labels: status: applied :hand:

#779 feat: Nod 143 licenza lightbend
  src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
Labels: env: dev, env: uat, status: applied :hand:

#782 feat: [PAGOPA-601] Add vars to API Config
  src/core/api_config.tf
Labels: status: applied :hand:

#774 [PAGOPA-735] Added query parameter on report search
  src/core/.terraform.lock.hcl
  src/core/api/gpd_api/reporting_analysis/v1/_openapi.json.tpl
Labels: status: applied :hand:

#783 feat: [PAGOPA-765] Fix AFM Calculator mock
  src/domains/afm-app/api/calculator-service/node/v1/_base_policy.xml
Labels: env: dev, status: ready to apply, status: applied :hand:

#795 feat: Fix es config
  src/elk-monitoring/.terraform.lock.hcl
  src/elk-monitoring/01_aks.tf
  src/elk-monitoring/05_elastic_stack.tf
  src/elk-monitoring/README.md
  src/elk-monitoring/env/weu-prod/terraform.tfvars
  src/elk-monitoring/env/weu-uat/terraform.tfvars
Labels: status: applied :hand:

#799 Chk 1255 notifications api review
  src/domains/ecommerce-app/04_apim_ecommerce.tf
  src/domains/ecommerce-app/api/ecommerce-notifications-service/v1/_openapi.json.tpl
  src/domains/ecommerce-app/api/ecommerce-notifications-service/v1/_swagger.json.tpl
Labels: env: dev, env: uat, status: apply in progress

#796 feat: PAGOPA-773 added subscription-required to forwarder
  src/core/apim_node_forwarder.tf
Labels: env: prod, status: applied :hand:

#785 feat: [NOD-129] Add vars to apiconfig kv
  src/domains/apiconfig-app/.terraform.lock.hcl
  src/domains/apiconfig-app/99_main.tf
  src/domains/apiconfig-common/02_security.tf
  src/domains/apiconfig-common/README.md
Labels: status: applied :hand:

#802 feat: Fix logstash
  src/elk-monitoring/05_elastic_stack.tf
Labels: status: applied :hand:

#806 feat: Nod 157 creare infra tf fdr
  src/domains/fdr-app/.terraform.lock.hcl
  src/domains/fdr-app/00_azuread.tf
  src/domains/fdr-app/00_data.tf
  src/domains/fdr-app/00_monitor.tf
  src/domains/fdr-app/00_network.tf
  src/domains/fdr-app/01_aks.tf
  src/domains/fdr-app/02_namespace.tf
  src/domains/fdr-app/02_security.tf
  src/domains/fdr-app/03_serviceaccounts_azure_devops.tf
  src/domains/fdr-app/05_tls_checker.tf
  src/domains/fdr-app/99_locals.tf
  src/domains/fdr-app/99_main.tf
  src/domains/fdr-app/99_variables.tf
  src/domains/fdr-app/README.md
  src/domains/fdr-app/env/weu-dev/backend.ini
  src/domains/fdr-app/env/weu-dev/backend.tfvars
  src/domains/fdr-app/env/weu-dev/terraform.tfvars
  src/domains/fdr-app/env/weu-prod/backend.ini
  src/domains/fdr-app/env/weu-prod/backend.tfvars
  src/domains/fdr-app/env/weu-prod/terraform.tfvars
  src/domains/fdr-app/env/weu-uat/backend.ini
  src/domains/fdr-app/env/weu-uat/backend.tfvars
  src/domains/fdr-app/env/weu-uat/terraform.tfvars
  src/domains/fdr-app/templates/tls-cert.yaml.tpl
  src/domains/fdr-app/terraform.sh
  src/domains/fdr-common/.terraform.lock.hcl
  src/domains/fdr-common/00_azuread.tf
  src/domains/fdr-common/00_monitor.tf
  src/domains/fdr-common/01_network.tf
  src/domains/fdr-common/02_security.tf
  src/domains/fdr-common/99_locals.tf
  src/domains/fdr-common/99_main.tf
  src/domains/fdr-common/99_variables.tf
  src/domains/fdr-common/README.md
  src/domains/fdr-common/env/weu-dev/backend.ini
  src/domains/fdr-common/env/weu-dev/backend.tfvars
  src/domains/fdr-common/env/weu-dev/terraform.tfvars
  src/domains/fdr-common/env/weu-prod/backend.ini
  src/domains/fdr-common/env/weu-prod/backend.tfvars
  src/domains/fdr-common/env/weu-prod/terraform.tfvars
  src/domains/fdr-common/env/weu-uat/backend.ini
  src/domains/fdr-common/env/weu-uat/backend.tfvars
  src/domains/fdr-common/env/weu-uat/terraform.tfvars
  src/domains/fdr-common/terraform.sh
Labels: env: dev, status: applied :hand:

#790 feat: Nod 146 target columns
  src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
  src/psql/nodo/liquibase/changelog/cfg/3.14.0/db.changelog-20230314090150_target_columns.xml
  src/psql/nodo/liquibase/changelog/cfg/db.changelog-master-3.14.0.xml
  src/psql/nodo/liquibase/changelog/offline/db.changelog-master-3.14.0.xml
  src/psql/nodo/liquibase/changelog/online/db.changelog-master-3.14.0.xml
  src/psql/nodo/liquibase/changelog/re/db.changelog-master-3.14.0.xml
  src/psql/nodo/liquibase/changelog/wfesp/db.changelog-master-3.14.0.xml
  src/psql/nodo/liquibase/run.sh
Labels: status: applied :hand:

#780 feat: Add wfesp onprem prod
  src/core/api/nodopagamenti_api/nodoServices/wfesp/v1/_base_policy.xml
  src/core/apim_nodo_3p_services.tf
  src/core/env/prod/terraform.tfvars
Labels: status: applied :hand:

#811 feat: NOD-113 added nodo secret api-config-cache-subscription-key-string
  src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
Labels: env: dev, status: applied :hand:

#808 Chk 1277 align specifications
  src/domains/apiconfig-app/README.md
  src/domains/ecommerce-app/api/ecommerce-checkout/v1/_openapi.json.tpl
  src/domains/ecommerce-app/api/ecommerce-transaction-auth-requests-service/v1/_openapi.json.tpl
  src/domains/ecommerce-app/api/ecommerce-transactions-service/v1/_openapi.json.tpl
  src/domains/fdr-app/99_locals.tf
  src/domains/fdr-common/99_locals.tf
Labels: env: dev, env: uat, status: applied

#786 add stations retrieval apis to apiConfig
  src/domains/selfcare-app/api/pagopa-api-config/v1/_openapi.json.tpl
  src/domains/selfcare-common/99_variables.tf
  src/domains/selfcare-common/README.md
Labels: env: dev, status: applied

#819 Chk 1293 add notify retry queue
  src/domains/ecommerce-common/03_storage.tf
  src/domains/ecommerce-common/README.md
Labels: env: dev, env: uat, status: applied

#807 feat: Create cosmo db SELFCARE
  src/domains/selfcare-common/02_security.tf
  src/domains/selfcare-common/03_cosmosdb_bopagopa_datastore.tf
  src/domains/selfcare-common/99_variables.tf
  src/domains/selfcare-common/README.md
  src/domains/selfcare-common/env/weu-dev/terraform.tfvars
  src/domains/selfcare-common/env/weu-prod/terraform.tfvars
  src/domains/selfcare-common/env/weu-uat/terraform.tfvars
Labels: env: dev, status: applied :hand:

#829 feat: Update api doc
  src/domains/selfcare-app/api/pagopa-api-config/v1/_openapi.json.tpl
Labels: env: dev, status: applied :hand:

#828 feat: Add service in status page apim [gpd]
  src/domains/shared-app/04_apim_statuspage.tf
Labels: env: dev, env: uat, status: applied :hand:

#830 fix: ecommerce payment methods api
  src/domains/ecommerce-app/api/ecommerce-checkout/v1/_openapi.json.tpl
  src/domains/ecommerce-app/api/ecommerce-payment-methods-service/v1/_openapi.json.tpl
Labels: env: dev, env: uat, status: applied

#788 feat: [NOD-53] Policy cache generation
  .terraform-version
  src/core/api_product/nodo_pagamenti_api/decoupler/decoupler-activate-outbound.xml
  src/core/api_product/nodo_pagamenti_api/decoupler/decoupler-algorithm.xml
  src/core/env/dev/terraform.tfvars
  src/domains/apiconfig-app/.terraform.lock.hcl
  src/domains/apiconfig-app/00_data.tf
  src/domains/apiconfig-app/04_apim_api_apiconfig-cache-node.tf
  src/domains/apiconfig-app/04_apim_fragment_apiconfig_cache.tf
  src/domains/apiconfig-app/04_apim_product_apiconfig-cache.tf
  src/domains/apiconfig-app/99_locals.tf
  src/domains/apiconfig-app/99_main.tf
  src/domains/apiconfig-app/README.md
  src/domains/apiconfig-app/api/apiconfig-cache/node/_base_policy.xml
  src/domains/apiconfig-app/api/apiconfig-cache/node/_openapi_nodev1.json.tpl
  src/domains/apiconfig-app/api/apiconfig-cache/node/generate_cache_fragment.xml
  src/domains/apiconfig-app/api_product/apiconfig-cache/_base_policy.xml
  src/domains/apiconfig-app/env/weu-uat/terraform.tfvars
Labels: env: dev, env: uat, status: applied :hand:

#809 fix: API-Config TLS checker
  src/domains/apiconfig-app/05_tls_checker.tf
  src/domains/apiconfig-app/99_main.tf
  src/domains/apiconfig-app/README.md
Labels: env: dev, env: uat, status: applied :hand:

#840 feat: add mock for PDV
  src/domains/ecommerce-app/04_apim_ecommerce_mock.tf
  src/domains/ecommerce-app/README.md
  src/domains/ecommerce-app/api/ecommerce-mock/pdv/v1/_base_policy.xml.tpl
  src/domains/ecommerce-app/api/ecommerce-mock/pdv/v1/_openapi.json.tpl
Labels: env: dev, env: uat, status: applied
