Repository pagopa/pagopa-infra, pull requests merged in 2023-11, with the labels that each got.

#1446 [PAGOPA-1332] unique pa iban relationship
  src/psql/nodo/liquibase/changelog/cfg/3.23.0/db.changelog-20230705163700_update_database_object.xml
Labels: env: dev, status: applied :hand:

#1442 Chk 2003 fix pm policies
  src/domains/ecommerce-app/04_apim_ecommerce_io.tf
  src/domains/ecommerce-app/api/ecommerce-io/v1/_auth_request.xml.tpl
  src/domains/ecommerce-app/api/ecommerce-io/v1/get_transaction.xml.tpl
  src/domains/wallet-app/api/payment-wallet/v1/_wallet_fees_policy.xml.tpl
Labels: status: apply in progress

#1458 [PRDP-185] feat: introducing dev tokenizer secret
  src/domains/receipts-secrets/.terraform.lock.hcl
  src/domains/receipts-secrets/secret/weu-dev/noedit_secret_enc.json
  src/domains/receipts-secrets/secret/weu-prod/noedit_secret_enc.json
  src/domains/receipts-secrets/secret/weu-uat/noedit_secret_enc.json
Labels: env: dev

#1457 chore: Update path in GPD PN Integration API [PAGOPA-1338]
  src/domains/gps-app/04_apim_gpd_for_pn_aca.tf
  src/domains/gps-app/api/pn-integration/_openapi.json.tpl
Labels: status: applied :hand:

#1460 chore(conf): add unicredit as NPG psp
  src/domains/ecommerce-app/env/weu-dev/terraform.tfvars
Labels: status: applied :hand:

#1459 chore(api): [CHK-2089] - move post fees for io
  src/domains/ecommerce-app/04_apim_ecommerce_io.tf
  src/domains/ecommerce-app/README.md
  src/domains/ecommerce-app/api/ecommerce-io/v1/_calculate_fees_policy.xml.tpl
  src/domains/ecommerce-app/api/ecommerce-io/v1/_openapi.json.tpl
  src/domains/wallet-app/04_apim_payment_wallet.tf
  src/domains/wallet-app/README.md
  src/domains/wallet-app/api/payment-wallet/v1/_openapi.json.tpl
Labels: env: dev, env: uat, env: prod, status: apply in progress

#1467 chore: PRDP-194 pdv keys
  src/domains/receipts-secrets/secret/weu-prod/noedit_secret_enc.json
  src/domains/receipts-secrets/secret/weu-uat/noedit_secret_enc.json
Labels: status: applied :hand:

#1464 chore: Disable opsgenie action group from response-time alert [PAGOPA-1339]
  src/domains/afm-app/00_alert_afm_calculator.tf
  src/domains/gps-app/00_alert_gpd_core.tf
  src/domains/gps-app/00_alert_gpd_payments.tf
  src/domains/nodo-app/00_alert.tf
  src/domains/shared-app/00_alert_authorizer.tf
Labels: env: prod, status: applied :hand:

#1424 fix: added continuous backup and geolocation redundancy
  src/domains/shared-common/99_variables.tf
  src/domains/shared-common/README.md
  src/domains/shared-common/env/weu-prod/terraform.tfvars
  src/domains/shared-common/env/weu-uat/terraform.tfvars
Labels: status: applied :hand:

#1473 [PAGOPA-1347] rename view
  src/psql/nodo/liquibase/changelog/cfg/3.23.0/db.changelog-20230705163700_update_database_object.xml
Labels: env: dev, status: applied :hand:

#1483 feat: Added region replica for iuv generator
  src/domains/shared-common/env/weu-prod/terraform.tfvars
Labels: status: applied

#1478 [PRDP-196] feat: introducing tokenizer client error alerts
  src/domains/receipts-app/.terraform.lock.hcl
  src/domains/receipts-app/00_alert.tf
  src/domains/receipts-app/README.md
Labels: status: applied :hand:

#1486 feat: introducing APIM config for receipts datastore
  src/domains/receipts-app/04_apim_receipts.tf
  src/domains/receipts-app/README.md
  src/domains/receipts-app/api/receipt-datastore/v1/_base_policy.xml
  src/domains/receipts-app/api/receipt-datastore/v1/_openapi.json.tpl
  src/domains/receipts-app/api_product/receipt-datastore/_base_policy.xml
Labels: env: dev, env: uat, env: prod

#1488 chore: Upd cf pdf notifier
  src/domains/receipts-secrets/secret/weu-prod/noedit_secret_enc.json
  src/domains/receipts-secrets/secret/weu-uat/noedit_secret_enc.json
Labels: status: applied :hand:

#1491 chore: Linked service df vs cosmos
  src/domains/observability/04_datafactory_linkedservice.tf
  src/domains/observability/README.md
Labels: status: applied :hand:

#1498 feat: Added postgres dns registration in uat env
  src/domains/fdr-common/03_postgresql.tf
  src/domains/fdr-common/99_variables.tf
  src/domains/fdr-common/README.md
  src/domains/fdr-common/env/weu-dev/terraform.tfvars
  src/domains/fdr-common/env/weu-prod/terraform.tfvars
  src/domains/fdr-common/env/weu-uat/terraform.tfvars
  src/next-core/01_network.tf
  src/next-core/99_variables.tf
  src/next-core/README.md
  src/next-core/env/dev/terraform.tfvars
  src/next-core/env/prod/terraform.tfvars
  src/next-core/env/uat/terraform.tfvars
Labels: status: applied :hand:

#1490 chore(nodo-alert): Update fault-code alert
  src/domains/nodo-app/00_alert.tf
  src/domains/nodo-app/00_alert_faultcode.tf
  src/domains/nodo-app/00_monitor.tf
  src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
  src/domains/nodo-app/README.md
Labels: status: applied :hand:

#1501 feat: DIS-40 DIS-39
  src/domains/fdr-common/03_postgresql.tf
  src/domains/fdr-common/99_variables.tf
  src/domains/fdr-common/README.md
  src/domains/fdr-common/env/weu-prod/terraform.tfvars
  src/domains/nodo-common/env/weu-prod/terraform.tfvars
Labels: status: applied :hand:

#1395 [NOD-540] feat: added resources for Verify KO's events from Nodo
  src/core/env/dev/terraform.tfvars
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
  src/domains/nodo-app/00_alert_ndp_verifyko.tf
  src/domains/nodo-app/00_network.tf
  src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
  src/domains/nodo-app/05_fn_ndp_verifyko_to_datastore.tf
  src/domains/nodo-app/05_fn_ndp_verifyko_to_tablestorage.tf
  src/domains/nodo-app/99_variables.tf
  src/domains/nodo-app/README.md
  src/domains/nodo-app/env/weu-dev/terraform.tfvars
  src/domains/nodo-app/env/weu-prod/terraform.tfvars
  src/domains/nodo-app/env/weu-uat/terraform.tfvars
  src/domains/nodo-common/01_events.tf
  src/domains/nodo-common/01_network.tf
  src/domains/nodo-common/02_security.tf
  src/domains/nodo-common/03_cosmosdb_nodo_re.tf
  src/domains/nodo-common/03_cosmosdb_nodo_verifyko.tf
  src/domains/nodo-common/03_storage_account_nodo_re.tf
  src/domains/nodo-common/03_storage_account_nodo_verifyko.tf
  src/domains/nodo-common/99_variables.tf
  src/domains/nodo-common/README.md
  src/domains/nodo-common/env/weu-dev/terraform.tfvars
  src/domains/nodo-common/env/weu-prod/terraform.tfvars
  src/domains/nodo-common/env/weu-uat/terraform.tfvars
Labels: status: applied :hand:

#1511 Chk 2120 ecommerce closepayment mock
  src/domains/ecommerce-app/api/ecommerce-mock/nodoPerPM/v1/_base_policy.xml.tpl
Labels: env: uat, status: applied :hand:

#1512 feat: Added velero sa backup
  src/next-aks/01_velero.tf
  src/next-aks/99_variables.tf
  src/next-aks/env/weu-prod/terraform.tfvars
Labels: status: applied :hand:

#1507 fix: updated weu-dev with datastore apikey
  src/domains/receipts-secrets/secret/weu-dev/noedit_secret_enc.json
  src/domains/receipts-secrets/secret/weu-uat/noedit_secret_enc.json
Labels: env: dev

#1524 [PASELC-610] feat: enabled IBANs functionality for SelfCare BO
  src/domains/apiconfig-app/api/apiconfig_api/subkey/v1/_base_policy.xml.tpl
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#1508 feat: DIS-38 bis
  src/domains/fdr-common/env/weu-prod/terraform.tfvars
  src/domains/gps-common/.terraform.lock.hcl
  src/domains/gps-common/01_network.tf
  src/domains/gps-common/03_postgresql_gpd.tf
  src/domains/gps-common/03_postgresql_replica.tf
  src/domains/gps-common/99_locals.tf
  src/domains/gps-common/99_variables.tf
  src/domains/gps-common/env/weu-dev/terraform.tfvars
  src/domains/gps-common/env/weu-prod/terraform.tfvars
  src/domains/gps-common/env/weu-uat/terraform.tfvars
  src/domains/nodo-common/.terraform.lock.hcl
  src/domains/nodo-common/01_network.tf
  src/domains/nodo-common/03_postgresql.tf
  src/domains/nodo-common/03_postgresql_replica.tf
  src/domains/nodo-common/99_locals.tf
  src/domains/nodo-common/99_main.tf
  src/domains/nodo-common/99_variables.tf
  src/domains/nodo-common/env/weu-dev/terraform.tfvars
  src/domains/nodo-common/env/weu-prod/terraform.tfvars
  src/domains/nodo-common/env/weu-uat/terraform.tfvars
Labels: status: applied :hand:

#1354 [NOD-508] Fix auth policy
  src/core/api_product/nodo_pagamenti_api/auth/_base_policy.xml
  src/core/api_product/nodo_pagamenti_api/decoupler/base_policy.xml.tpl
Labels: env: dev, status: applied :hand:
