Repository pagopa/pagopa-infra, pull requests merged in 2023-10, with the labels that each got.

#1350 feat: Apply prod `receipts` namespace and resources
  src/domains/receipts-app/env/weu-prod/backend.ini
  src/domains/receipts-app/env/weu-prod/backend.tfvars
  src/domains/receipts-app/env/weu-prod/terraform.tfvars
  src/domains/receipts-common/env/weu-prod/backend.ini
  src/domains/receipts-common/env/weu-prod/backend.tfvars
  src/domains/receipts-common/env/weu-prod/terraform.tfvars
  src/domains/receipts-secrets/secret/weu-prod/noedit_secret_enc.json
Labels: status: applied :hand:

#1346 fix: [NOD-455] Added exception for Taxonomy Storage Account
  src/domains/shared-common/03_storage_account_taxonomy.tf
  src/domains/shared-common/99_variables.tf
  src/domains/shared-common/env/weu-prod/terraform.tfvars
  src/domains/shared-common/env/weu-uat/terraform.tfvars
Labels: env: uat, env: prod, status: applied :hand:

#1349 feat(api-v2): open-api transaction-service
  src/domains/ecommerce-app/04_apim_ecommerce.tf
  src/domains/ecommerce-app/04_apim_ecommerce_checkout.tf
  src/domains/ecommerce-app/README.md
  src/domains/ecommerce-app/api/ecommerce-checkout/v2/_base_policy.xml.tpl
  src/domains/ecommerce-app/api/ecommerce-checkout/v2/_openapi.json.tpl
  src/domains/ecommerce-app/api/ecommerce-checkout/v2/_transaction_policy.xml.tpl
  src/domains/ecommerce-app/api/ecommerce-transactions-service/v2/_base_policy.xml.tpl
  src/domains/ecommerce-app/api/ecommerce-transactions-service/v2/_openapi.json.tpl
Labels: env: uat, env: prod, status: applied

#1358 [NOD-487] Nodo Database migration - APIM and product infrastructure
  src/domains/nodo-app/04_apim_nodo_datamigration.tf
  src/domains/nodo-app/99_locals.tf
  src/domains/nodo-app/api/nodo-datamigration/v1/_base_policy.xml
  src/domains/nodo-app/api/nodo-datamigration/v1/_openapi.json.tpl
  src/domains/nodo-secret/.terraform.lock.hcl
  src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#1361 feat: Technical support group
  src/domains/shared-app/04_apim_technical_support.tf
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#1365 feat: API config secret
  src/domains/apiconfig-common/02_security.tf
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#1364 [PRDP-25] feat: Added alerts on thoughput for receipt cosmos db
  src/domains/receipts-app/00_alert.tf
  src/domains/receipts-common/00_monitor.tf
  src/domains/receipts-common/03_cosmosdb.tf
  src/domains/receipts-common/99_locals.tf
  src/domains/receipts-common/README.md
  src/domains/receipts-secrets/secret/weu-prod/noedit_secret_enc.json
Labels: status: applied :hand:

#1367 fix: Prod PDF engine
  src/domains/shared-app/env/weu-prod/terraform.tfvars
Labels: status: applied :hand:

#1372 [PRDP-158] feat: add App Service plan for java pdf-engine
  src/domains/shared-app/01_app_service_pdf_engine.tf
  src/domains/shared-app/02_keyvault.tf
  src/domains/shared-app/04_apim_pdf_engine.tf
  src/domains/shared-app/05_taxonomy_fn.tf
  src/domains/shared-app/99_locals.tf
  src/domains/shared-app/README.md
  src/domains/shared-app/api/pdf-engine/v1/_base_policy.xml
Labels: status: applied :hand:

#1378 chore: Add pdfengine status page
  src/domains/shared-app/04_apim_statuspage.tf
  src/domains/shared-app/README.md
Labels: status: applied :hand:

#1383 fix: Receipt prod secrets notifier
  src/domains/receipts-secrets/secret/weu-prod/noedit_secret_enc.json
Labels: status: applied :hand:

#1343 feat: Update policy in GPD-Core API for organization [PAGOPA-1139]
  src/domains/gps-app/README.md
  src/domains/gps-app/api/gpd_api/debt-position-services/v1/_base_policy.xml
Labels: env: dev, env: uat, status: applied

#1360 chore: Update GPD for PN API [PAGOPA-1267]
  src/domains/gps-app/04_apim_gpd_for_pn_aca.tf
  src/domains/gps-app/api/pn-integration/_base_policy.xml
  src/domains/gps-app/api/pn-integration/_openapi.json.tpl
Labels: status: applied

#1389 fix trigger for TNSPO kpi
  src/domains/observability/04_datafactory_pipeline.tf
Labels: status: applied :hand:

#1368 fix: Upd profile scaling to forwarder app service
  src/core/README.md
  src/core/node_forwarder.tf
Labels: status: applied :hand:

#1373 fix: Removed API from nodo-auth product
  src/core/apim_nodo_services_auth.tf
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#1404 fix: Upd receipt prod secret
  src/domains/receipts-secrets/secret/weu-prod/noedit_secret_enc.json
Labels: status: applied :hand:

#1408 feat: [NOD-537] Add index FdR
  src/domains/fdr-common/03_cosmos_mongodb_fdr.tf
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#1409 feat: DIS-47 Added zone replication for azdo agents
  src/core/README.md
  src/core/apim_nodo_services_auth.tf
  src/core/azure_devops_agent.tf
  src/core/env/prod/terraform.tfvars
  src/core/variables.tf
Labels: status: applied :hand:

#1410 fix: [NOD-554] Taxonomy openapi
  src/domains/shared-app/api/taxonomy/v1/_openapi.json.tpl
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#1413 [PRDP-176] feat: Added alert for receipt generator
  src/domains/receipts-app/00_alert.tf
  src/domains/receipts-app/README.md
Labels: status: applied :hand:

#1382 feat: [PAGOPA-1272] node subkey
  src/domains/gps-common/02_security.tf
Labels: status: applied :hand:

#1384 [PAGOPA-1270] update iban view: update fields on iban_validi_per_pa view
  src/psql/nodo/liquibase/changelog/cfg/3.23.0/db.changelog-20230705163700_update_database_object.xml
  src/psql/nodo/liquibase/changelog/cfg/db.changelog-master-3.23.0.xml
Labels: env: dev, status: applied :hand:

#1419 [PRDP-181] feat: add cpu scaling rules on app service pdf engine
  src/domains/shared-app/01_app_service_pdf_engine.tf
Labels: env: dev, env: uat, env: prod

#1399 feat(sops): introduce sops for managing secrets
  .devops/qi-code-review-pipelines.yml
  .devops/qi-deploy-pipelines.yml
  .github/workflows/static_analysis.yml
  src/domains/qi-common/02_security.tf
  src/domains/qi-common/README.md
  src/domains/qi-secrets/.terraform.lock.hcl
  src/domains/qi-secrets/99_locals.tf
  src/domains/qi-secrets/99_main.tf
  src/domains/qi-secrets/99_variables.tf
  src/domains/qi-secrets/README.md
  src/domains/qi-secrets/env/weu-dev/backend.ini
  src/domains/qi-secrets/env/weu-dev/backend.tfvars
  src/domains/qi-secrets/env/weu-dev/terraform.tfvars
  src/domains/qi-secrets/env/weu-prod/backend.ini
  src/domains/qi-secrets/env/weu-prod/backend.tfvars
  src/domains/qi-secrets/env/weu-prod/terraform.tfvars
  src/domains/qi-secrets/env/weu-uat/backend.ini
  src/domains/qi-secrets/env/weu-uat/backend.tfvars
  src/domains/qi-secrets/env/weu-uat/terraform.tfvars
  src/domains/qi-secrets/key_secret.tf
  src/domains/qi-secrets/secret/weu-dev/configs.json
  src/domains/qi-secrets/secret/weu-dev/noedit_secret_enc.json
  src/domains/qi-secrets/secret/weu-dev/secret.ini
  src/domains/qi-secrets/secret/weu-prod/configs.json
  src/domains/qi-secrets/secret/weu-prod/noedit_secret_enc.json
  src/domains/qi-secrets/secret/weu-prod/secret.ini
  src/domains/qi-secrets/secret/weu-uat/configs.json
  src/domains/qi-secrets/secret/weu-uat/noedit_secret_enc.json
  src/domains/qi-secrets/secret/weu-uat/secret.ini
  src/domains/qi-secrets/sops.sh
  src/domains/qi-secrets/terraform.sh
  src/domains/qi-secrets/terrasops.sh
Labels: status: applied :hand:

#1394 feat: [NOD-535] Policy FdR for FTP
  src/domains/fdr-app/04_apim_fdr_fase1.tf
  src/domains/fdr-app/99_variables.tf
  src/domains/fdr-app/api/fdr-fase1/nodoPerPsp/v1/fdr_nodoinvia_flussorendicontazione_flow.xml
  src/domains/fdr-app/env/weu-dev/terraform.tfvars
  src/domains/fdr-app/env/weu-prod/terraform.tfvars
  src/domains/fdr-app/env/weu-uat/terraform.tfvars
Labels: env: dev, status: applied :hand:

#1397 feat: NOD-532: Aggiungere Application Insights a Fase1 e stampare gli alert…
  src/domains/fdr-app/00_alert.tf
  src/domains/fdr-app/00_monitor.tf
  src/domains/fdr-app/99_locals.tf
  src/psql/nodo/liquibase/run.sh
Labels: env: dev, status: applied :hand:

#1427 feat: [NOD-558] Release/fdr 2.0.2
  src/domains/fdr-app/00_alert.tf
  src/domains/fdr-app/00_monitor.tf
  src/domains/fdr-app/04_apim_fdr_fase1.tf
  src/domains/fdr-app/04_apim_fdr_fase1_internal.tf
  src/domains/fdr-app/04_apim_fdr_fase3.tf
  src/domains/fdr-app/99_locals.tf
  src/domains/fdr-app/99_variables.tf
  src/domains/fdr-app/api/fdr-fase1/nodoPerPsp/v1/fdr_nodoinvia_flussorendicontazione_flow.xml
  src/domains/fdr-app/api/fdr-service/org/v1/_base_policy.xml.tpl
  src/domains/fdr-app/api/fdr-service/org/v1/_openapi.json.tpl
  src/domains/fdr-app/api/fdr-service/psp/v1/_base_policy.xml.tpl
  src/domains/fdr-app/api/fdr-service/psp/v1/_openapi.json.tpl
  src/domains/fdr-app/api_product/fdr-service/org/_base_policy.xml
  src/domains/fdr-app/api_product/fdr-service/psp/_base_policy.xml
  src/domains/fdr-app/env/weu-dev/terraform.tfvars
  src/domains/fdr-app/env/weu-prod/terraform.tfvars
  src/domains/fdr-app/env/weu-uat/terraform.tfvars
  src/domains/fdr-common/03_postgresql.tf
  src/domains/fdr-common/99_variables.tf
  src/domains/fdr-common/env/weu-dev/terraform.tfvars
  src/domains/fdr-common/env/weu-prod/terraform.tfvars
  src/domains/fdr-common/env/weu-uat/terraform.tfvars
  src/psql/nodo/liquibase/run.sh
Labels: env: dev, env: uat, status: applied :hand:

#1430 chore: Upd api key service AppIO receipt
  src/domains/receipts-secrets/secret/weu-prod/noedit_secret_enc.json
  src/domains/receipts-secrets/secret/weu-uat/noedit_secret_enc.json
Labels: status: applied :hand:

#1431 feat: Storage account test data
  src/domains/fdr-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/shared-common/03_storage_account_test_data.tf
  src/domains/shared-common/99_variables.tf
  src/domains/shared-common/env/weu-dev/terraform.tfvars
  src/domains/shared-common/env/weu-uat/terraform.tfvars
Labels: env: dev, env: uat

#1434 fix: [NOD-561] FdR3 OpenAPI
  src/domains/fdr-app/api/fdr-service/org/v1/_openapi.json.tpl
  src/domains/fdr-app/api/fdr-service/psp/v1/_openapi.json.tpl
Labels: env: dev, env: uat, status: applied :hand:

#1405 feat(ecommerce-for-io): add APIM mapping policy for endpoint `POST /transactions`
  src/domains/ecommerce-app/04_apim_ecommerce_io.tf
  src/domains/ecommerce-app/README.md
  src/domains/ecommerce-app/api/ecommerce-io/v1/post_transactions.xml.tpl
Labels: env: dev, status: applied

#1444 Changing secret value dev QI
  src/domains/qi-secrets/secret/weu-dev/noedit_secret_enc.json
Labels: env: dev, status: applied :hand:

#1441 CHK-2072 fix: aca openapi fields max size
  src/domains/aca-app/api/aca/v1/_openapi.json.tpl
Labels: status: partially applied

#1445 chore: Add service pdf secrets for appIO
  src/domains/receipts-secrets/secret/weu-prod/noedit_secret_enc.json
Labels: status: applied :hand:
