Repository pagopa/pagopa-infra, pull requests merged in 2023-09, with the labels that each got.

#1262 feat(ecommerce-npg): [CHK-1840] auth request npg details
  src/domains/ecommerce-app/api/ecommerce-transaction-auth-requests-service/v1/_openapi.json.tpl
Labels: env: dev, env: uat, env: prod, status: applied

#1270 feat: added Platform's Authorizer config on Status page
  src/domains/shared-app/04_apim_statuspage.tf
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#1263 feat(ecommerce-npg): [CHK-1837] NPG transaction status notification policy
  src/domains/ecommerce-app/04_apim_ecommerce_npg_notification.tf
  src/domains/ecommerce-app/README.md
  src/domains/ecommerce-app/api/npg-notification/_base_policy.xml.tpl
  src/domains/ecommerce-app/api/npg-notification/_npg_notifications_policy.xml.tpl
  src/domains/ecommerce-app/api/npg-notification/_openapi.json.tpl
Labels: env: dev, env: uat, env: prod, status: applied

#1267 feat: add biz missing elastic secret PAGOPA-1196
  src/domains/bizevents-common/02_security.tf
Labels: status: applied :hand:

#1273 fix: [NOD-376] Taxonomy to UAT and PROD
  src/domains/shared-app/00_network.tf
  src/domains/shared-app/05_taxonomy_fn.tf
  src/domains/shared-app/99_variables.tf
  src/domains/shared-app/env/weu-dev/terraform.tfvars
  src/domains/shared-app/env/weu-prod/terraform.tfvars
  src/domains/shared-app/env/weu-uat/terraform.tfvars
  src/domains/shared-common/01_network.tf
  src/domains/shared-common/99_variables.tf
  src/domains/shared-common/env/weu-dev/terraform.tfvars
  src/domains/shared-common/env/weu-prod/terraform.tfvars
  src/domains/shared-common/env/weu-uat/terraform.tfvars
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#1275 [PRDP-127] feat: Add receipt generator to status page apim
  src/domains/shared-app/04_apim_statuspage.tf
Labels: status: applied :hand:

#1019 [CHK-1594] feat(wallet-fe): add wallet-fe CDN
  src/domains/wallet-common/00_dns_public.tf
  src/domains/wallet-common/00_monitor.tf
  src/domains/wallet-common/01_network.tf
  src/domains/wallet-common/02_security.tf
  src/domains/wallet-common/05_wallet_cdn.tf
  src/domains/wallet-common/99_locals.tf
  src/domains/wallet-common/99_variables.tf
  src/domains/wallet-common/README.md
  src/domains/wallet-common/env/weu-dev/terraform.tfvars
  src/domains/wallet-common/env/weu-prod/terraform.tfvars
  src/domains/wallet-common/env/weu-uat/terraform.tfvars
  src/domains/wallet-common/terraform.sh
Labels: env: dev

#1281 HOTFIX🔥 verificatore: new url to apiconfig
  src/core/api/nodopagamenti_api/nodeForPsp/v1/activate_nm3.xml
  src/core/api/nodopagamenti_api/nodeForPsp/v2/activate_nm3.xml
  src/core/apim_nodo_services.tf
  src/core/apim_nodo_services_auth.tf
  src/domains/nodo-app/04_apim_nodo_services_ndp.tf
  src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
  src/domains/nodo-app/05_fn_ndp_re_to_tablestorage.tf
  src/domains/nodo-app/README.md
  src/domains/nodo-app/api/nodopagamenti_api/nodeForPsp/v1/activate_nm3.xml
  src/domains/nodo-app/api/nodopagamenti_api/nodeForPsp/v2/activate_nm3.xml
Labels: status: applied :hand:

#1288 feat: Add redis secret to biz
  src/domains/bizevents-common/02_security.tf
  src/domains/bizevents-common/README.md
Labels: status: applied :hand:

#1266 feat: Update gpd-payments policy [PAGOPA-1140]
  src/domains/gps-app/api/payments-service/v1/rest/_base_policy.xml
Labels: env: dev, env: uat, status: applied :hand:

#1292 [PRDP-130] feat: Add receipts storage account primary key
  src/domains/receipts-secrets/02_security.tf
  src/domains/receipts-secrets/README.md
Labels: env: dev, env: uat, status: applied :hand:

#1290 feat: Add new nodo alerts [PAGOPA-1207]
  src/domains/nodo-app/00_alert.tf
  src/domains/nodo-app/README.md
Labels: status: applied :hand:

#1296 fix: StatusPage: new Apiconfig path
  src/domains/shared-app/04_apim_statuspage.tf
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#1297 feat(nodo-app): Add response time alert for each operation [PAGOPA-1207]
  src/domains/nodo-app/00_alert.tf
Labels: status: applied :hand:

#1274 [PRDP-129] feat: Add alert on cart events
  src/domains/receipts-app/00_alert.tf
  src/domains/receipts-app/README.md
Labels: env: uat, status: applied :hand:

#1306 fix: [NOD-442] Docker registry
  src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
  src/domains/nodo-app/05_fn_ndp_re_to_tablestorage.tf
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#1302 [CHK-1891] Fix for orderId
  src/domains/ecommerce-app/api/ecommerce-checkout/v1/_openapi.json.tpl
  src/domains/ecommerce-app/api/ecommerce-payment-methods-service/v1/_openapi.json.tpl
  src/domains/ecommerce-app/api/npg-notification/_npg_notifications_policy.xml.tpl
  src/domains/ecommerce-app/api/npg-notification/_openapi.json.tpl
Labels: env: dev, status: applied

#1223 feat: adding QI namespace [PQI-27, PQI-28]
  .devops/qi-code-review-pipelines.yml
  .devops/qi-deploy-pipelines.yml
  .github/workflows/static_analysis.yml
  .utils/terraform_run_all.sh
  src/core/env/dev/terraform.tfvars
  src/core/env/uat/terraform.tfvars
  src/domains/fdr-app/README.md
  src/domains/qi-app/.terraform.lock.hcl
  src/domains/qi-app/00_azuread.tf
  src/domains/qi-app/00_monitor.tf
  src/domains/qi-app/00_network.tf
  src/domains/qi-app/01_aks.tf
  src/domains/qi-app/02_namespace.tf
  src/domains/qi-app/02_security.tf
  src/domains/qi-app/03_serviceaccounts_azure_devops.tf
  src/domains/qi-app/04_apim_qi.tf
  src/domains/qi-app/05_aks_middleware_tools.tf
  src/domains/qi-app/99_locals.tf
  src/domains/qi-app/99_main.tf
  src/domains/qi-app/99_variables.tf
  src/domains/qi-app/README.md
  src/domains/qi-app/api_product/_base_policy.xml
  src/domains/qi-app/env/weu-dev/backend.ini
  src/domains/qi-app/env/weu-dev/backend.tfvars
  src/domains/qi-app/env/weu-dev/terraform.tfvars
  src/domains/qi-app/env/weu-prod/backend.ini
  src/domains/qi-app/env/weu-prod/backend.tfvars
  src/domains/qi-app/env/weu-prod/terraform.tfvars
  src/domains/qi-app/env/weu-uat/backend.ini
  src/domains/qi-app/env/weu-uat/backend.tfvars
  src/domains/qi-app/env/weu-uat/terraform.tfvars
  src/domains/qi-app/helm/cert-mounter.yaml.tpl
  src/domains/qi-app/terraform.sh
  src/domains/qi-common/.terraform.lock.hcl
  src/domains/qi-common/00_azuread.tf
  src/domains/qi-common/00_monitor.tf
  src/domains/qi-common/01_events.tf
  src/domains/qi-common/01_network.tf
  src/domains/qi-common/02_security.tf
  src/domains/qi-common/03_storage_account_fn.tf
  src/domains/qi-common/99_locals.tf
  src/domains/qi-common/99_main.tf
  src/domains/qi-common/99_variables.tf
  src/domains/qi-common/README.md
  src/domains/qi-common/env/weu-dev/backend.ini
  src/domains/qi-common/env/weu-dev/backend.tfvars
  src/domains/qi-common/env/weu-dev/terraform.tfvars
  src/domains/qi-common/env/weu-prod/backend.ini
  src/domains/qi-common/env/weu-prod/backend.tfvars
  src/domains/qi-common/env/weu-prod/terraform.tfvars
  src/domains/qi-common/env/weu-uat/backend.ini
  src/domains/qi-common/env/weu-uat/backend.tfvars
  src/domains/qi-common/env/weu-uat/terraform.tfvars
  src/domains/qi-common/terraform.sh
Labels: env: dev, env: uat, status: applied :hand:

#1308 feat: Update nodo alerts [PAGOPA-1207]
  src/domains/nodo-app/00_alert.tf
Labels: status: applied :hand:

#1305 feat: Update docker config for GPD reporting batch function app [PAGOPA-1176]
  src/domains/gps-app/05_gpd_reporting_functions.tf
  src/domains/gps-app/env/weu-dev/terraform.tfvars
  src/domains/gps-app/env/weu-prod/terraform.tfvars
  src/domains/gps-app/env/weu-uat/terraform.tfvars
Labels: env: dev, env: uat, status: applied :hand:

#1314 [NOD-472] fix: updated container registry ref
  src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
  src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#1313 feat: [NOD-464] Deploy FdR UAT
  src/core/apim_nodo_services.tf
  src/core/apim_nodo_services_auth.tf
  src/domains/fdr-app/00_data.tf
  src/domains/fdr-app/04_apim_fdr_fase1.tf
  src/domains/fdr-app/04_apim_fdr_fase1_auth.tf
  src/domains/fdr-app/04_apim_fdr_fase1_internal.tf
  src/domains/fdr-app/04_apim_fdr_fase3.tf
  src/domains/fdr-app/04_apim_fdr_nodo_legacy_services.tf
  src/domains/fdr-app/05_aks_middleware_tools.tf
  src/domains/fdr-app/05_fdr_json_to_xml_fn.tf
  src/domains/fdr-app/05_fdr_re_fn.tf
  src/domains/fdr-app/05_fdr_xml_to_json_fn.tf
  src/domains/fdr-app/99_locals.tf
  src/domains/fdr-app/api/fdr-fase1-internal/v1/_base_policy.xml.tpl
  src/domains/fdr-app/api/fdr-fase1-internal/v1/_openapi.json.tpl
  src/domains/fdr-app/api/fdr-fase1/nodoPerPa/v1/fdr_pagopa.xml.tpl
  src/domains/fdr-app/api/fdr-fase1/nodoPerPsp/v1/fdr_nodoinvia_flussorendicontazione_flow.xml
  src/domains/fdr-app/api/fdr-service-internal/v1/_openapi.json.tpl
  src/domains/fdr-app/env/weu-dev/terraform.tfvars
  src/domains/fdr-app/env/weu-prod/terraform.tfvars
  src/domains/fdr-secret/secret/weu-prod/noedit_secret_enc.json
  src/domains/fdr-secret/secret/weu-uat/noedit_secret_enc.json
Labels: env: uat, env: prod, status: applied :hand:

#1319 [NOD-473] fix: updated container registry ref
  src/domains/nodo-app/.terraform.lock.hcl
  src/domains/nodo-app/05_fn_ndp_re_to_tablestorage.tf
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#1326 [NOD-474] fix docker details for FdR
  src/domains/fdr-app/05_fdr_json_to_xml_fn.tf
  src/domains/fdr-app/05_fdr_re_fn.tf
  src/domains/fdr-app/05_fdr_xml_to_json_fn.tf
Labels: env: dev, env: uat, status: applied :hand:

#1004 fix: Fixed parkedList API v1
  src/core/api/nodopagamenti_api/nodoPerPM/v1/_add_v1_policy.xml.tpl
  src/core/apim_nodo_services.tf
  src/core/apim_nodo_services_auth.tf
  src/core/apim_nodo_services_dev.tf
  src/domains/nodo-app/04_apim_nodo_services_ndp.tf
  src/domains/nodo-app/04_apim_nodo_services_ndp_replica.tf
  src/domains/nodo-app/api/nodopagamenti_api/nodoPerPM/v1/_add_v1_policy.xml.tpl
  src/domains/nodo-app/api/nodopagamenti_api/nodoPerPM/v1/_closepayment_policy_dev.xml.tpl
  src/domains/nodo-app/api/nodopagamenti_api_replica/nodoPerPM/v1/_add_v1_policy.xml.tpl
  src/domains/nodo-app/api/nodopagamenti_api_replica/nodoPerPM/v1/_closepayment_policy_dev.xml.tpl
  src/domains/nodo-app/api/nodopagamenti_api_replica/nodoPerPM/v1/_swagger.json.tpl
Labels: env: dev, env: uat, env: prod, status: ready to apply, status: applied :hand:

#1316 feat: [NOD-450] release/nodo-3.22
  src/core/api/nodopagamenti_api/nodoPerPM/v1/_add_v1_policy.xml.tpl
  src/core/api/nodopagamenti_api/nodoPerPM/v1/_swagger.json.tpl
  src/core/apim_nodo_services.tf
  src/core/apim_nodo_services_auth.tf
  src/core/apim_nodo_services_dev.tf
  src/core/apim_payment_manager.tf
  src/core/env/dev/terraform.tfvars
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
  src/domains/gps-app/04_apim_gpd_payments.tf
  src/domains/gps-app/99_locals.tf
  src/domains/mock-app/04_apim_mock_ec.tf
  src/domains/mock-app/04_apim_mock_ec_psp_pm_nexi.tf
  src/domains/mock-app/99_locals.tf
  src/domains/nodo-app/04_apim_mock_ec.tf
  src/domains/nodo-app/04_apim_mock_ec_replica.tf
  src/domains/nodo-app/04_apim_mock_ec_secondary-replica.tf
  src/domains/nodo-app/04_apim_mock_ec_secondary.tf
  src/domains/nodo-app/04_apim_mock_psp.tf
  src/domains/nodo-app/04_apim_mock_psp_replica.tf
  src/domains/nodo-app/04_apim_mock_psp_secondary.tf
  src/domains/nodo-app/04_apim_mock_psp_secondary_replica.tf
  src/domains/nodo-app/04_apim_nodo_services_ndp.tf
  src/domains/nodo-app/04_apim_nodo_services_ndp_replica.tf
  src/domains/nodo-app/api/nodopagamenti_api/nodoPerPM/v1/_add_v1_policy.xml.tpl
  src/domains/nodo-app/api/nodopagamenti_api/nodoPerPM/v1/_closepayment_policy_dev.xml.tpl
  src/domains/nodo-app/api/nodopagamenti_api_replica/nodoPerPM/v1/_add_v1_policy.xml.tpl
  src/domains/nodo-app/api/nodopagamenti_api_replica/nodoPerPM/v1/_closepayment_policy_dev.xml.tpl
  src/domains/nodo-app/api/nodopagamenti_api_replica/nodoPerPM/v1/_swagger.json.tpl
  src/domains/nodo-secret/02_security.tf
  src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
Labels: env: prod, status: applied :hand:

#1329 fix: [NOD-463] secret nodo
  src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#1330 fix: Fix release Nodo 3.2.2 checkout_nodo_ws
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
  src/domains/checkout-app/04_apim_checkout.tf
Labels: env: uat, env: prod, status: applied :hand:

#1307 fix: Remove azurerm_api_management_api_version_set
  src/domains/qi-app/04_apim_qi.tf
  src/domains/qi-app/README.md
Labels: env: dev, env: uat, status: applied

#1333 [PRDP-142] Introducing app service for pdf-engine in shared
  src/domains/shared-app/.terraform.lock.hcl
  src/domains/shared-app/00_network.tf
  src/domains/shared-app/01_app_service_pdf_engine.tf
  src/domains/shared-app/04_apim_pdf_engine.tf
  src/domains/shared-app/99_locals.tf
  src/domains/shared-app/99_main.tf
  src/domains/shared-app/99_variables.tf
  src/domains/shared-app/README.md
  src/domains/shared-app/api/pdf-engine-node/v1/_base_policy.xml
  src/domains/shared-app/api/pdf-engine-node/v1/_openapi.json.tpl
  src/domains/shared-app/env/weu-dev/terraform.tfvars
  src/domains/shared-app/env/weu-uat/terraform.tfvars
Labels: env: dev, env: uat, status: applied :hand:

#1301 feat: Add dns a-record `forwarder` to natgw ips for `[env].platform.pagopa.it`
  src/core/README.md
  src/core/dns_private.tf
Labels: status: applied :hand:

#1336 feat: updated shared security to include pdf-engine-node-subkey secre…
  src/domains/shared-common/02_security.tf
  src/domains/shared-common/README.md
Labels: env: dev, env: uat

#1338 feat: [NOD-461] Enable FdR Fase1 DEV
  src/domains/fdr-app/04_apim_fdr_legacy_nodo_nexi.tf
  src/domains/fdr-app/env/weu-dev/terraform.tfvars
  src/domains/fdr-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/fdr-secret/secret/weu-prod/noedit_secret_enc.json
  src/domains/fdr-secret/secret/weu-uat/noedit_secret_enc.json
Labels: env: dev, env: uat, status: applied :hand:

#1339 feat: [NOD-471] Add index to Cosmos of FdR RE
  src/domains/fdr-common/03_cosmos_mongodb_fdr_re.tf
Labels: env: dev, env: uat, status: applied :hand:

#1337 feat: SMO DF pipe KPI_TPNP
  src/domains/observability/04_datafactory_dataflow_NOT_USED.tf
  src/domains/observability/04_datafactory_dataset.tf
  src/domains/observability/04_datafactory_linkedservice.tf
  src/domains/observability/04_datafactory_pipeline.tf
  src/domains/observability/04_datafactory_trigger_NOT_USED.tf
  src/domains/observability/README.md
  src/domains/observability/datafactory/datasets/KPI_TPNP.json
  src/domains/observability/datafactory/datasets/ReEvent.json
  src/domains/observability/datafactory/datasets/type_properties/KPI_TPNP.json
  src/domains/observability/datafactory/datasets/type_properties/ReEvent.json
  src/domains/observability/datafactory/pipelines/KPI_TPNP.json
Labels: env: dev, env: uat, status: applied :hand:

#1312 [CHK-1908] Payment gateway npg
  src/domains/ecommerce-app/04_apim_ecommerce_checkout.tf
  src/domains/ecommerce-app/99_variables.tf
  src/domains/ecommerce-app/README.md
  src/domains/ecommerce-app/api/ecommerce-checkout/v1/_auth_request.xml.tpl
  src/domains/ecommerce-app/api/ecommerce-checkout/v1/_openapi.json.tpl
  src/domains/ecommerce-app/api/ecommerce-transactions-service/v1/_openapi.json.tpl
  src/domains/ecommerce-app/env/weu-dev/terraform.tfvars
  src/domains/ecommerce-app/env/weu-prod/terraform.tfvars
  src/domains/ecommerce-app/env/weu-uat/terraform.tfvars
Labels: status: applied

#1341 fix: Fix nodo monitoring
  src/core/apim_nodo_monitoring_services.tf
  src/core/apim_nodo_services.tf
  src/core/env/uat/terraform.tfvars
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#1309 fix: Opt field `paymentNote` and `dueDate` verificatore
  src/core/README.md
  src/core/api/nodopagamenti_api/nodeForPsp/v1/activate_nm3.xml
  src/core/api/nodopagamenti_api/nodeForPsp/v2/activate_nm3.xml
  src/core/api_logs.tf
  src/domains/nodo-app/00_alert_faultcode.tf
  src/domains/nodo-app/README.md
  src/domains/nodo-app/api/nodopagamenti_api/nodeForPsp/v1/activate_nm3.xml
  src/domains/nodo-app/api/nodopagamenti_api/nodeForPsp/v2/activate_nm3.xml
  src/domains/nodo-app/api/nodopagamenti_api_replica/nodeForPsp/v1/activate_nm3.xml
Labels: status: applied :hand:

#1345 fix: Nodo monitoring dev Nexi
  src/core/apim_nodo_services_dev.tf
Labels: env: dev, status: applied :hand:
