Repository pagopa/pagopa-infra, pull requests merged in 2024-04, with the labels that each got.

#1880 fix: NPG wallet cards policy
  src/domains/wallet-app/api/npg-notifications/v1/_base_policy.xml.tpl
Labels: env: dev, env: uat, status: applied :hand:

#1890 feat: Postgres private dns dev
  src/domains/fdr-common/env/weu-dev/terraform.tfvars
  src/domains/gps-common/env/weu-dev/terraform.tfvars
  src/domains/nodo-common/env/weu-dev/terraform.tfvars
  src/next-core/01_network_dns_private.tf
  src/next-core/99_variables.tf
  src/next-core/env/dev/terraform.tfvars
  src/next-core/env/prod/terraform.tfvars
  src/next-core/env/uat/terraform.tfvars
Labels: status: applied :hand:

#1915 feat: Addedd redis hostname secrets
  src/domains/apiconfig-common/02_security.tf
  src/domains/bizevents-common/02_security.tf
  src/domains/nodo-common/02_security.tf
  src/domains/shared-common/02_security.tf
Labels: status: applied :hand:

#1921 chore: Add gps apm secret
  src/domains/gps-common/.terraform.lock.hcl
  src/domains/gps-common/02_security.tf
  src/domains/gps-common/README.md
  src/domains/shared-app/06_pagopa_shared_toolbox.tf
Labels: status: applied :hand:

#1862 feat: [NOD-237] Alert cache
  src/domains/nodo-app/00_alert_node_cfg_sync.tf
  src/domains/nodo-app/00_data.tf
  src/domains/nodo-app/00_monitor.tf
  src/domains/nodo-app/README.md
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#1922 chore(CUP): Add new corporate [PAGOPA-1679]
  src/domains/canoneunico/env/weu-prod/terraform.tfvars
Labels: status: applied :hand:

#1926 fix: Endpoint FdR auth
  src/domains/fdr-app/00_data.tf
  src/domains/fdr-app/04_apim_fdr_fase1_auth.tf
  src/domains/fdr-app/README.md
Labels: env: dev, env: uat, status: applied :hand:

#1924 chore(GPD): federated identity and alert tuning [PAGOPA-1668]
  src/domains/gps-app/00_alert_gpd_payments.tf
  src/domains/gps-common/10_github_identity.tf
Labels: env: dev, env: uat, status: applied :hand:

#1894 feat: NOD-790 secondary connection strings for biz events
  src/domains/nodo-common/02_security.tf
  src/domains/nodo-common/README.md
  src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#1944 feat: Velero backup for each namespace
  src/next-aks/.terraform.lock.hcl
  src/next-aks/00_aks.tf
  src/next-aks/01_velero.tf
  src/next-aks/99_main.tf
  src/next-aks/99_variables.tf
  src/next-aks/README.md
Labels: status: applied :hand:

#1949 feat: update transaction gateway status
  src/elk-monitoring/pagopa/ecommerce/dashboards/ecommerceUpdateStatusDashboard.ndjson
Labels: env: uat, env: prod, status: applied :hand:

#1952 feat: npg monotoring dashboard
  src/elk-monitoring/pagopa/ecommerce/dashboards/ecommerceNpgMonitoringDashboard.ndjson
  src/elk-monitoring/pagopa/ecommerce/dashboards/ecommerceUpdateStatusDashboard.ndjson
Labels: env: uat, env: prod, status: applied :hand:

#1960 feat(npg-monitoring): add ok vs error per api pane
  src/elk-monitoring/pagopa/ecommerce/dashboards/ecommerceNpgMonitoringDashboard.ndjson
Labels: env: uat, env: prod, status: applied :hand:

#1937 [VAS-772] feat: introducing station testing feature flag
  src/domains/selfcare-common/04_app_configuration_feature.tf
Labels: env: dev, env: uat

#1964 fix(cart): align openapi specs
  .devops/checkout-deploy-pipelines.yml
  src/domains/checkout-app/api/checkout/checkout_ec/v1/_openapi.json.tpl
Labels: env: dev, env: uat, env: prod, status: apply in progress

#1970 feat: Cleanup redis configuration
  src/domains/ecommerce-common/02_security.tf
  src/domains/ecommerce-common/03_redis.tf
  src/domains/ecommerce-common/99_variables.tf
  src/domains/ecommerce-common/README.md
  src/domains/ecommerce-common/env/weu-dev/terraform.tfvars
  src/domains/ecommerce-common/env/weu-prod/terraform.tfvars
  src/domains/ecommerce-common/env/weu-uat/terraform.tfvars
Labels: status: applied

#1849 feat(GPD): Update openAPIs [PAGOPA-1588]
  src/domains/gps-app/04_apim_gpd_core.tf
  src/domains/gps-app/api/gpd-upload-service/v1/_openapi.json.tpl
  src/domains/gps-app/api/gpd_api/debt-position-services/v1/_openapi.json.tpl
  src/domains/gps-app/api/gpd_api/debt-position-services/v2/_openapi.json.tpl
  src/domains/gps-app/api/gpd_api/v1/_openapi.json.tpl
  src/domains/gps-app/api/gpd_api/v2/_openapi.json.tpl
  src/domains/gps-app/api/pn-integration/_openapi.json.tpl
Labels: status: applied

#1974 feat: NOD-863 allign openapi with idtransfer
  src/domains/fdr-app/api/fdr-service-internal/v1/_openapi.json.tpl
  src/domains/fdr-app/api/fdr-service/org/v1/_openapi.json.tpl
  src/domains/fdr-app/api/fdr-service/psp/v1/_openapi.json.tpl
Labels: env: dev, env: uat, status: applied :hand:

#1975 feat: NOD-861 fix path conversione service
  src/domains/fdr-app/04_apim_fdr_fase3.tf
  src/domains/fdr-app/05_fdr_xml_to_json_fn.tf
  src/domains/fdr-app/api/fdr-service/psp/v1/_openapi.json.tpl
Labels: env: dev, env: uat, status: applied :hand:

#1927 chore: ADF biz to biz_view
  src/domains/bizevents-common/.terraform.lock.hcl
  src/domains/bizevents-common/03_cosmosdb_bizevents_datastore.tf
  src/domains/bizevents-common/03_cosmosdb_negative_bizevents_datastore.tf
  src/domains/bizevents-common/04_datafactory_dataflow.tf
  src/domains/bizevents-common/04_datafactory_dataset.tf
  src/domains/bizevents-common/04_datafactory_linkedservice.tf
  src/domains/bizevents-common/04_datafactory_pipeline.tf
  src/domains/bizevents-common/04_datafactory_trigger_NOT_USED.tf
  src/domains/bizevents-common/99_data.tf
  src/domains/bizevents-common/99_main.tf
  src/domains/bizevents-common/99_variables.tf
  src/domains/bizevents-common/README.md
  src/domains/bizevents-common/datafactory/dataflows/writeBizEventsToBizView.dsl
  src/domains/bizevents-common/datafactory/pipelines/BIZEVENTS_TO_BIZVIEW_Pipeline.json
  src/domains/bizevents-common/env/weu-dev/terraform.tfvars
  src/domains/bizevents-common/env/weu-prod/terraform.tfvars
  src/domains/bizevents-common/env/weu-uat/terraform.tfvars
Labels: status: applied :hand:
