Repository pagopa/pagopa-infra, pull requests merged in 2024-07, with the labels that each got.

#2229 feat: [PagoPa-1799] - new filter api
  src/domains/bizevents-app/04_apim_bizevents.tf
  src/domains/bizevents-app/99_locals.tf
  src/domains/bizevents-app/README.md
  src/domains/bizevents-app/api/transaction-service/v1/_openapi-jwt.json.tpl
  src/domains/bizevents-app/api/transaction-service/v1/_openapi.json.tpl
Labels: status: applied :hand:

#2231 feat: [PAGOPA-1896] - secret for query
  src/domains/bizevents-common/02_security.tf
  src/domains/bizevents-common/03_cosmosdb_bizevents_datastore.tf
  src/domains/bizevents-common/99_locals.tf
  src/domains/bizevents-common/README.md
Labels: status: applied :hand:

#2236 feat(nodo): Enable mock-ec API [PAGOPA-1897]
  src/domains/nodo-app/04_apim_mock_ec.tf
Labels: status: applied

#2240 fix: Update policy decoupler algorithm xml [PAGOPA-1904]
  src/core/api_product/nodo_pagamenti_api/decoupler/decoupler-algorithm.xml
Labels: env: uat, status: applied :hand:, wisp

#2241 fix: Cfg biz-jwt-pdv
  src/domains/bizevents-app/env/weu-prod/terraform.tfvars
Labels: status: applied :hand:

#2123 feat: ELK remove balancer, add heap to hot
  src/elk-monitoring/05_elastic_stack.tf
  src/elk-monitoring/env/weu-dev/terraform.tfvars
  src/elk-monitoring/env/weu-prod/terraform.tfvars
  src/elk-monitoring/env/weu-uat/terraform.tfvars
Labels: env: dev, env: uat, env: prod

#2225 [PAGOPA-1888] feat(shared): Add wisp-converter info products
  src/domains/shared-app/00_network.tf
  src/domains/shared-app/04_apim_statuspage.tf
  src/domains/shared-app/99_locals.tf
Labels: env: dev, env: uat, env: prod, status: applied :hand:, wisp

#2222 fix: Printit EventHub configuration
  src/domains/printit-app/00_data.tf
  src/domains/printit-app/99_variables.tf
  src/domains/printit-app/README.md
  src/domains/printit-app/env/itn-dev/terraform.tfvars
  src/domains/printit-app/env/itn-prod/terraform.tfvars
  src/domains/printit-app/env/itn-uat/terraform.tfvars
  src/domains/printit-common/10_github_identity.tf
Labels: env: dev, env: uat, status: applied :hand:, printit

#2257 feat: Business Simulation - Storico ricevute nell'app IO
  src/domains/bizevents-common/02_security.tf
  src/domains/bizevents-common/README.md
  src/domains/bizevents-secrets/.terraform.lock.hcl
  src/domains/bizevents-secrets/99_locals.tf
  src/domains/bizevents-secrets/99_main.tf
  src/domains/bizevents-secrets/99_variables.tf
  src/domains/bizevents-secrets/README.md
  src/domains/bizevents-secrets/env/weu-dev/backend.ini
  src/domains/bizevents-secrets/env/weu-dev/backend.tfvars
  src/domains/bizevents-secrets/env/weu-dev/terraform.tfvars
  src/domains/bizevents-secrets/env/weu-prod/backend.ini
  src/domains/bizevents-secrets/env/weu-prod/backend.tfvars
  src/domains/bizevents-secrets/env/weu-prod/terraform.tfvars
  src/domains/bizevents-secrets/env/weu-uat/backend.ini
  src/domains/bizevents-secrets/env/weu-uat/backend.tfvars
  src/domains/bizevents-secrets/env/weu-uat/terraform.tfvars
  src/domains/bizevents-secrets/key_secret.tf
  src/domains/bizevents-secrets/secret/weu-dev/configs.json
  src/domains/bizevents-secrets/secret/weu-dev/noedit_secret_enc.json
  src/domains/bizevents-secrets/secret/weu-dev/secret.ini
  src/domains/bizevents-secrets/secret/weu-prod/configs.json
  src/domains/bizevents-secrets/secret/weu-prod/noedit_secret_enc.json
  src/domains/bizevents-secrets/secret/weu-prod/secret.ini
  src/domains/bizevents-secrets/secret/weu-uat/configs.json
  src/domains/bizevents-secrets/secret/weu-uat/noedit_secret_enc.json
  src/domains/bizevents-secrets/secret/weu-uat/secret.ini
  src/domains/bizevents-secrets/sops.sh
  src/domains/bizevents-secrets/terraform.sh
  src/domains/bizevents-secrets/terrasops.sh
Labels: status: applied :hand:

#2253 chore: update policy to filter ec in decoupler PAGOPA-1917
  src/core/api_product/nodo_pagamenti_api/decoupler/decoupler-algorithm.xml
  src/domains/nodo-app/04_apim_wisp_converter_03_redirect.tf
  src/domains/nodo-app/04_apim_wisp_dismantling_policies.tf
  src/domains/nodo-app/99_variables.tf
  src/domains/nodo-app/api_product/nodo_pagamenti_api/decoupler/decoupler-algorithm.xml
  src/domains/nodo-app/env/weu-dev/terraform.tfvars
  src/domains/nodo-app/env/weu-prod/terraform.tfvars
  src/domains/nodo-app/env/weu-uat/terraform.tfvars
Labels: env: dev, env: uat, status: applied :hand:

#2266 chore: Add-fed-indentity-biz + change-natgw-alert
  src/domains/bizevents-common/10_github_identity.tf
  src/next-core/08_natgateway.tf
Labels: status: applied :hand:

#2288 chore: [PAGOPA-1908] Nodo common for WISP
  src/domains/nodo-common/env/weu-prod/terraform.tfvars
Labels: env: prod, status: applied :hand:, wisp

#2289 chore: [PAGOPA-1908] nodo secret for WISP
  src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
Labels: env: dev, env: uat, env: prod, status: applied :hand:, wisp

#2287 feat(shared-common): Update IUV generator for WISP dismantling [PAGOPA-1908]
  src/domains/shared-common/01_network.tf
  src/domains/shared-common/03_cosmosdb_iuvgenerator.tf
  src/domains/shared-common/10_github_identity.tf
  src/domains/shared-common/99_locals.tf
  src/domains/shared-common/README.md
  src/domains/shared-common/env/weu-prod/terraform.tfvars
  src/domains/shared-common/env/weu-uat/terraform.tfvars
Labels: status: applied, wisp

#2290 feat(shared): add SHA hashes for policies changes
  src/domains/shared-app/04_apim_authorizer.tf
  src/domains/shared-app/04_apim_io_wallet_session.tf
  src/domains/shared-app/04_apim_iuvgenerator.tf
  src/domains/shared-app/README.md
Labels: env: dev, env: uat, status: applied :hand:

#2291 chore: [PAGOPA-1908] nodo app for WISP
  src/domains/nodo-app/00_alert_node_cfg_sync.tf
  src/domains/nodo-app/01_aks.tf
  src/domains/nodo-app/04_apim_nodo_services_ndp.tf
  src/domains/nodo-app/04_apim_receipt_for_ndp.tf
  src/domains/nodo-app/04_apim_wisp_converter_01_product.tf
  src/domains/nodo-app/04_apim_wisp_converter_04_caching.tf
  src/domains/nodo-app/04_apim_wisp_dismantling_policies.tf
  src/domains/nodo-app/99_locals.tf
  src/domains/nodo-app/99_variables.tf
  src/domains/nodo-app/README.md
  src/domains/nodo-app/api/nodopagamenti_api/nodeForPsp/v1/activate_nm3.xml
  src/domains/nodo-app/api/nodopagamenti_api/nodeForPsp/v2/activate_nm3.xml
  src/domains/nodo-app/api/nodopagamenti_api/nodoPerPM/v2/wisp-closepayment.xml
  src/domains/nodo-app/api/nodopagamenti_api/wisp/wisp-disable-payment-token-timer.xml
  src/domains/nodo-app/api/nodopagamenti_api/wisp/wisp-receipt-ko.xml
  src/domains/nodo-app/api/nodopagamenti_api/wisp/wisp-sendpaymentresult.xml
  src/domains/nodo-app/api/wisp-converter/caching/v1/_base_policy.xml
  src/domains/nodo-app/api/wisp-converter/caching/v1/openapi.json
  src/domains/nodo-app/api/wisp-converter/caching/v1/wisp-cache-for-decoupler.xml
  src/domains/nodo-app/api/wisp-converter/redirect/v1/_base_policy.xml
  src/domains/nodo-app/api/wisp-converter/redirect/v1/openapi.json
  src/domains/nodo-app/api/wisp-converter/soap/README.md
  src/domains/nodo-app/api_product/nodo_pagamenti_api/decoupler/base_policy.xml.tpl
  src/domains/nodo-app/api_product/nodo_pagamenti_api/decoupler/base_policy_test.xml.tpl
  src/domains/nodo-app/api_product/nodo_pagamenti_api/decoupler/cfg/decoupler_configurator.sh
  src/domains/nodo-app/api_product/nodo_pagamenti_api/decoupler/cfg/dev/decoupler-configuration.xml
  src/domains/nodo-app/api_product/nodo_pagamenti_api/decoupler/cfg/dev/decoupler_configuration.json
  src/domains/nodo-app/api_product/nodo_pagamenti_api/decoupler/cfg/prod/decoupler-configuration.xml
  src/domains/nodo-app/api_product/nodo_pagamenti_api/decoupler/cfg/prod/decoupler_configuration.json
  src/domains/nodo-app/api_product/nodo_pagamenti_api/decoupler/cfg/uat/decoupler-configuration.xml
  src/domains/nodo-app/api_product/nodo_pagamenti_api/decoupler/cfg/uat/decoupler_configuration.json
  src/domains/nodo-app/api_product/nodo_pagamenti_api/decoupler/decoupler-activate-outbound.xml
  src/domains/nodo-app/api_product/nodo_pagamenti_api/decoupler/decoupler-algorithm-test.xml
  src/domains/nodo-app/api_product/nodo_pagamenti_api/decoupler/decoupler-algorithm.xml
  src/domains/nodo-app/api_product/wisp-converter/_base_policy.xml
  src/domains/nodo-app/env/weu-dev/terraform.tfvars
  src/domains/nodo-app/env/weu-prod/terraform.tfvars
  src/domains/nodo-app/env/weu-uat/terraform.tfvars
Labels: env: dev, env: uat, env: prod, status: applied :hand:, wisp

#2294 fix: [PAGOPA-1908] Nodo common fix WISP cosmos
  src/domains/nodo-common/env/weu-prod/terraform.tfvars
Labels: env: prod, status: applied :hand:, wisp

#2298 chore: [PAGOPA-1908] Nodo secret iuv for WISP
  src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json
Labels: env: prod, status: applied :hand:

#1891 feat: [NOD-782] [dismissione WISP] Add APIM policy for caching keys for decoupler
  src/core/99_variables.tf
  src/core/README.md
  src/core/api/nodopagamenti_api/nodeForPsp/v1/_base_policy_api_test.xml.tpl
  src/core/api/nodopagamenti_api/nodeForPsp/v1/activate_nm3.xml
  src/core/api/nodopagamenti_api/nodeForPsp/v2/activate_nm3.xml
  src/core/api/nodopagamenti_api/nodoPerPM/v2/wisp-closepayment.xml
  src/core/api/payment_manager_api/pm-per-nodo/v2/wisp-sendpaymentresult.xml
  src/core/api_product/nodo_pagamenti_api/decoupler/base_policy.xml.tpl
  src/core/api_product/nodo_pagamenti_api/decoupler/base_policy_test.xml.tpl
  src/core/api_product/nodo_pagamenti_api/decoupler/decoupler-activate-outbound.xml
  src/core/api_product/nodo_pagamenti_api/decoupler/decoupler-algorithm-test.xml
  src/core/api_product/nodo_pagamenti_api/decoupler/decoupler-algorithm.xml
  src/core/api_product/nodo_pagamenti_api/on_error_soap_req.xml
  src/core/apim_nodo_services_01_decoupler.tf
  src/core/apim_nodo_services_09_nodo_per_pm.tf
  src/core/apim_payment_manager.tf
  src/core/env/dev/terraform.tfvars
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
  src/domains/gps-app/00_data.tf
  src/domains/gps-app/04_apim_gpd_payments.tf
  src/domains/gps-app/99_variables.tf
  src/domains/gps-app/README.md
  src/domains/gps-app/api/payments-service/v1/soap/wisp-paSendRTV2.xml
  src/domains/gps-app/env/weu-dev/terraform.tfvars
  src/domains/gps-app/env/weu-prod/terraform.tfvars
  src/domains/gps-app/env/weu-uat/terraform.tfvars
Labels: env: dev, env: uat, status: applied :hand:, wisp

#2282 feat(ecommerce-for-io): Remove injection of session token into url params in auth-request policy [CHK-3031]
  src/domains/ecommerce-app/api/ecommerce-io/v2/_auth_request.xml.tpl
Labels: env: dev, status: applied

#2299 chore: [PAGOPA-1933] verificatore and clean code
  src/core/api/nodopagamenti_api/nodeForPsp/v1/activate_nm3.xml
  src/core/api/nodopagamenti_api/nodeForPsp/v2/activate_nm3.xml
  src/core/api_product/nodo_pagamenti_api/decoupler/base_policy.xml.tpl
  src/core/api_product/nodo_pagamenti_api/decoupler/decoupler-activate-outbound.xml
  src/core/api_product/nodo_pagamenti_api/decoupler/decoupler-algorithm.xml
  src/core/api_product/nodo_pagamenti_api/on_error_soap_req.xml
  src/domains/nodo-app/api/nodopagamenti_api/nodeForPsp/v1/activate_nm3.xml
  src/domains/nodo-app/api/nodopagamenti_api/nodeForPsp/v2/activate_nm3.xml
Labels: env: dev, env: uat, status: applied :hand:

#2259 feat: Add gpd-payments-pull to statuspage and monitoring [VAS-971]
  src/domains/apiconfig-common/02_security.tf
  src/domains/selfcare-common/02_security.tf
  src/domains/shared-app/04_apim_statuspage.tf
  src/domains/shared-common/02_security.tf
  src/synthetic-monitoring/monitoring_configuration.json.tpl
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#2270 feat: Add payments pull [VAS-933]
  src/domains/gps-app/00_alert_gpd_payments_pull.tf
  src/domains/gps-app/99_variables.tf
  src/domains/gps-app/README.md
Labels: env: dev, env: uat

#2317 chore: Update WISP whitelist in uat
  src/domains/nodo-app/env/weu-uat/terraform.tfvars
Labels: env: uat, status: applied :hand:, wisp

#2322 [PAGOPA-1964] fix: resolved typos on receipt generation for `closePaymentsV2`
  src/domains/nodo-app/01_aks.tf
  src/domains/nodo-app/api/nodopagamenti_api/wisp/wisp-receipt-ko.xml
  src/domains/nodo-app/env/weu-dev/terraform.tfvars
  src/domains/nodo-app/env/weu-prod/terraform.tfvars
  src/domains/nodo-app/env/weu-uat/terraform.tfvars
Labels: status: applied :hand:, wisp

#2323 fix(printit): Product Apim Published
  src/domains/printit-app/04_apim_notice_service.tf
Labels: printit

#2312 [PAGOPA-1913] feat(nodo-app): Add WISP-dismantling alerts
  src/domains/nodo-app/00_alert_wisp_dismantling.tf
  src/domains/nodo-app/README.md
Labels: status: applied :hand:, wisp

#2328 [PAGOPA-1913] fix(nodo-app): Update WISP dismantling alerts
  src/domains/nodo-app/00_alert_wisp_dismantling.tf
Labels: status: applied :hand:

#2127 Pagopa 1745 sviluppo retrieve flow gestione dinamica broker
  src/domains/gps-app/02_security.tf
  src/domains/gps-app/05_gpd_reporting_functions.tf
  src/domains/gps-app/99_variables.tf
  src/domains/gps-app/README.md
  src/domains/gps-common/02_security.tf
  src/domains/gps-secret/.terraform.lock.hcl
  src/domains/gps-secret/99_locals.tf
  src/domains/gps-secret/99_main.tf
  src/domains/gps-secret/99_variables.tf
  src/domains/gps-secret/README.md
  src/domains/gps-secret/env/weu-dev/backend.ini
  src/domains/gps-secret/env/weu-dev/backend.tfvars
  src/domains/gps-secret/env/weu-dev/terraform.tfvars
  src/domains/gps-secret/env/weu-prod/backend.ini
  src/domains/gps-secret/env/weu-prod/backend.tfvars
  src/domains/gps-secret/env/weu-prod/terraform.tfvars
  src/domains/gps-secret/env/weu-uat/backend.ini
  src/domains/gps-secret/env/weu-uat/backend.tfvars
  src/domains/gps-secret/env/weu-uat/terraform.tfvars
  src/domains/gps-secret/key_secret.tf
  src/domains/gps-secret/secret/weu-dev/configs.json
  src/domains/gps-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/gps-secret/secret/weu-dev/secret.ini
  src/domains/gps-secret/secret/weu-prod/configs.json
  src/domains/gps-secret/secret/weu-prod/noedit_secret_enc.json
  src/domains/gps-secret/secret/weu-prod/secret.ini
  src/domains/gps-secret/secret/weu-uat/configs.json
  src/domains/gps-secret/secret/weu-uat/noedit_secret_enc.json
  src/domains/gps-secret/secret/weu-uat/secret.ini
  src/domains/gps-secret/sops.sh
  src/domains/gps-secret/terraform.sh
  src/domains/gps-secret/terrasops.sh
Labels: status: applied :hand:

#2336 [PAGOPA-1075] feat: add Comune di Albairate in WISP dismantling
  src/domains/nodo-app/env/weu-uat/terraform.tfvars
Labels: env: uat, status: applied :hand:

#2339 feat: Add params 4 perftest biz
  src/domains/bizevents-app/04_apim_bizevents.tf
  src/domains/bizevents-app/README.md
  src/domains/bizevents-common/02_security.tf
  src/domains/bizevents-common/README.md
  src/domains/bizevents-secrets/secret/weu-dev/noedit_secret_enc.json
  src/domains/bizevents-secrets/secret/weu-uat/noedit_secret_enc.json
Labels: status: applied :hand:

#2349 feat: Upd ingestion biz prod query
  src/domains/bizevents-app/api/bizevents-helpdesk/v1/_base_policy.xml
  src/domains/bizevents-app/api/transaction-service/v1/_base_policy.xml
  src/domains/bizevents-common/02_security.tf
  src/domains/bizevents-secrets/secret/weu-prod/noedit_secret_enc.json
Labels: status: applied :hand:

#2234 feat: Introducing elastic config for printit. [VAS-1046]
  src/aks-leonardo/03_monitoring.tf
  src/aks-leonardo/README.md
  src/domains/selfcare-app/02_namespace.tf
  src/elk-monitoring/05_kibana_dashboard_pagopaprintit.tf
  src/elk-monitoring/05_kibana_log_pagopaprintit.tf
  src/elk-monitoring/README.md
  src/synthetic-monitoring/.terraform.lock.hcl
Labels: printit

#2277 feat: Add payments pull kibiana log indexing [VAS-937]
  src/domains/afm-common/02_keyvault.tf
  src/domains/afm-common/README.md
  src/domains/gps-app/00_data.tf
  src/domains/gps-common/02_security.tf
  src/domains/gps-common/README.md
  src/elk-monitoring/05_kibana_log_pagopa_general.tf
  src/elk-monitoring/05_kibana_log_pagopapaymentspull.tf
  src/elk-monitoring/README.md
  src/elk-monitoring/pagopa/dashboard.ndjson
  src/elk-monitoring/pagopa/ingest-pipeline.json
Labels: env: dev, env: uat

#2348 feat: Introducing notice blob api [PPANTT-69]
  src/domains/printit-app/04_apim_notice_blob.tf
  src/domains/printit-app/99_variables.tf
  src/domains/printit-app/README.md
  src/domains/printit-app/api/notices-blob/v1/_base_policy.xml
  src/domains/printit-app/api/notices-blob/v1/_get_logo_policy.xml
  src/domains/printit-app/api/notices-blob/v1/_get_notices_policy.xml
  src/domains/printit-app/api/notices-blob/v1/_openapi.json.tpl
Labels: env: dev, env: uat

#2350 PAGOPA-1994 adding corbetta and trentino
  src/domains/nodo-app/env/weu-uat/terraform.tfvars
Labels: env: uat, status: applied :hand:

#2357 chore: Upd ingestion biz query
  src/domains/bizevents-secrets/secret/weu-prod/noedit_secret_enc.json
Labels: status: applied :hand:
