Repository pagopa/pagopa-infra, pull requests merged in 2024-10, with the labels that each got.

#2459 chore: [PAGOPA-2230] WISP receipt dead letter
  src/domains/nodo-common/03_cosmosdb_wisp_converter.tf
  src/domains/nodo-common/99_variables.tf
  src/domains/nodo-common/env/weu-dev/terraform.tfvars
  src/domains/nodo-common/env/weu-prod/terraform.tfvars
  src/domains/nodo-common/env/weu-uat/terraform.tfvars
Labels: env: dev, env: uat, env: prod, wisp

#2462 feat: Add new feature flags for backoffice's Stations
  src/domains/selfcare-common/.terraform.lock.hcl
  src/domains/selfcare-common/02_azdo.tf
  src/domains/selfcare-common/04_app_configuration_feature.tf
  src/domains/selfcare-common/README.md
Labels: status: applied :hand:

#2456 feat: Introduced payment options mock
  src/domains/paymentoptions-app/.terraform.lock.hcl
  src/domains/paymentoptions-app/04_apim_payment_options_mock.tf
  src/domains/paymentoptions-app/99_locals.tf
  src/domains/paymentoptions-app/99_variables.tf
  src/domains/paymentoptions-app/README.md
  src/domains/paymentoptions-app/api/payment-options-mock/_base_policy.xml
  src/domains/paymentoptions-app/api/payment-options-mock/_get_payment_options_policy.xml
  src/domains/paymentoptions-app/api/payment-options-mock/_openapi.json.tpl
  src/domains/paymentoptions-app/env/itn-dev/terraform.tfvars
  src/domains/paymentoptions-app/env/itn-prod/terraform.tfvars
  src/domains/paymentoptions-app/env/itn-uat/terraform.tfvars
  src/domains/paymentoptions-secrets/sops.sh
Labels: env: dev, env: uat, status: applied :hand:

#2454 feat: [CHK-3290] add user api policy into ecommerce-io
  src/domains/ecommerce-app/api/ecommerce-io/v2/_base_policy.xml.tpl
Labels: env: dev

#2448 feat: Added 2 new ips to prod net gw
  src/next-core/08_natgateway.tf
  src/next-core/99_main.tf
  src/next-core/README.md
Labels: env: prod, status: applied :hand:

#2470 fix: [PAGOPA-2263] temporarily added `/fdr-psp` under AppGW's upload domain
  src/next-core/env/uat/terraform.tfvars
Labels: env: uat, status: applied :hand:

#2453 feat: [CHK-3284] add user-stats collection
  src/domains/ecommerce-common/03_cosmosdb.tf
Labels: env: dev

#2473 add: Cfg perf test ppull
  src/domains/gps-app/02_security.tf
  src/domains/gps-app/04_apim_gpd_core.tf
  src/domains/gps-app/04_apim_payments_pull.tf
  src/domains/gps-app/README.md
Labels: status: applied :hand:

#2441 PAGOPA-2127 removing company name from input
  src/domains/aca-app/api/aca/v1/_openapi.json.tpl
Labels: status: applied :hand:

#2472 chore: [PAGOPA-2249] feat(decoupler-outbound): Add sessionId when createTimer
  src/core/api_product/nodo_pagamenti_api/decoupler/decoupler-activate-outbound.xml
  src/domains/nodo-common/env/weu-prod/terraform.tfvars
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#2487 feat: Add cfg pert test ppull for prod
  src/domains/gps-app/02_security.tf
  src/domains/gps-app/04_apim_gpd_core.tf
  src/domains/gps-app/04_apim_payments_pull.tf
  src/domains/gps-app/README.md
Labels: status: applied :hand:

#2486 feat(status page): Proxy Github
  src/domains/shared-app/04_apim_statuspage.tf
  src/domains/shared-app/api/status-page-service/v1/_healthcheck_policy.xml
  src/domains/shared-app/api/status-page-service/v1/_openapi.json.tpl
  src/domains/shared-app/api/status-page-service/v1/_proxygithub_policy.xml
Labels: env: prod, status: applied :hand:

#2490 fix: sync call to rpt timer WISP Conv PAGOPA-2292
  src/core/api/nodopagamenti_api/nodoPerPa/v1/wisp_nodoInviaRPT_nodoInviaCarrelloRPT_outbound_policy.xml
  src/domains/nodo-app/00_alert_wisp_dismantling.tf
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#2002 chore(apiconfig-common): Remove old azurerm provider from all refs
  src/domains/apiconfig-common/02_security.tf
  src/domains/apiconfig-common/README.md
Labels: status: ready to apply, warning

#2499 chore: Fix evh observability to italy name
  src/domains/observability/.terraform.lock.hcl
  src/domains/observability/03_eventhub_msg.tf
Labels: status: applied :hand:

#2500 feat: [CHK-3292] add payment wallet eventhub
  src/domains/observability/env/dev/terraform.tfvars
  src/domains/observability/env/prod/terraform.tfvars
  src/domains/observability/env/uat/terraform.tfvars
Labels: status: applied :hand:

#2509 chore(gpd): remove pull flag from swagger
  src/domains/gps-app/README.md
  src/domains/gps-app/api/gpd_api/debt-position-services/v1/_openapi.json.tpl
  src/domains/gps-common/terraform.sh
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#2492 feat: [CHK-3341] add user stats availability alert
  src/domains/ecommerce-common/00_alerts.tf
  src/domains/ecommerce-common/README.md
Labels: env: dev

#2482 fix: [PAGOPA-2274] Decoupler policies fixes
  src/core/api_product/nodo_pagamenti_api/decoupler/decoupler-algorithm.xml
  src/core/api_product/nodo_pagamenti_api/on_error_soap_req.xml
Labels: env: dev, env: uat, env: prod, status: applied :hand:, nodo

#2512 Fix lightbend key
  src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#2479 feat: [PAGOPA-2212] introduced report generation for D-WISP
  src/domains/nodo-common/01_network.tf
  src/domains/nodo-common/03_cosmosdb_wisp_converter.tf
  src/domains/nodo-common/99_variables.tf
  src/domains/nodo-common/env/weu-dev/terraform.tfvars
  src/domains/nodo-common/env/weu-prod/terraform.tfvars
  src/domains/nodo-common/env/weu-uat/terraform.tfvars
  src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
Labels: env: dev, env: uat, status: applied :hand:

#2515 feat: [PAGOPA-2301] Made NAV-to-IUV mapping on D-WISP more resilient
  src/domains/nodo-common/03_cosmosdb_wisp_converter.tf
  src/domains/nodo-common/99_variables.tf
  src/domains/nodo-common/README.md
  src/domains/nodo-common/env/weu-dev/terraform.tfvars
  src/domains/nodo-common/env/weu-prod/terraform.tfvars
  src/domains/nodo-common/env/weu-uat/terraform.tfvars
Labels: env: dev, env: uat, env: prod, status: applied :hand:, wisp
