Repository pagopa/pagopa-infra, pull requests merged in 2024-12, with the labels that each got.

#2616 feat: [PAGOPA-2425] add alert on D-WISP's redirect API availability
  src/domains/nodo-app/00_alert_wisp_dismantling.tf
  src/domains/nodo-app/README.md
Labels: status: applied :hand:

#2623 feat: Add payopt workload identity
  src/aks-leonardo/03_aks_0.tf
  src/aks-leonardo/99_variables.tf
  src/aks-leonardo/env/itn-dev/terraform.tfvars
  src/aks-leonardo/env/itn-prod/terraform.tfvars
  src/aks-leonardo/env/itn-uat/terraform.tfvars
  src/domains/payopt-app/.terraform.lock.hcl
  src/domains/payopt-app/02_namespace.tf
  src/domains/payopt-app/05_aks_middleware_tools.tf
  src/domains/payopt-app/99_main.tf
  src/domains/payopt-common/03_eventhub.tf
  src/domains/payopt-common/10_github_identity.tf
  src/domains/payopt-common/99_main.tf
  src/domains/payopt-secrets/01_keyvault.tf
  src/domains/payopt-secrets/99_main.tf
  src/domains/printit-app/.terraform.lock.hcl
Labels: env: dev, env: uat, status: applied :hand:

#2625 feat: [PPANTT-201] ebollo status page
  src/domains/shared-app/04_apim_statuspage.tf
Labels: status: applied :hand:

#2633 feat(GPD): Update rate-limit
  src/domains/gps-app/api/gpd-upload-service/v1/_base_policy.xml
Labels: env: dev, env: uat, env: prod, status: applied :hand:, gpd

#2641 feat: Moved prod gh job to correct cae region
  src/domains/afm-app/07_gh_runner.tf
  src/domains/apiconfig-app/07_gh_runner.tf
  src/domains/bizevents-app/07_gh_runner.tf
  src/domains/fdr-app/07_gh_runner.tf
  src/domains/gps-app/07_gh_runner.tf
  src/domains/nodo-app/07_gh_runner.tf
  src/domains/receipts-app/07_gh_runner.tf
  src/domains/selfcare-app/07_gh_runner.tf
  src/domains/shared-app/07_gh_runner.tf
  src/next-core/env/prod/terraform.tfvars
Labels: status: applied :hand:

#2622 feat: [PAGOPA-2395] Upgraded PostgreSQL version for FdR1
  src/domains/fdr-common/.terraform.lock.hcl
  src/domains/fdr-common/01_network.tf
  src/domains/fdr-common/03_cosmos_mongodb_fdr.tf
  src/domains/fdr-common/03_cosmos_mongodb_fdr_re.tf
  src/domains/fdr-common/03_postgresql.tf
  src/domains/fdr-common/03_postgresql_replica.tf
  src/domains/fdr-common/03_storage_account_fdr.tf
  src/domains/fdr-common/03_storage_account_fdr_history.tf
  src/domains/fdr-common/03_storage_account_fdr_re.tf
  src/domains/fdr-common/03_storage_account_reporting_fdr.tf
  src/domains/fdr-common/10_github_identity.tf
  src/domains/fdr-common/99_main.tf
  src/domains/fdr-common/99_variables.tf
  src/domains/fdr-common/README.md
  src/domains/fdr-common/env/weu-dev/terraform.tfvars
  src/domains/fdr-common/env/weu-prod/terraform.tfvars
  src/domains/fdr-common/env/weu-uat/terraform.tfvars
Labels: env: dev, env: uat, env: prod, status: applied :hand:, fdr

#2630 feat: [PPANTT-200] ebollo mbd gps service alerts
  src/domains/ebollo-app/00_alerts.tf
  src/domains/ebollo-app/05_subkey.tf
  src/domains/ebollo-app/06_keyvault.tf
  src/domains/ebollo-app/99_locals.tf
  src/domains/shared-app/04_apim_statuspage.tf
Labels: status: applied :hand:

#2572 feat: [PAGOPA-2045] set async request to FdR1 for SFTP requests
  src/core/api/nodopagamenti_api/nodoPerPsp/v1/fdr_nodoinvia_flussorendicontazione_flow.xml
  src/domains/fdr-app/00_alert_fdr_fase3.tf
  src/domains/fdr-app/00_alert_fdr_jsontoxml.tf
  src/domains/fdr-app/00_alert_fdr_xmltojson.tf
  src/domains/fdr-app/02_function.tf
  src/domains/fdr-app/04_apim_fdr_fase3.tf
  src/domains/fdr-app/04_apim_fdr_json_to_xml.tf
  src/domains/fdr-app/04_apim_fdr_legacy_nodo_nexi.tf
  src/domains/fdr-app/04_apim_fdr_xml_to_json.tf
  src/domains/fdr-app/05_fdr_json_to_xml_fn.tf
  src/domains/fdr-app/05_fdr_re_fn.tf
  src/domains/fdr-app/05_fdr_xml_to_json_fn.tf
  src/domains/fdr-app/99_variables.tf
  src/domains/fdr-app/README.md
  src/domains/fdr-app/api/fdr-fase1/nodoPerPsp/v1/fdr_nodoinvia_flussorendicontazione_flow.xml
  src/domains/fdr-app/api/fdr-legacy/nodoPerPa/v1/NodoPerPa.wsdl
  src/domains/fdr-app/api/fdr-legacy/nodoPerPa/v1/_base_policy.xml
  src/domains/fdr-app/api/nodoPerPa/v1/_base_policy.xml.tpl
  src/domains/fdr-app/api/nodoPerPsp/v1/fdr_nodoinvia_flussorendicontazione_flow.xml
  src/domains/fdr-app/env/weu-dev/terraform.tfvars
  src/domains/fdr-app/env/weu-prod/terraform.tfvars
  src/domains/fdr-app/env/weu-uat/terraform.tfvars
  src/next-core/api/nodopagamenti_api/nodoPerPsp/v1/fdr_nodoinvia_flussorendicontazione_flow.xml
Labels: env: dev, env: uat, env: prod, status: applied :hand:, fdr

#2651 Feat add elastic otel
  src/domains/ebollo-app/06_keyvault.tf
  src/domains/ebollo-secrets/secret/itn-dev/noedit_secret_enc.json
  src/domains/ebollo-secrets/secret/itn-prod/noedit_secret_enc.json
  src/domains/ebollo-secrets/secret/itn-uat/noedit_secret_enc.json
Labels: status: applied :hand:

#2653 fix(printit): remove .zip in the swagger file for printit proxy to blob
  src/domains/printit-app/api/notices-blob/v1/_openapi.json.tpl
Labels: env: dev, env: uat, env: prod, status: applied :hand:, printit

#2514 [PPANTT-168] feat: introduce ingestion infra
  src/domains/gps-app/00_data.tf
  src/domains/gps-app/05_debezium_connect.tf
  src/domains/gps-app/99_variables.tf
  src/domains/gps-app/env/weu-dev/terraform.tfvars
  src/domains/gps-app/env/weu-prod/terraform.tfvars
  src/domains/gps-app/env/weu-uat/terraform.tfvars
  src/domains/gps-app/yaml/kafka-connect.yaml
  src/domains/gps-app/yaml/postgres-connector.yaml
  src/domains/gps-common/01_network.tf
  src/domains/gps-common/02_security.tf
  src/domains/gps-common/03_cosmosdb.tf
  src/domains/gps-common/03_postgresql_gpd.tf
  src/domains/gps-common/03_postgresql_gpd_TEST_2_DELETE.tf
  src/domains/gps-common/03_postgresql_gpd_db.tf
  src/domains/gps-common/03_postgresql_gpd_single_server.tf
  src/domains/gps-common/03_postgresql_replica.tf
  src/domains/gps-common/99_locals.tf
  src/domains/gps-common/99_main.tf
  src/domains/gps-common/99_variables.tf
  src/domains/gps-common/env/weu-dev/terraform.tfvars
  src/domains/gps-common/env/weu-prod/terraform.tfvars
  src/domains/gps-common/env/weu-uat/terraform.tfvars
  src/domains/gps-common/how2_cdc_GPD.md
  src/domains/gps-secret/secret/weu-prod/noedit_secret_enc.json
  src/domains/observability/02_security.tf
  src/domains/observability/03_eventhub_msg_gdp.tf
  src/domains/observability/env/prod/terraform.tfvars
  src/domains/observability/gpd_evh_create__az.sh
  src/domains/shared-app/api/statuspage_nodopagamenti/v1/_base_policy.xml
  src/elk-monitoring/05_elastic_stack.tf
  src/psql/flyway_gpd.sh
Labels: status: applied :hand:

#2658 feat: Remove alert status-page
  src/next-core/env/prod/terraform.tfvars
Labels: status: applied :hand:

#2639 feat: [PQ-247] add nodo per payment manager api to assistenza product
  src/core/apim_nodo_services_09_nodo_per_pm.tf
Labels: status: applied :hand:

#2650 fix: [PQ-253] fix script ingestion gec
  src/domains/observability/datafactory/pipelines/PDND_CDC_GEC_CIBUNDLES.json
  src/domains/observability/datafactory/pipelines/PDND_CDC_GEC_PAYMENTTYPES.json
  src/domains/observability/datafactory/pipelines/PDND_CDC_GEC_TOUCHPOINTS.json
Labels: status: applied :hand:

#2663 feat: Added spontaneus payments downstream secrets
  src/domains/gps-app/00_data.tf
  src/domains/gps-app/02_security.tf
  src/domains/gps-app/05_subkey.tf
  src/domains/gps-app/api/spontaneous-payments-service/v1/_base_policy.xml
Labels: status: applied :hand:

#2666 chore: Gh Bot CD PAT + Lightbend Key [NODO]
  src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
Labels: env: dev, env: uat, env: prod, status: applied :hand:, nodo

#2669 chore: [PAGOPA-2498] GPS secret
  src/domains/gps-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/gps-secret/secret/weu-prod/noedit_secret_enc.json
  src/domains/gps-secret/secret/weu-uat/noedit_secret_enc.json
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#2673 feat: [PAYMCLOUD-188] Add new Opsgenie webhook token to secrets file
  src/next-core-secrets/secret/prod/noedit_secret_enc.json
Labels: env: prod, status: applied

#2672 fix: Wisp uat servicebus to standard
  src/aks-leonardo/README.md
  src/core-itn-secrets/README.md
  src/core-itn/README.md
  src/core/README.md
  src/domains/apiconfig-app/README.md
  src/domains/apiconfig-common/02_security.tf
  src/domains/apiconfig-common/README.md
  src/domains/fdr-app/README.md
  src/domains/fdr-common/README.md
  src/domains/gps-app/00_data.tf
  src/domains/gps-app/README.md
  src/domains/gps-common/03_postgresql_gpd.tf
  src/domains/gps-common/03_postgresql_gpd_db.tf
  src/domains/gps-common/README.md
  src/domains/gps-common/env/weu-prod/terraform.tfvars
  src/domains/gps-common/env/weu-uat/terraform.tfvars
  src/domains/nodo-common/06_service_bus_wisp_converter.tf
  src/domains/nodo-common/env/weu-uat/terraform.tfvars
  src/domains/observability/03_eventhub_msg_gdp.tf
  src/domains/observability/README.md
  src/domains/selfcare-app/README.md
  src/elk-monitoring/README.md
  src/grafana-monitoring/README.md
  src/packer/README.md
  src/synthetic-monitoring/README.md
  src/zabbix/README.md
Labels: released

#2677 chore: Fdr pat secret and other stuff
  src/domains/apiconfig-secret/.terraform.lock.hcl
  src/domains/apiconfig-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/apiconfig-secret/secret/weu-prod/noedit_secret_enc.json
  src/domains/apiconfig-secret/secret/weu-uat/noedit_secret_enc.json
  src/domains/fdr-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/fdr-secret/secret/weu-prod/noedit_secret_enc.json
  src/domains/fdr-secret/secret/weu-uat/noedit_secret_enc.json
  src/domains/gps-secret/secret/weu-prod/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#2680 feat: Enabled cdc gpd ingestion PROD
  src/domains/gps-common/env/weu-prod/terraform.tfvars
  src/domains/gps-secret/secret/weu-prod/noedit_secret_enc.json
  src/domains/observability/03_eventhub_msg_gdp.tf
  src/domains/observability/env/uat/terraform.tfvars
  src/domains/observability/gpd_evh_create__az.sh
Labels: status: applied :hand:

#2674 bug: [PAGOPA-2421] - advisory lock
  src/domains/gps-common/02_security.tf
  src/domains/gps-common/99_locals.tf
Labels: status: applied :hand:, gpd

#2684 chore: [PAGOPA-2505] fix private endpoint storage account WISP
  src/domains/nodo-common/03_storage_account_wisp_converter.tf
  src/domains/nodo-common/env/weu-uat/terraform.tfvars
Labels: env: dev, env: uat, env: prod, status: applied :hand:, wisp

#2682 feat: Add enabled `workload_identity`🇮🇹 + apply payopt prod + apply mock payopt dev and uat
  src/aks-leonardo/env/itn-prod/terraform.tfvars
  src/domains/payopt-app/04_apim_payment_options.tf
  src/domains/payopt-app/04_apim_payment_options_mock.tf
  src/domains/payopt-app/05_subkey.tf
  src/domains/payopt-app/06_keyvault.tf
  src/domains/payopt-app/99_variables.tf
  src/domains/payopt-app/api/payment-options-mock/_get_payment_options_dev_policy.xml
  src/domains/payopt-app/api/payment-options-mock/_get_payment_options_uat_policy.xml
  src/domains/payopt-app/env/itn-dev/terraform.tfvars
  src/domains/payopt-app/env/itn-prod/terraform.tfvars
  src/domains/payopt-app/env/itn-uat/terraform.tfvars
  src/domains/payopt-common/.terraform.lock.hcl
  src/domains/payopt-common/env/itn-dev/terraform.tfvars
  src/domains/payopt-common/env/itn-prod/terraform.tfvars
  src/domains/payopt-common/env/itn-uat/terraform.tfvars
  src/domains/payopt-secrets/env/itn-dev/terraform.tfvars
  src/domains/payopt-secrets/env/itn-prod/terraform.tfvars
  src/domains/payopt-secrets/env/itn-uat/terraform.tfvars
  src/domains/payopt-secrets/secret/itn-prod/noedit_secret_enc.json
Labels: status: applied :hand:

#2690 feat: Enabled debezium-conn gpd prod
  src/domains/gps-app/env/weu-prod/terraform.tfvars
  src/domains/observability/gpd_evh_create__az.sh
Labels: status: applied :hand:

#2687 feat: Add qi smo jira tickets
  src/domains/qi-app/04_apim_qi_smo_jira_tickets.tf
  src/domains/qi-app/api/qi-smo-jira-tickets-api/v1/_base_policy.xml.tpl
  src/domains/qi-app/api/qi-smo-jira-tickets-api/v1/_openapi.json.tpl
Labels: status: applied :hand:

#2693 feat: [PAYMCLOUD-191] Upgrade aks platform module to v8.66.1
  src/aks-platform/02_aks.tf
  src/aks-platform/README.md
Labels: env: dev, env: uat, env: prod, status: applied
