Repository pagopa/pagopa-infra, pull requests merged in 2024-09, with the labels that each got.

#2385 chore: [PAGOPA-2061] PROD release for WISP dismantling
  src/core/api/nodopagamenti_api/nodeForPsp/v1/activate_nm3.xml
  src/core/api/nodopagamenti_api/nodeForPsp/v2/activate_nm3.xml
  src/core/api_product/nodo_pagamenti_api/decoupler/base_policy.xml.tpl
  src/core/api_product/nodo_pagamenti_api/decoupler/decoupler-algorithm.xml
  src/domains/nodo-app/04_apim_wisp_dismantling_policies.tf
  src/domains/nodo-app/99_variables.tf
  src/domains/nodo-app/api/nodopagamenti_api/nodeForPsp/v1/activate_nm3.xml
  src/domains/nodo-app/api/nodopagamenti_api/nodeForPsp/v2/activate_nm3.xml
  src/domains/nodo-app/api/nodopagamenti_api/wisp/cfg/dev/batch_migration_cis.txt
  src/domains/nodo-app/api/nodopagamenti_api/wisp/cfg/dev/batch_migration_stations.txt
  src/domains/nodo-app/api/nodopagamenti_api/wisp/cfg/prod/batch_migration_cis.txt
  src/domains/nodo-app/api/nodopagamenti_api/wisp/cfg/prod/batch_migration_stations.txt
  src/domains/nodo-app/api/nodopagamenti_api/wisp/cfg/uat/batch_migration_cis.txt
  src/domains/nodo-app/api/nodopagamenti_api/wisp/cfg/uat/batch_migration_stations.txt
  src/domains/nodo-app/api/nodopagamenti_api/wisp/wisp-batch-migration.xml
  src/domains/nodo-app/env/weu-dev/terraform.tfvars
  src/domains/nodo-app/env/weu-prod/terraform.tfvars
  src/domains/nodo-app/env/weu-uat/terraform.tfvars
  src/next-core/api/nodopagamenti_api/nodeForPsp/v1/activate_nm3.xml
  src/next-core/api/nodopagamenti_api/nodeForPsp/v2/activate_nm3.xml
Labels: env: dev, env: uat, env: prod, status: applied :hand:, wisp, core

#2399 chore: [PAGOPA-2074] Regione Veneto - parte 3
  src/domains/nodo-app/api/nodopagamenti_api/wisp/cfg/prod/batch_migration_cis.txt
  src/domains/nodo-app/api/nodopagamenti_api/wisp/cfg/prod/batch_migration_stations.txt
Labels: env: prod, status: applied :hand:, wisp

#2397 feat: ECommerce hang timeout [PAGOPA-2056]
  src/domains/afm-app/README.md
  src/domains/ecommerce-app/README.md
  src/domains/nodo-app/README.md
  src/domains/nodo-app/env/weu-dev/terraform.tfvars
  src/domains/nodo-app/env/weu-uat/terraform.tfvars
  src/domains/nodo-common/02_security.tf
  src/domains/nodo-common/06_service_bus_wisp_converter.tf
  src/domains/nodo-common/README.md
  src/domains/nodo-common/env/weu-dev/terraform.tfvars
  src/domains/nodo-common/env/weu-prod/terraform.tfvars
  src/domains/nodo-common/env/weu-uat/terraform.tfvars
  src/domains/selfcare-app/README.md
  src/domains/selfcare-common/README.md
  src/grafana-monitoring/README.md
Labels: env: dev, env: uat, env: prod, status: applied :hand:, nodo

#2406 feat: Upg gpd pglfex + cosmos wisp RU
  src/domains/gps-common/env/weu-prod/terraform.tfvars
  src/domains/nodo-common/env/weu-prod/terraform.tfvars
Labels: env: prod, status: applied :hand:

#2409 feat: [PAGOPA-2107] WISP batch migration
  src/domains/nodo-app/04_apim_wisp_dismantling_policies.tf
  src/domains/nodo-app/api/nodopagamenti_api/wisp/cfg/dev/batch_migration_cis.txt
  src/domains/nodo-app/api/nodopagamenti_api/wisp/cfg/dev/batch_migration_stations.txt
  src/domains/nodo-app/api/nodopagamenti_api/wisp/cfg/prod/batch_migration_cis.txt
  src/domains/nodo-app/api/nodopagamenti_api/wisp/cfg/prod/batch_migration_stations.txt
  src/domains/nodo-app/api/nodopagamenti_api/wisp/cfg/uat/batch_migration_cis.txt
  src/domains/nodo-app/api/nodopagamenti_api/wisp/cfg/uat/batch_migration_stations.txt
  src/domains/nodo-app/api/nodopagamenti_api/wisp/wisp-batch-migration.xml
  src/domains/nodo-common/03_cosmosdb_wisp_converter.tf
  src/domains/nodo-common/06_service_bus_wisp_converter.tf
  src/domains/nodo-common/99_variables.tf
  src/domains/nodo-common/README.md
  src/domains/nodo-common/env/weu-dev/terraform.tfvars
  src/domains/nodo-common/env/weu-prod/terraform.tfvars
  src/domains/nodo-common/env/weu-uat/terraform.tfvars
Labels: env: dev, env: uat, env: prod, wisp

#2412 feat: Add LAP apim infra
  src/domains/bizevents-app/04_apim_lap.tf
  src/domains/bizevents-app/README.md
  src/domains/bizevents-app/api/lap-service/v1/_base_policy-jwt.xml
  src/domains/bizevents-app/api/lap-service/v1/_base_policy.xml
  src/domains/bizevents-app/api/lap-service/v1/_openapi-jwt.json.tpl
  src/domains/bizevents-app/api/lap-service/v1/_openapi.json.tpl
  src/domains/bizevents-app/api_product/lap-service/_base_policy.xml
  src/domains/bizevents-common/02_security.tf
  src/domains/bizevents-common/README.md
Labels: status: applied :hand:

#1878 feat: Add ndp.pagopa.it
  src/core/dns_ndp.tf
Labels: env: prod, status: applied :hand:

#2413 fix: [PAGOPA-2112] Fix send-payment-result-v2
  src/core/api/payment_manager_api/pm-per-nodo/v2/_base_policy.xml
  src/core/api/payment_manager_api/pm-per-nodo/v2/_base_policy.xml.tpl
  src/core/api/payment_manager_api/pm-per-nodo/v2/wisp-sendpaymentresult.xml.tpl
  src/core/apim_payment_manager.tf
  src/core/dns_ndp.tf
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#2403 chore: Biz updated secrets
  src/domains/bizevents-common/02_security.tf
  src/domains/bizevents-secrets/.terraform.lock.hcl
  src/domains/bizevents-secrets/secret/weu-dev/noedit_secret_enc.json
  src/domains/bizevents-secrets/secret/weu-prod/noedit_secret_enc.json
  src/domains/bizevents-secrets/secret/weu-uat/noedit_secret_enc.json
  src/domains/nodo-secret/02_security.tf
Labels: status: applied :hand:

#2419 chore: Fix ec biz service
  src/domains/bizevents-app/api/bizevents-service/v1/_base_policy.xml
  src/domains/bizevents-app/api/bizevents-service/v1/_openapi.json.tpl
Labels: status: applied :hand:

#2418 chore: Add alert cosmos_wisp_normalized_ru_exceeded
  src/domains/nodo-common/00_monitor.tf
  src/domains/nodo-common/03_cosmosdb_wisp_converter.tf
  src/domains/nodo-common/99_locals.tf
  src/domains/nodo-common/README.md
Labels: status: applied :hand:

#2377 [PAGOPA-1991] feat: added secrets for integration tests
  src/domains/nodo-common/02_security.tf
  src/domains/nodo-common/10_github_identity.tf
  src/domains/nodo-common/99_locals.tf
  src/domains/nodo-common/README.md
  src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
Labels: env: dev, env: uat, status: applied :hand:, wisp, nodo

#2401 refactor: round 2 removal of PGS APIs
  src/core/README.md
  src/core/api/payment_transactions_gateway_api/external/v1/_base_policy.xml.tpl
  src/core/api/payment_transactions_gateway_api/external/v1/_openapi.json.tpl
  src/core/api/payment_transactions_gateway_api/internal/v1/_base_policy.xml.tpl
  src/core/api/payment_transactions_gateway_api/internal/v1/_openapi.json.tpl
  src/core/api/payment_transactions_gateway_api/pgs-fe/v1/_base_policy.xml.tpl
  src/core/api/payment_transactions_gateway_api/pgs-fe/v1/_openapi.json.tpl
  src/core/api/payment_transactions_gateway_api/update/v1/_base_policy.xml.tpl
  src/core/api/payment_transactions_gateway_api/update/v1/_openapi.json.tpl
  src/core/apim_payment_transactions_gateway.tf
Labels: env: dev, status: applied

#2390 chore: remove keys used by PGS for eCommerce
  .devops/ecommerce-code-review-pipelines.yml
  src/core/README.md
  src/core/api/payment_transactions_gateway_api/external/v1/_base_policy.xml.tpl
  src/core/api/payment_transactions_gateway_api/external/v1/_openapi.json.tpl
  src/core/api/payment_transactions_gateway_api/internal/v1/_base_policy.xml.tpl
  src/core/api/payment_transactions_gateway_api/internal/v1/_openapi.json.tpl
  src/core/api/payment_transactions_gateway_api/pgs-fe/v1/_base_policy.xml.tpl
  src/core/api/payment_transactions_gateway_api/pgs-fe/v1/_openapi.json.tpl
  src/core/api/payment_transactions_gateway_api/update/v1/_base_policy.xml.tpl
  src/core/api/payment_transactions_gateway_api/update/v1/_openapi.json.tpl
  src/core/apim_payment_transactions_gateway.tf
  src/domains/checkout-app/05_checkout_fe.tf
  src/domains/ecommerce-common/02_security.tf
  src/domains/ecommerce-common/README.md
  src/domains/nodo-app/04_apim_wisp_dismantling_policies.tf
  src/domains/nodo-common/env/weu-dev/terraform.tfvars
Labels: env: dev, status: applied

#2420 feat: [PAGOPA-1647] pm ingestion
  scripts/generate_terraform_import.py
  src/domains/bizevents-app/04_apim_bizevents_pm_ingestion.tf
  src/domains/bizevents-app/README.md
  src/domains/bizevents-secrets/secret/weu-dev/noedit_secret_enc.json
  src/domains/bizevents-secrets/secret/weu-prod/noedit_secret_enc.json
  src/domains/bizevents-secrets/secret/weu-uat/noedit_secret_enc.json
Labels: status: applied :hand:

#2415 feat: [PAGOPA-2091] WISP RPT timeout
  src/core/api/nodopagamenti_api/nodoPerPa/v1/wisp_nodoInviaRPT_nodoInviaCarrelloRPT_outbound_policy.xml
  src/domains/nodo-app/04_apim_wisp_converter_04_caching.tf
  src/domains/nodo-app/api/wisp-converter/caching/v1/delete_sessionId_policy.xml
  src/domains/nodo-app/api/wisp-converter/caching/v1/openapi.json
  src/domains/nodo-common/02_security.tf
  src/domains/nodo-common/06_service_bus_wisp_converter.tf
  src/domains/nodo-common/env/weu-dev/terraform.tfvars
  src/domains/nodo-common/env/weu-prod/terraform.tfvars
  src/domains/nodo-common/env/weu-uat/terraform.tfvars
Labels: env: dev, env: uat, env: prod, status: applied :hand:, wisp

#2427 chore: Fix test api biz lap
  src/domains/bizevents-app/04_apim_lap.tf
Labels: status: applied :hand:

#2423 feat: add receipt pdf technical support api to assistenza product
  src/domains/receipts-app/04_apim_receipts.tf
Labels: status: applied :hand:

#2429 feat: [PAYMCLOUD-82] initial integration with sops on next-core
  scripts/sops.sh
  scripts/terrasops.sh
  src/next-core-secrets/.terraform.lock.hcl
  src/next-core-secrets/02_key_secret.tf
  src/next-core-secrets/0_init_key_sops.tf
  src/next-core-secrets/99_locals.tf
  src/next-core-secrets/99_main.tf
  src/next-core-secrets/99_variables.tf
  src/next-core-secrets/README.md
  src/next-core-secrets/env/dev/backend.ini
  src/next-core-secrets/env/dev/backend.tfvars
  src/next-core-secrets/env/dev/terraform.tfvars
  src/next-core-secrets/env/prod/backend.ini
  src/next-core-secrets/env/prod/backend.tfvars
  src/next-core-secrets/env/prod/terraform.tfvars
  src/next-core-secrets/env/uat/backend.ini
  src/next-core-secrets/env/uat/backend.tfvars
  src/next-core-secrets/env/uat/terraform.tfvars
  src/next-core-secrets/secret/dev/configs.json
  src/next-core-secrets/secret/dev/noedit_secret_enc.json
  src/next-core-secrets/secret/dev/secret.ini
  src/next-core-secrets/secret/prod/configs.json
  src/next-core-secrets/secret/prod/secret.ini
  src/next-core-secrets/secret/uat/configs.json
  src/next-core-secrets/secret/uat/secret.ini
  src/next-core-secrets/sops.sh
  src/next-core-secrets/terraform.sh
  src/next-core-secrets/terrasops.sh
  src/next-core/01_security.tf
  src/next-core/80_vpn.tf
  src/next-core/99_variables.tf
  src/next-core/README.md
  src/next-core/env/dev/terraform.tfvars
Labels: status: applied

#2428 fix: [PAGOPA-2155] Added check on nodoInviaRPT/nodoInviaCarrelloRPT outbound policy
  src/core/api/nodopagamenti_api/nodoPerPa/v1/wisp_nodoInviaRPT_nodoInviaCarrelloRPT_outbound_policy.xml
Labels: env: dev, env: uat, env: prod, status: applied :hand:, wisp

#2431 feat: add biz event service helpdesk api to assistenza product
  src/domains/bizevents-app/04_apim_bizevents.tf
Labels: status: applied :hand:

#2434 feat: [PAYMCLOUD-83] New pipeline code review next core secrets with refactor
  .devops/base-code-review-pipelines.yml
  .devops/base-deploy-pipelines.yml
  .devops/next-core-secrets-code-review-pipelines.yml
  .devops/next-core-secrets-deploy-pipelines.yml
  src/next-core/07_azure_devops_agent.tf
Labels: status: applied

#2449 chore: Add gh identity pagopa-afm-fee-reporting-service
  src/domains/afm-common/10_github_identity.tf
Labels: status: applied :hand:
