Repository pagopa/pagopa-infra, pull requests merged in 2024-08, with the labels that each got.

#2329 [PAGOPA-1946] feat: routing whitelisted payment types on WISP dismantling
  src/core/api_product/nodo_pagamenti_api/decoupler/decoupler-algorithm.xml
  src/domains/nodo-app/04_apim_wisp_dismantling_policies.tf
  src/domains/nodo-app/99_variables.tf
  src/domains/nodo-app/README.md
  src/domains/nodo-app/env/weu-dev/terraform.tfvars
  src/domains/nodo-app/env/weu-prod/terraform.tfvars
  src/domains/nodo-app/env/weu-uat/terraform.tfvars
Labels: status: applied :hand:

#2342 PAGOPA-1957 adding logic for wfesp
  src/core/api_product/nodo_pagamenti_api/decoupler/decoupler-activate-outbound.xml
  src/core/api_product/nodo_pagamenti_api/decoupler/decoupler-algorithm.xml
  src/domains/nodo-app/04_apim_wfesp_dismantling.tf
  src/domains/nodo-app/99_variables.tf
  src/domains/nodo-app/env/weu-dev/terraform.tfvars
  src/domains/nodo-app/env/weu-prod/terraform.tfvars
  src/domains/nodo-app/env/weu-uat/terraform.tfvars
Labels: status: applied :hand:

#2353 [PAGOPA-2001] fix: resolved bug on KO sendpaymentresult on WISP dismantling
  src/core/api/payment_manager_api/pm-per-nodo/v2/wisp-sendpaymentresult.xml
  src/domains/nodo-app/api/nodopagamenti_api/wisp/wisp-sendpaymentresult.xml
Labels: status: applied :hand:

#2359 [PAGOPA] feat: Update node-forwarder-availability alert
  src/next-core/06_node_forwarder.tf
Labels: status: applied :hand:

#2363 [PAGOPA-1994] fix: changed wrong stations for WISP dismantling
  src/domains/nodo-app/env/weu-uat/terraform.tfvars
Labels: env: uat, status: applied :hand:

#2362 feat: Add ISTITUTO COMPRENSIVO GRUGLIASCO a Trasporti Integrati e Logistica…
  src/domains/nodo-app/env/weu-prod/terraform.tfvars
Labels: status: applied :hand:

#2365 chore: Add perms-seflfcare-kv-dev-uat
  src/domains/selfcare-common/02_security.tf
Labels: status: applied :hand:

#2344 chore: Add printit to statuspage [PPANTT-15]
  src/domains/shared-app/04_apim_statuspage.tf
Labels: status: applied :hand:

#2366 feat: [PQ-89] - ndp integration test enhancement
  src/domains/afm-app/04_apim_afm_calculator.tf
  src/domains/afm-app/api/calculator-service/node/v1/_base_policy.xml
Labels: status: applied :hand:

#2355 feat: [PAGOPA-2002] feat(wisp-dis): Add receipts-rt container
  src/domains/nodo-common/03_cosmosdb_wisp_converter.tf
  src/domains/nodo-common/99_variables.tf
  src/domains/nodo-common/README.md
  src/domains/nodo-common/env/weu-dev/terraform.tfvars
  src/domains/nodo-common/env/weu-prod/terraform.tfvars
  src/domains/nodo-common/env/weu-uat/terraform.tfvars
Labels: status: applied :hand:

#2368 feat: Add new EC/station to DismissioneWISP
  src/domains/nodo-app/env/weu-prod/terraform.tfvars
Labels: status: applied :hand:

#2369 feat: Remove wispdism step3
  src/domains/nodo-app/env/weu-prod/terraform.tfvars
Labels: status: applied :hand:

#2356 fix gps space
  src/elk-monitoring/05_kibana_log_pagopapaymentspull.tf
  src/elk-monitoring/05_kibana_log_pagopaprintit.tf
  src/elk-monitoring/README.md
  src/elk-monitoring/pagopa/gps/component@custom.json
  src/elk-monitoring/pagopa/gps/data-view.json
  src/elk-monitoring/pagopa/gps/ilm-policy.json
  src/elk-monitoring/pagopa/gps/index-template.json
  src/elk-monitoring/pagopa/gps/ingest-pipeline.json
  src/elk-monitoring/pagopa/gps/space.json
  src/elk-monitoring/pagopa/printit/component@custom.json
  src/elk-monitoring/pagopa/printit/data-view.json
  src/elk-monitoring/pagopa/printit/ilm-policy.json
  src/elk-monitoring/pagopa/printit/index-template.json
  src/elk-monitoring/pagopa/printit/ingest-pipeline.json
  src/elk-monitoring/pagopa/printit/space.json
Labels: status: ready to apply, status: applied :hand:

#2370 chore: secrets regarding ecommerce for WISP
  src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
Labels: env: dev, env: uat, status: applied :hand:, wisp

#2367 fix: [PAGOPA-2008] Update `renewrequest` after setting password
  src/core/api_product/nodo_pagamenti_api/decoupler/base_policy.xml.tpl
Labels: env: dev, env: uat, env: prod, status: applied :hand:, nodo

#2352 [PPANTT-41] feat: Add station-maintenances flag for selfcare-backoffice
  src/domains/selfcare-common/04_app_configuration_feature.tf
  src/domains/selfcare-common/README.md
Labels: status: applied :hand:

#2375 fix: WFESP content-type
  src/core/api_product/nodo_pagamenti_api/decoupler/decoupler-activate-outbound.xml
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#2374 chore: Enable WISP for all [UAT]
  src/domains/nodo-app/env/weu-uat/terraform.tfvars
Labels: wisp

#2373 feat: Add SMO email secret to selfcare kv
  src/domains/selfcare-app/02_security.tf
Labels: env: prod, status: applied :hand:

#2315 feat: Stampa Avvisi
  src/domains/printit-app/00_alerts.tf
  src/domains/printit-app/99_locals.tf
  src/domains/printit-app/README.md
  src/domains/printit-app/env/itn-uat/terraform.tfvars
  src/domains/printit-common/10_github_identity.tf
  src/domains/printit-common/99_variables.tf
  src/domains/printit-common/README.md
  src/domains/printit-common/env/itn-dev/terraform.tfvars
  src/domains/printit-common/env/itn-prod/terraform.tfvars
  src/domains/printit-common/env/itn-uat/terraform.tfvars
  src/elk-monitoring/05_kibana_log_pagopaprintit.tf
  src/elk-monitoring/pagopa/printit/dashboards/dashboard_massive.ndjson
  src/elk-monitoring/pagopa/printit/data-view.json
Labels: status: applied :hand:, printit

#2382 chore: [PAGOPA-2039] Batch migration fragment for WISP
  src/core/api_product/nodo_pagamenti_api/decoupler/base_policy.xml.tpl
  src/core/api_product/nodo_pagamenti_api/decoupler/decoupler-algorithm.xml
  src/domains/nodo-app/04_apim_wisp_dismantling_policies.tf
  src/domains/nodo-app/api/nodopagamenti_api/wisp/cfg/dev/batch_migration_cis.txt
  src/domains/nodo-app/api/nodopagamenti_api/wisp/cfg/dev/batch_migration_stations.txt
  src/domains/nodo-app/api/nodopagamenti_api/wisp/cfg/prod/batch_migration_cis.txt
  src/domains/nodo-app/api/nodopagamenti_api/wisp/cfg/prod/batch_migration_stations.txt
  src/domains/nodo-app/api/nodopagamenti_api/wisp/cfg/uat/batch_migration_cis.txt
  src/domains/nodo-app/api/nodopagamenti_api/wisp/cfg/uat/batch_migration_stations.txt
  src/domains/nodo-app/api/nodopagamenti_api/wisp/wisp-batch-migration.xml
Labels: env: dev, env: uat, status: applied :hand:, wisp, core

#2371 feat: [PAGOPA-2003] Add policies to manage nodoChiediCopiaRT for WISP
  src/core/api_product/nodo_pagamenti_api/decoupler/base_policy.xml.tpl
  src/core/api_product/nodo_pagamenti_api/decoupler/decoupler-algorithm.xml
  src/domains/nodo-app/04_apim_wisp_dismantling_policies.tf
  src/domains/nodo-app/99_variables.tf
  src/domains/nodo-app/env/weu-dev/terraform.tfvars
  src/domains/nodo-app/env/weu-prod/terraform.tfvars
  src/domains/nodo-app/env/weu-uat/terraform.tfvars
Labels: env: dev, env: uat, wisp

#2389 chore: Add apim usr grp tech pagopa-core
  src/next-core/03_apim_management_groups.tf
  src/next-core/03_apim_management_tech_usr.tf
  src/next-core/README.md
Labels: status: applied :hand:

#2383 chore: [PAGOPA-2054] attivazione regione veneto 29/08/24 in PROD / parte 1
  src/domains/nodo-app/env/weu-prod/terraform.tfvars
Labels: env: prod, status: applied :hand:, wisp

#2386 feat: Add secrets and cfg for PM biz ingestion
  src/domains/bizevents-common/10_github_identity.tf
  src/domains/bizevents-secrets/secret/weu-dev/noedit_secret_enc.json
  src/domains/bizevents-secrets/secret/weu-prod/noedit_secret_enc.json
  src/domains/bizevents-secrets/secret/weu-uat/noedit_secret_enc.json
Labels: status: applied :hand:

#2388 feat: Enable authorizer fragment in ACA policy [PAGOPA-2059]
  src/domains/aca-app/04_apim_aca.tf
  src/domains/aca-app/api/aca/v1/_base_policy.xml
  src/domains/aca-app/api/aca/v1/_base_policy.xml.tpl
Labels: status: applied :hand:
