Repository pagopa/pagopa-infra, pull requests merged in 2024-05, with the labels that each got.

#1979 chore: PAGOPA-1726 updating openapi
  src/domains/afm-app/04_apim_afm_calculator.tf
  src/domains/afm-app/README.md
  src/domains/afm-app/api/calculator-service/node/v1/_openapi.json.tpl
  src/domains/afm-app/api/calculator-service/node/v2/_openapi.json.tpl
  src/domains/afm-app/api/calculator-service/v1/_openapi.json.tpl
  src/domains/afm-app/api/calculator-service/v2/_openapi.json.tpl
Labels: status: applied :hand:

#1942 chore: Ehub enableTxNS03 and disableTxNS01 ( DEV and UAT )
  src/core/README.md
  src/core/logicapp_btz_evt.tf
  src/domains/bizevents-common/02_security.tf
  src/domains/bizevents-common/99_variables.tf
  src/domains/bizevents-common/README.md
  src/domains/bizevents-common/env/weu-dev/terraform.tfvars
  src/domains/bizevents-common/env/weu-prod/terraform.tfvars
  src/domains/bizevents-common/env/weu-uat/terraform.tfvars
  src/domains/fdr-app/02_function.tf
  src/domains/fdr-app/05_fdr_re_fn.tf
  src/domains/fdr-app/99_variables.tf
  src/domains/fdr-app/README.md
  src/domains/fdr-app/env/weu-dev/terraform.tfvars
  src/domains/fdr-app/env/weu-prod/terraform.tfvars
  src/domains/fdr-app/env/weu-uat/terraform.tfvars
  src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
  src/domains/nodo-app/05_fn_ndp_re_to_tablestorage.tf
  src/domains/nodo-app/05_fn_ndp_verifyko_to_datastore.tf
  src/domains/nodo-app/05_fn_ndp_verifyko_to_tablestorage.tf
  src/domains/nodo-app/99_variables.tf
  src/domains/nodo-app/README.md
  src/domains/nodo-app/env/weu-dev/terraform.tfvars
  src/domains/nodo-app/env/weu-prod/terraform.tfvars
  src/domains/nodo-app/env/weu-uat/terraform.tfvars
  src/domains/nodo-common/env/weu-dev/terraform.tfvars
  src/domains/nodo-common/env/weu-uat/terraform.tfvars
  src/domains/qi-common/02_security.tf
Labels: env: dev, env: uat, status: applied :hand:

#1982 chore: Add `db-nodo-pagamenti-dr` a-record
  src/core/99_variables.tf
  src/core/README.md
  src/core/cosmos_db_payments.tf
  src/core/dns_private.tf
  src/core/env/prod/terraform.tfvars
Labels: env: prod, status: applied :hand:

#1983 chore: Add dataexp data-conn
  src/domains/observability/01_observability.tf
  src/domains/observability/README.md
Labels: status: applied :hand:

#1981 feat: NOD-879 add STAND_IN_NO_RPT
  src/domains/fdr-app/api/fdr-service-internal/v1/_openapi.json.tpl
  src/domains/fdr-app/api/fdr-service/org/v1/_openapi.json.tpl
  src/domains/fdr-app/api/fdr-service/psp/v1/_openapi.json.tpl
Labels: env: dev, env: uat, status: applied :hand:

#1976 chore: Advisor cost changes cosmos
  src/domains/bizevents-common/.terraform.lock.hcl
  src/domains/bizevents-common/00_monitor.tf
  src/domains/bizevents-common/03_cosmosdb_bizevents_datastore.tf
  src/domains/bizevents-common/99_locals.tf
  src/domains/bizevents-common/99_variables.tf
  src/domains/bizevents-common/README.md
  src/domains/bizevents-common/env/weu-dev/terraform.tfvars
  src/domains/bizevents-common/env/weu-prod/terraform.tfvars
  src/domains/bizevents-common/env/weu-uat/terraform.tfvars
  src/domains/fdr-common/env/weu-prod/terraform.tfvars
  src/domains/gps-common/env/weu-prod/terraform.tfvars
  src/domains/receipts-common/03_cosmosdb.tf
  src/domains/receipts-common/99_variables.tf
  src/domains/receipts-common/README.md
  src/domains/receipts-common/env/weu-dev/terraform.tfvars
  src/domains/receipts-common/env/weu-prod/terraform.tfvars
  src/domains/receipts-common/env/weu-uat/terraform.tfvars
Labels: status: applied :hand:

#1893 feat: NOD-777: [Dismissione WISP] ELK Monitoring
  .gitignore
  src/elk-monitoring/05_elastic_stack.tf
  src/elk-monitoring/05_kibana_dashboard_ndp.tf
  src/elk-monitoring/05_kibana_log_ndp.tf
  src/elk-monitoring/ndp/wispconverter/dashboard/wispconverter_Global.ndjson
  src/elk-monitoring/ndp/wispsoapconverter/dashboard/wispsoapconverter_Global.ndjson
  src/elk-monitoring/ndp/wispsoapconverter/dashboard/wispsoapconverter_Monitor_EC.ndjson
  src/elk-monitoring/ndp/wispsoapconverter/ingest-pipeline.json
Labels: env: dev, env: uat, env: prod, status: applied

#1907 feat: Applied feature flags selfcare
  src/domains/selfcare-common/.terraform.lock.hcl
Labels: env: dev, status: ready to apply, status: applied :hand:, selfcare

#1998 chore: Upd open-api market-place BE
  src/domains/afm-app/api/marketplace-service/v1/_openapi.json.tpl
Labels: status: applied :hand:

#1948 PAGOPA-1695 adding paSendRT poison queue
  src/domains/gps-common/02_security.tf
  src/domains/gps-common/03_gpd_storage_account_sftp.tf
Labels: status: applied :hand:

#1991 [CHK-2805] feat(mock): add basic mock definition for NPG
  src/domains/ecommerce-app/04_apim_ecommerce_mock.tf
  src/domains/ecommerce-app/README.md
  src/domains/ecommerce-app/api/ecommerce-mock/npg/v1/_base_policy.xml.tpl
  src/domains/ecommerce-app/api/ecommerce-mock/npg/v1/_openapi.json.tpl
  src/domains/ecommerce-app/api/ecommerce-mock/npg/v1/confirm_payment.xml.tpl
  src/domains/ecommerce-app/api/ecommerce-mock/npg/v1/get_card_data.xml.tpl
  src/domains/ecommerce-app/api/ecommerce-mock/npg/v1/get_state.xml.tpl
  src/domains/ecommerce-app/api/ecommerce-mock/npg/v1/post_orders_build.xml.tpl
  src/domains/ecommerce-app/api/ecommerce-mock/npg/v1/refund_payment.xml.tpl
Labels: env: dev, status: applied

#1980 [NOD-714] feat: add 'pagopa-fdr-nodo-dei-pagamenti' for GH identity
  src/domains/fdr-common/10_github_identity.tf
  src/domains/fdr-common/README.md
  src/domains/fdr-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/fdr-secret/secret/weu-uat/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#2009 chore: PAGOPA-1681 updating biz openapi
  src/domains/bizevents-app/api/bizevents-helpdesk/v1/_openapi.json.tpl
  src/domains/bizevents-app/api/bizevents-service/v1/_openapi.json.tpl
  src/domains/bizevents-app/api/transaction-service/v1/_openapi.json.tpl
Labels: status: applied :hand:

#1987 chore: POST session wallet token pagoPA for AppIO 📲
  src/core/.terraform.lock.hcl
  src/domains/bizevents-app/04_apim_bizevents.tf
  src/domains/bizevents-app/README.md
  src/domains/bizevents-app/api/transaction-service/v1/_base_policy-jwt.xml
  src/domains/bizevents-app/api/transaction-service/v1/_openapi-jwt.json.tpl
  src/domains/bizevents-common/02_security.tf
  src/domains/bizevents-common/README.md
  src/domains/shared-app/04_apim_io_wallet_session.tf
  src/domains/shared-app/99_variables.tf
  src/domains/shared-app/README.md
  src/domains/shared-app/api/session-wallet/v1/_base_policy.xml.tpl
  src/domains/shared-app/api/session-wallet/v1/_fragment_policiy_chk_jwt.tpl.xml
  src/domains/shared-app/api/session-wallet/v1/_openapi.json.tpl
  src/domains/shared-app/api_product/session-wallet/_base_policy.xml
  src/domains/shared-app/env/weu-dev/terraform.tfvars
  src/domains/shared-app/env/weu-prod/terraform.tfvars
  src/domains/shared-app/env/weu-uat/terraform.tfvars
  src/domains/shared-common/02_security.tf
  src/domains/shared-common/README.md
Labels: env: dev, env: uat, status: applied :hand:

#1984 feat(gpd-upload): Add instance to ELK [PAGOPA-1595]
  src/domains/gps-app/api/gpd-upload-service/v1/_base_policy.xml
  src/elk-monitoring/05_elastic_stack.tf
Labels: status: applied :hand:

#2013 chore: Remove base include from ACA
  src/domains/aca-app/api/aca/v1/_base_policy.xml.tpl
  src/domains/aca-app/api_product/_base_policy.xml
Labels: status: applied :hand:

#2017 chore: [NOD-895] Secret apiconfig-kv
  src/domains/apiconfig-common/02_security.tf
Labels: env: dev, env: uat, status: applied :hand:

#2024 chore: Switch Hhub PROD from NS01 to NS03
  src/domains/bizevents-common/02_security.tf
  src/domains/bizevents-common/env/weu-prod/terraform.tfvars
  src/domains/fdr-app/env/weu-prod/terraform.tfvars
  src/domains/nodo-app/env/weu-prod/terraform.tfvars
  src/domains/nodo-common/env/weu-prod/terraform.tfvars
  src/domains/nodo-switcher/env/weu-prod/terraform.tfvars
Labels: status: applied :hand:

#2023 chore: Setup app forwarder for SMO NExi Jira notification
  src/domains/observability/05_app_forwarder.tf
  src/domains/observability/99_variables.tf
  src/domains/observability/README.md
  src/domains/observability/env/weu-dev/terraform.tfvars
  src/domains/observability/env/weu-uat/terraform.tfvars
  src/domains/observability/scripts/certs/dev-certificate.crt
  src/domains/observability/scripts/certs/dev-private.key
  src/domains/observability/scripts/set_kv_secrets.sh
Labels: status: applied :hand:

#2028 chore: [NOD-857] Nodo added secret
  src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json
Labels: env: prod, status: applied :hand:

#2018 feat: Add new collection maintenance to backoffice [VAS-1024]
  src/domains/selfcare-common/03_cosmosdb_bopagopa_datastore.tf
  src/domains/selfcare-common/README.md
Labels: env: dev, status: applied :hand:, selfcare

#2031 fix: [NOD-836] FdR secrets in uat
  src/domains/fdr-secret/secret/weu-uat/noedit_secret_enc.json
Labels: env: uat, status: applied :hand:, fdr

#2033 chore: [NOD-884] Alert node cfg sync
  src/domains/nodo-app/00_alert_node_cfg_sync.tf
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#2041 chore: [NOD-901] Liquibase nodo - viste
  src/psql/nodo/liquibase/changelog/cfg-partner/3.28.0/db.changelog-20240517000000_elenco_servizi_view.xml
  src/psql/nodo/liquibase/changelog/cfg-partner/3.28.0/db.changelog-20240517010000_cdi_preferences_view.xml
  src/psql/nodo/liquibase/changelog/cfg-partner/db.changelog-master-3.28.0.xml
  src/psql/nodo/liquibase/changelog/cfg/3.28.0/db.changelog-20240517000000_elenco_servizi_view.xml
  src/psql/nodo/liquibase/changelog/cfg/3.28.0/db.changelog-20240517010000_cdi_preferences_view.xml
  src/psql/nodo/liquibase/changelog/cfg/db.changelog-master-3.28.0.xml
Labels: env: dev, nodo

#2035 feat: [PAGOPA-1741] get pdf receipt
  src/domains/bizevents-app/api/transaction-service/v1/_openapi-jwt.json.tpl
  src/domains/bizevents-app/api/transaction-service/v1/_openapi.json.tpl
  src/domains/bizevents-common/02_security.tf
  src/domains/bizevents-common/99_locals.tf
  src/domains/bizevents-common/README.md
Labels: status: applied :hand:

#2029 [PAGOPA-1744] chore(GPD): Update APIs
  src/domains/gps-app/api/gpd_api/debt-position-services/v1/_openapi.json.tpl
  src/domains/gps-app/api/gpd_api/v1/_openapi.json.tpl
Labels: env: dev, env: uat, status: applied :hand:

#2050 chore: [NOD-893] secret partition
  src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
Labels: env: dev, env: uat, env: prod, status: applied :hand:, nodo

#2056 feat: Core itn uat prod
  src/core-itn/00_dns_private.tf
  src/core-itn/01_keyvault.tf
  src/core-itn/01_network.tf
  src/core-itn/02_dns_private_link.tf
  src/core-itn/10_evenhubs.tf
  src/core-itn/99_variables.tf
  src/core-itn/README.md
  src/core-itn/env/uat/terraform.tfvars
Labels: env: dev, env: uat, env: prod, status: applied

#2051 feat: add `pagopa-mbd` repository for GH identity [NOD-906]
  src/domains/nodo-common/10_github_identity.tf
Labels: env: dev, env: uat, env: prod, status: applied :hand:, mbd

#2047 [NOD-905] feat: add secrets for integration tests and OpEx dashboards
  src/domains/fdr-common/00_data.tf
  src/domains/fdr-common/02_security.tf
  src/domains/fdr-common/05_subscription_key.tf
  src/domains/fdr-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/fdr-secret/secret/weu-prod/noedit_secret_enc.json
Labels: fdr

#2034 fix: Feature flags
  src/domains/selfcare-common/.terraform.lock.hcl
  src/domains/selfcare-common/02_security.tf
  src/domains/selfcare-common/04_app_configuration_feature.tf
Labels: selfcare

#2058 feat: Introducing complete and errors notice eventhub topic [VAS-835]
  src/domains/printit-app/00_data.tf
  src/domains/printit-app/06_keyvault.tf
  src/domains/printit-common/03_eventhub.tf
Labels: env: dev, env: uat

#2048 feat: Subkey printit
  src/domains/printit-app/06_keyvault.tf
  src/domains/printit-app/README.md
  src/domains/printit-common/03_storage_account_notices.tf
  src/domains/printit-common/10_github_identity.tf
  src/domains/printit-common/README.md
Labels: printit

#2068 chore: Add LstTrx KV secrets
  src/domains/bizevents-common/02_security.tf
  src/domains/bizevents-common/README.md
Labels: status: applied :hand:

#2052 chore(shared-app): Authorizer migration to AKS [PAGOPA-1678]
  src/domains/shared-app/04_apim_statuspage.tf
  src/domains/shared-app/05_authorizer_functions.tf
  src/domains/shared-app/99_locals.tf
  src/domains/shared-common/.terraform.lock.hcl
  src/domains/shared-common/10_github_identity.tf
Labels: status: applied :hand:

#2046 feat: Update ACA OpenAPI [PAGOPA-1711]
  src/domains/aca-app/api/aca/v1/_openapi.json.tpl
Labels: status: applied :hand:

#1785 chore : Switch from apicfg-core from oracle to pglfex
  src/core/99_variables.tf
  src/core/README.md
  src/core/api/nodopagamenti_api/nodeForPsp/v1/activate_nm3.xml
  src/core/api/nodopagamenti_api/nodeForPsp/v2/activate_nm3.xml
  src/core/apim.tf
  src/core/env/dev/terraform.tfvars
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
  src/domains/apiconfig-app/04_apim_product_apiconfig-selfcare-integration.tf
  src/domains/apiconfig-app/api/apiconfig-selfcare-integration/v1/_base_policy.xml
  src/domains/apiconfig-app/api/apiconfig-selfcare-integration/v1/_openapi.json.tpl
  src/domains/apiconfig-app/api/apiconfig_api/jwt/v1/_base_policy.xml.tpl
  src/domains/apiconfig-app/api/apiconfig_api/subkey/v1/_base_policy.xml.tpl
  src/domains/nodo-app/api/nodopagamenti_api/nodeForPsp/v1/activate_nm3.xml
  src/domains/nodo-app/api/nodopagamenti_api/nodeForPsp/v2/activate_nm3.xml
  src/domains/nodo-app/apim_v2/api/nodopagamenti_api/nodeForPsp/v1/activate_nm3.xml
  src/domains/nodo-app/apim_v2/api/nodopagamenti_api/nodeForPsp/v2/activate_nm3.xml
  src/domains/nodo-app/env/weu-dev/terraform.tfvars
  src/domains/shared-app/04_apim_statuspage.tf
  src/next-core/api/nodopagamenti_api/nodeForPsp/v1/activate_nm3.xml
  src/next-core/api/nodopagamenti_api/nodeForPsp/v2/activate_nm3.xml
Labels: status: applied :hand:

#2066 feat: Migrated prod redis to ha version
  src/domains/apiconfig-common/env/weu-prod/terraform.tfvars
  src/domains/bizevents-common/env/weu-prod/terraform.tfvars
  src/domains/nodo-common/env/weu-prod/terraform.tfvars
  src/domains/shared-common/env/weu-prod/terraform.tfvars
Labels: env: prod, no merge, on hold, status: ready to apply

#2075 [NOD-931] fix: add OR clause on CANALE_APP column value setting
  src/psql/nodo/liquibase/changelog/cfg-partner/3.28.0/db.changelog-20240527000000_update_elenco_servizi_view_master.xml
  src/psql/nodo/liquibase/changelog/cfg-partner/db.changelog-master-3.28.0.xml
  src/psql/nodo/liquibase/changelog/cfg/3.28.0/db.changelog-20240527000000_update_elenco_servizi_view_master.xml
  src/psql/nodo/liquibase/changelog/cfg/db.changelog-master-3.28.0.xml
  src/psql/nodo/liquibase/changelog/online/3.26.0/sql/1_DDL_TABLE.sql
  src/psql/nodo/liquibase/changelog/wfesp/3.26.0/sql/1_DDL_TABLE.sql
Labels: env: dev, released, nodo

#2082 chore: Wallet session IO list-trx
  src/domains/bizevents-app/04_apim_bizevents.tf
  src/domains/bizevents-app/99_variables.tf
  src/domains/bizevents-app/README.md
  src/domains/bizevents-app/api/transaction-service/v1/_base_policy-jwt.xml
  src/domains/bizevents-app/api/transaction-service/v1/_openapi-jwt.json.tpl
  src/domains/bizevents-app/api/transaction-service/v1/_openapi.json.tpl
  src/domains/bizevents-app/env/weu-dev/terraform.tfvars
  src/domains/bizevents-app/env/weu-prod/terraform.tfvars
  src/domains/bizevents-app/env/weu-uat/terraform.tfvars
Labels: env: dev, env: uat, status: applied :hand:

#2089 fix(gpd-upload): [PAGOPA-1789] Update authorization_entity variable
  src/domains/gps-app/api/gpd-upload-service/v1/_base_policy.xml
Labels: status: applied :hand:

#2092 fix: [NOD-936] Add nodo api monitoring to apim_x_node product
  src/core/apim_nodo_monitoring_services.tf
Labels: env: dev, nodo

#2062 feat: [NOD-829] Next FdR release
  src/domains/fdr-app/00_alert.tf
  src/domains/fdr-app/00_alert_fdr_fase1.tf
  src/domains/fdr-app/00_alert_fdr_fase3.tf
  src/domains/fdr-app/00_alert_fdr_jsontoxml.tf
  src/domains/fdr-app/00_alert_fdr_xmltojson.tf
  src/domains/fdr-app/05_fdr_re_fn.tf
  src/domains/fdr-app/99_variables.tf
  src/domains/fdr-app/README.md
  src/domains/fdr-app/env/weu-uat/terraform.tfvars
  src/domains/fdr-common/00_data.tf
  src/domains/fdr-common/02_security.tf
  src/domains/fdr-common/03_cosmos_mongodb_fdr.tf
  src/domains/fdr-common/05_subscription_key.tf
  src/domains/fdr-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/fdr-secret/secret/weu-prod/noedit_secret_enc.json
Labels: env: dev, env: uat, status: applied :hand:, fdr
