Repository pagopa/pagopa-infra, pull requests merged in 2024-01, with the labels that each got.

#1592 fix: Verify KO
  src/domains/nodo-app/00_alert_ndp_verifyko.tf
  src/domains/nodo-app/05_fn_ndp_verifyko_to_datastore.tf
  src/domains/nodo-app/05_fn_ndp_verifyko_to_tablestorage.tf
  src/domains/nodo-app/99_variables.tf
  src/domains/nodo-app/env/weu-dev/terraform.tfvars
  src/domains/nodo-app/env/weu-prod/terraform.tfvars
  src/domains/nodo-app/env/weu-uat/terraform.tfvars
  src/domains/nodo-common/01_events.tf
  src/domains/nodo-common/01_network.tf
  src/domains/nodo-common/03_cosmosdb_nodo_verifyko.tf
  src/domains/nodo-common/03_storage_account_nodo_verifyko.tf
  src/domains/nodo-common/99_variables.tf
  src/domains/nodo-common/env/weu-dev/terraform.tfvars
  src/domains/nodo-common/env/weu-prod/terraform.tfvars
  src/domains/nodo-common/env/weu-uat/terraform.tfvars
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#1610 Scaling verifyko fn
  src/domains/nodo-app/00_data.tf
  src/domains/nodo-app/05_fn_ndp_verifyko_to_datastore.tf
  src/domains/nodo-app/05_fn_ndp_verifyko_to_tablestorage.tf
  src/domains/nodo-app/env/weu-prod/terraform.tfvars
Labels: env: prod, status: applied :hand:

#1577 [PRDP-276] feat: updated cosmosdb
  src/domains/receipts-common/03_cosmosdb.tf
  src/domains/receipts-common/README.md
  src/domains/receipts-common/scripts/store_procedure.js
Labels: status: applied :hand:

#1611 [PRDP-307] chore: Updated receipt helpdesk openapi with getCart API
  src/domains/receipts-app/api/receipt-helpdesk/v1/_openapi.json.tpl
Labels: status: applied :hand:

#1614 Fix Verify ko autoscaling
  src/domains/nodo-app/05_fn_ndp_verifyko_to_tablestorage.tf
  src/domains/nodo-app/99_variables.tf
  src/domains/nodo-app/env/weu-prod/terraform.tfvars
Labels: env: prod, status: applied :hand:

#1612 added topic for qi psp kpi
  src/core/env/dev/terraform.tfvars
Labels: env: dev, status: applied :hand:

#1617 feat: Partial DIS-43 - updated SA replication type
  src/domains/canoneunico/env/prod/terraform.tfvars
  src/domains/fdr-app/02_function.tf
  src/domains/fdr-app/99_variables.tf
  src/domains/fdr-app/env/weu-dev/terraform.tfvars
  src/domains/fdr-app/env/weu-prod/terraform.tfvars
  src/domains/fdr-app/env/weu-uat/terraform.tfvars
  src/domains/gps-common/03_reporting_storage_account.tf
  src/domains/gps-common/99_variables.tf
  src/domains/gps-common/env/weu-prod/terraform.tfvars
  src/elk-monitoring/env/weu-prod/terraform.tfvars
Labels: status: applied

#1619 [PRDP-285] feat: updated openapi.json.tpl
  src/domains/receipts-app/api/receipt-helpdesk/v1/_openapi.json.tpl
Labels: status: applied :hand:

#1626 [CHK-2305] feat(cdn): redirect ecommerce-fe outcome pages to ecommerce-fe index
  src/domains/checkout-app/05_checkout_fe.tf
Labels: env: dev, status: applied :hand:

#1636 [PRDP-328] fix: Changed consistency level account receipt-datastore to STRONG
  src/domains/receipts-common/env/weu-uat/terraform.tfvars
Labels: env: uat

#1633 [CHK-2320] feat(checkout-redirect): add secret to handle Checkout Redirect PSP API keys
  src/domains/ecommerce-common/02_security.tf
  src/domains/ecommerce-common/README.md
Labels: env: dev, status: applied

#1650 chore: PAGOPA-1220-configurazione-alert-su-opsgenie-per-biz-event
  src/domains/bizevents-app/00_alert.tf
  src/domains/bizevents-app/00_monitor.tf
  src/domains/bizevents-app/99_locals.tf
  src/domains/bizevents-app/README.md
Labels: status: applied :hand:

#1652 feat(cosmos): add email index
  src/domains/ecommerce-common/03_cosmosdb.tf
Labels: env: dev, env: uat, status: applied :hand:

#1631 update-biz-openapi
  src/domains/bizevents-app/api/bizevents-service/v1/_base_policy.xml
  src/domains/bizevents-app/api/bizevents-service/v1/_openapi.json.tpl
Labels: status: applied :hand:

#1645 [PAGOPA-1449] feat: Add domain managed identity
  src/core/identity_rg.tf
  src/domains/afm-common/10_github_identity.tf
  src/domains/afm-common/README.md
  src/domains/apiconfig-common/10_github_identity.tf
  src/domains/apiconfig-common/README.md
  src/domains/bizevents-common/10_github_identity.tf
  src/domains/bizevents-common/README.md
  src/domains/fdr-common/10_github_identity.tf
  src/domains/fdr-common/README.md
  src/domains/gps-common/10_github_identity.tf
  src/domains/gps-common/README.md
  src/domains/nodo-common/10_github_identity.tf
  src/domains/nodo-common/README.md
  src/domains/receipts-common/10_github_identity.tf
  src/domains/receipts-common/README.md
  src/domains/selfcare-common/10_github_identity.tf
  src/domains/selfcare-common/README.md
  src/domains/shared-common/10_github_identity.tf
  src/domains/shared-common/README.md
Labels: status: applied :hand:

#1649 [PASELC-706] fix: updates on MongoDB collections for Selfcare BackOffice
  src/domains/selfcare-common/03_cosmosdb_bopagopa_datastore.tf
  src/domains/selfcare-common/README.md
  src/domains/selfcare-common/env/weu-prod/terraform.tfvars
Labels: status: applied :hand:

#1533 NOD-589 - disable serverless on fdr and fdr-re
  src/domains/fdr-common/env/weu-dev/terraform.tfvars
  src/domains/fdr-common/env/weu-uat/terraform.tfvars
  src/domains/fdr-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/fdr-secret/secret/weu-uat/noedit_secret_enc.json
Labels: env: dev, env: uat, status: applied :hand:

#1660 chore: [PAGOPA-1088] Housekeeping
  src/domains/apiconfig-app/04_apim_fragment_apiconfig_cache.tf
  src/domains/apiconfig-app/api/apiconfig-cache/node_fdr/_base_policy_cache_on_apim.xml
  src/domains/apiconfig-app/api/apiconfig-cache/node_fdr/generate_cache_fragment.xml
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#1661 add: [QI] new topics for qi psp kpi
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
Labels: status: applied :hand:

#1669 feat: [NOD-674][NOD-675] Added repo to github identity
  src/domains/nodo-common/10_github_identity.tf
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#1672 feat: [NOD-575] add subkey x core
  src/domains/apiconfig-common/02_security.tf
Labels: status: applied :hand:

#1676 modified station used to call nodoChiediElencoFlussi api
  src/domains/gps-app/env/weu-prod/terraform.tfvars
Labels: status: applied :hand:

#1684 chore: Add new receipts secrets
  src/domains/receipts-secrets/secret/weu-dev/noedit_secret_enc.json
  src/domains/receipts-secrets/secret/weu-prod/noedit_secret_enc.json
  src/domains/receipts-secrets/secret/weu-uat/noedit_secret_enc.json
Labels: status: applied :hand:

#1532 feat: Add GPD Upload service infra [PAGOPA-1360]
  src/domains/gps-app/04_apim_gpd.tf
  src/domains/gps-app/04_apim_gpd_core.tf
  src/domains/gps-app/04_apim_gpd_upload.tf
  src/domains/gps-app/README.md
  src/domains/gps-app/api/gpd-upload-service/v1/_base_policy.xml
  src/domains/gps-app/api/gpd-upload-service/v1/_openapi.json.tpl
  src/domains/gps-app/api/gpd_api/v2/_base_policy.xml
  src/domains/gps-app/api/gpd_api/v2/_openapi.json.tpl
  src/domains/gps-common/.terraform.lock.hcl
  src/domains/gps-common/01_network.tf
  src/domains/gps-common/02_security.tf
  src/domains/gps-common/03_cosmosdb.tf
  src/domains/gps-common/03_gpd_storage_account.tf
  src/domains/gps-common/03_storage_account.tf
  src/domains/gps-common/99_locals.tf
  src/domains/gps-common/99_variables.tf
  src/domains/gps-common/README.md
  src/domains/gps-common/env/weu-dev/terraform.tfvars
  src/domains/gps-common/env/weu-prod/terraform.tfvars
  src/domains/gps-common/env/weu-uat/terraform.tfvars
Labels: status: applied :hand:

#1665 NOD-673 definizione storage account history
  src/domains/fdr-common/03_storage_account_fdr_history.tf
  src/domains/fdr-common/99_variables.tf
  src/domains/fdr-common/env/weu-dev/terraform.tfvars
  src/domains/fdr-common/env/weu-prod/terraform.tfvars
  src/domains/fdr-common/env/weu-uat/terraform.tfvars
  src/domains/fdr-secret/02_security.tf
  src/domains/fdr-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/fdr-secret/secret/weu-prod/noedit_secret_enc.json
  src/domains/fdr-secret/secret/weu-uat/noedit_secret_enc.json
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#1696 chore: Remove `06874351007` from verificatore's brokerlist UAT
  src/core/env/uat/terraform.tfvars
Labels: status: applied :hand:

#1697 feat: [NOD-689] Added evt hub topic
  src/core/env/dev/terraform.tfvars
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
  src/domains/apiconfig-common/02_security.tf
  src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#1699 fix: [NOD-691] gh identity nodo
  src/domains/nodo-common/10_github_identity.tf
Labels: env: dev, env: uat, env: prod, status: applied :hand:
