Repository pagopa/pagopa-infra, pull requests merged in 2024-02, with the labels that each got.

#1704 feat: Updated gps cosmos zone redundancy
  src/domains/gps-common/env/weu-prod/terraform.tfvars
Labels: status: applied

#1707 [PRDP-356] Updated openapi as defined in service repo
  src/domains/bizevents-app/api/bizevents-helpdesk/v1/_base_policy.xml
  src/domains/bizevents-app/api/bizevents-helpdesk/v1/_openapi.json.tpl
  src/domains/bizevents-app/api/bizevents-service/v1/_openapi.json.tpl
  src/domains/bizevents-app/api/transaction-service/v1/_openapi.json.tpl
Labels: status: applied :hand:

#1712 chore : Upd biz secrets
  src/domains/bizevents-common/02_security.tf
  src/domains/bizevents-common/README.md
Labels: status: applied :hand:

#1718 feat: Updated storage account replication type
  src/domains/fdr-app/env/weu-prod/terraform.tfvars
  src/domains/nodo-app/05_fn_ndp_verifyko_to_datastore.tf
  src/domains/nodo-app/05_fn_ndp_verifyko_to_tablestorage.tf
  src/domains/nodo-app/99_variables.tf
  src/domains/nodo-app/env/weu-dev/terraform.tfvars
  src/domains/nodo-app/env/weu-prod/terraform.tfvars
  src/domains/nodo-app/env/weu-uat/terraform.tfvars
  src/domains/shared-app/env/weu-prod/terraform.tfvars
Labels: status: applied :hand:

#1719 chore: GitHub federated identity receitps repp
  src/domains/receipts-common/10_github_identity.tf
Labels: status: applied :hand:

#1720 fix empty column on fullouter join
  src/domains/observability/datafactory/pipelines/KPI_FDR_RENDICONTAZIONI.json
Labels: env: dev

#1515 feat: Add new domain appgw `upload.<ENV>.platform.pagopa.it` listener
  src/core/99_variables.tf
  src/core/README.md
  src/core/appgateway.tf
  src/core/dns_public.tf
  src/core/env/dev/terraform.tfvars
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
  src/core/security.tf
Labels: env: dev, env: uat, status: applied :hand:

#1710 PAGOPA-1172 adding afm calculator v2 api
  src/domains/afm-app/04_apim_afm_calculator.tf
  src/domains/afm-app/api/calculator-service/v2/_base_policy.xml
  src/domains/afm-app/api/calculator-service/v2/_openapi.json.tpl
Labels: env: dev, status: applied :hand:

#1732 chore: refactoring and setup GPD-SFTP-SA config [PAGOPA-1512]
  src/aks-platform/01_network.tf
  src/domains/gps-common/01_network.tf
  src/domains/gps-common/03_gpd_reporting_storage_account.tf
  src/domains/gps-common/03_gpd_storage_account_sftp.tf
  src/domains/gps-common/99_variables.tf
  src/domains/gps-common/README.md
  src/domains/gps-common/env/weu-dev/terraform.tfvars
  src/domains/gps-common/env/weu-prod/terraform.tfvars
  src/domains/gps-common/env/weu-uat/terraform.tfvars
Labels: status: applied :hand:

#1735 chore(GPD): add gpd-upload on status API [PAGOPA-1473]
  src/domains/shared-app/04_apim_statuspage.tf
Labels: status: applied :hand:

#1348 fix: UAT nodo monitoring
  src/core/api/nodopagamenti_api/monitoring/v1/_base_policy.xml.tpl
  src/core/api_product/nodo_pagamenti_api/monitoring/base_policy.xml.tpl
  src/core/apim_nodo_monitoring_services.tf
  src/core/apim_nodo_services_dev.tf
  src/core/env/dev/terraform.tfvars
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
Labels: env: dev, env: uat, status: applied :hand:

#1743 standin product
  src/domains/nodo-app/04_apim_apiconfig.tf
  src/domains/nodo-app/04_apim_standin_manager.tf
  src/domains/nodo-app/api_product/standin-manager/_base_policy.xml
  src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#1747 feat: DIS-42 cosmos multi AZ
  src/core/env/prod/terraform.tfvars
  src/domains/afm-common/env/weu-prod/terraform.tfvars
  src/domains/receipts-common/env/weu-prod/terraform.tfvars
  src/domains/selfcare-common/env/weu-prod/terraform.tfvars
Labels: on hold

#1754 feat: Added new evh 03 and 04
  src/next-core/00_data.tf
  src/next-core/00_network.tf
  src/next-core/05_messages.tf
  src/next-core/99_variables.tf
  src/next-core/README.md
  src/next-core/env/dev/terraform.tfvars
  src/next-core/env/prod/terraform.tfvars
  src/next-core/env/uat/terraform.tfvars
Labels: env: uat, env: prod, status: applied

#1759 chore: Switch EVH from ns2 to ns4 sender/producer UAT and DEV
  src/domains/bizevents-common/01_events.tf
  src/domains/bizevents-common/02_security.tf
  src/domains/bizevents-common/README.md
  src/domains/qi-common/01_events.tf
  src/domains/qi-common/02_security.tf
  src/domains/qi-common/README.md
Labels: env: dev, env: uat, status: applied :hand:

#1760 fix: [NOD-723] evh04 migration nodo-dei-pagamenti-cache/stand-in
  src/core/env/dev/terraform.tfvars
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
  src/domains/apiconfig-common/01_events.tf
  src/domains/apiconfig-common/02_security.tf
  src/domains/apiconfig-common/99_locals.tf
  src/domains/nodo-common/01_events.tf
  src/domains/nodo-common/02_security.tf
  src/domains/nodo-common/99_locals.tf
  src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#1739 chore(GPD): remove useless `set-query-parameter` [PAGOPA-1533]
  src/domains/gps-app/07_apim_v2_donations.tf
  src/domains/gps-app/07_apim_v2_donazione_ucraina.tf
  src/domains/gps-app/README.md
  src/domains/gps-app/api/payments-service/v1/rest/_base_policy.xml
Labels: status: applied :hand:

#1761 fix: GPD archive cosmos tables
  src/domains/gps-common/03_cosmosdb.tf
  src/domains/gps-common/99_variables.tf
  src/domains/gps-common/README.md
  src/domains/gps-common/env/weu-dev/terraform.tfvars
  src/domains/gps-common/env/weu-prod/terraform.tfvars
  src/domains/gps-common/env/weu-uat/terraform.tfvars
Labels: status: applied :hand:

#1768 [NOD-652] feat: added Alerts on last retry during VerifyKO dumping process
  src/domains/nodo-app/00_alert_ndp_verifyko.tf
  src/domains/nodo-app/README.md
Labels: env: prod, status: applied :hand:

#1763 feat: Backoffice external
  src/domains/selfcare-app/04_apim_backoffice.tf
  src/domains/selfcare-app/04_apim_backoffice_external.tf
  src/domains/selfcare-app/04_apim_selc_jwt.tf
  src/domains/selfcare-app/04_apim_selc_subkey.tf
  src/domains/selfcare-app/README.md
  src/domains/selfcare-app/env/weu-prod/terraform.tfvars
Labels: status: applied :hand:

#1778 fix: Secret cfg
  src/domains/apiconfig-common/02_security.tf
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#1780 feat: added repositories for managed-identity CD
  src/domains/nodo-common/10_github_identity.tf
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#1769 chore: Create CUP sftp localusers
  src/domains/canoneunico/.terraform.lock.hcl
  src/domains/canoneunico/03_storage_account.tf
  src/domains/canoneunico/99_main.tf
  src/domains/canoneunico/99_outputs.tf
  src/domains/canoneunico/99_variables.tf
  src/domains/canoneunico/README.md
  src/domains/canoneunico/env/dev/terraform.tfvars
Labels: env: dev, status: applied :hand:

#1775 new CUP infra [PAGOPA-1541]
  src/domains/canoneunico/03_storage_account.tf
  src/domains/canoneunico/04_eventgrid.tf
  src/domains/canoneunico/README.md
  src/domains/canoneunico/env/weu-dev/backend.ini
  src/domains/canoneunico/env/weu-dev/backend.tfvars
  src/domains/canoneunico/env/weu-dev/terraform.tfvars
  src/domains/canoneunico/env/weu-prod/backend.ini
  src/domains/canoneunico/env/weu-prod/backend.tfvars
  src/domains/canoneunico/env/weu-prod/terraform.tfvars
  src/domains/canoneunico/env/weu-uat/backend.ini
  src/domains/canoneunico/env/weu-uat/backend.tfvars
  src/domains/canoneunico/env/weu-uat/terraform.tfvars
  src/domains/canoneunico/info.txt
Labels: env: dev, env: uat, status: applied
