Repository pagopa/pagopa-infra, pull requests merged in 2024-11, with the labels that each got.

#2507 feat: [PAGOPA-2280] add datafactory objects for gec ingestion
  src/domains/observability/.terraform.lock.hcl
  src/domains/observability/04_datafactory_dataflow.tf
  src/domains/observability/04_datafactory_dataset.tf
  src/domains/observability/04_datafactory_linkedservice.tf
  src/domains/observability/04_datafactory_pipeline_gec.tf
  src/domains/observability/04_datafactory_pipeline_smo.tf
  src/domains/observability/99_main.tf
  src/domains/observability/README.md
  src/domains/observability/datafactory/pipelines/PDND_CDC_GEC_BUNDLES.json
  src/domains/observability/datafactory/pipelines/PDND_CDC_GEC_CIBUNDLES.json
  src/domains/observability/datafactory/pipelines/PDND_CDC_GEC_PAYMENTTYPES.json
  src/domains/observability/datafactory/pipelines/PDND_CDC_GEC_TOUCHPOINTS.json
Labels: status: applied :hand:

#2524 fix: [PAGOPA-2280] datafactory-ingestion-gec
  src/domains/observability/04_datafactory_dataset.tf
Labels: status: applied :hand:

#2525 feat : Add published 2 `bizevent-lap` and `bizevent-transactions` apim product
  src/domains/bizevents-app/04_apim_bizevents.tf
  src/domains/bizevents-app/04_apim_lap.tf
Labels: status: applied :hand:

#2520 config(GPD): [PAGOPA-2329] Update max_throughput
  src/domains/gps-app/README.md
  src/domains/gps-common/03_cosmosdb.tf
  src/domains/gps-common/99_variables.tf
  src/domains/gps-common/env/weu-prod/terraform.tfvars
  src/domains/gps-common/env/weu-uat/terraform.tfvars
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#2527 fix(oracle secrets): update the secret for connecting to oracle
  src/domains/bizevents-common/02_security.tf
  src/domains/bizevents-common/README.md
  src/domains/bizevents-secrets/secret/weu-dev/noedit_secret_enc.json
  src/domains/bizevents-secrets/secret/weu-uat/noedit_secret_enc.json
Labels: env: dev, env: uat, status: applied :hand:

#2496 [PPANTT-162] feat: updated gpd postgres to enable flexible server on …
  src/domains/gps-app/.terraform.lock.hcl
  src/domains/gps-common/.terraform.lock.hcl
  src/domains/gps-common/01_network.tf
  src/domains/gps-common/02_security.tf
  src/domains/gps-common/03_cosmosdb.tf
  src/domains/gps-common/03_gpd_reporting_storage_account.tf
  src/domains/gps-common/03_gpd_storage_account_archive.tf
  src/domains/gps-common/03_gpd_storage_account_sftp.tf
  src/domains/gps-common/03_postgresql_gpd.tf
  src/domains/gps-common/03_postgresql_gpd_single_server.tf
  src/domains/gps-common/03_postgresql_replica.tf
  src/domains/gps-common/10_github_identity.tf
  src/domains/gps-common/99_locals.tf
  src/domains/gps-common/99_main.tf
  src/domains/gps-common/99_variables.tf
  src/domains/gps-common/README.md
  src/domains/gps-common/env/weu-dev/terraform.tfvars
  src/domains/gps-common/env/weu-prod/terraform.tfvars
  src/domains/gps-common/env/weu-uat/terraform.tfvars
  src/domains/gps-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/gps-secret/secret/weu-prod/noedit_secret_enc.json
  src/domains/gps-secret/secret/weu-uat/noedit_secret_enc.json
  src/psql/flyway_gpd.sh
  src/psql/migrations/DEV-pagoPA/apd/V1__APD_USER.sql
  src/psql/migrations/DEV-pagoPA/apd/V2__CDC_USER.sql
Labels: env: dev, env: uat, status: applied :hand:

#2526 feat: [CHK-3530] add indexes into payment-wallets document
  src/domains/pay-wallet-common/03_cosmosdb.tf
Labels: env: dev, env: uat, env: prod

#2521 chore: [PAGOPA-2264] ndphost header in nodo
  src/core/api_product/nodo_pagamenti_api/_base_policy.xml
  src/core/api_product/nodo_pagamenti_api/decoupler/base_policy.xml.tpl
  src/core/api_product/nodo_pagamenti_api/env/dev/ndphost_header.xml
  src/core/api_product/nodo_pagamenti_api/env/prod/ndphost_header.xml
  src/core/api_product/nodo_pagamenti_api/env/uat/ndphost_header.xml
  src/core/api_product/nodo_pagamenti_api/on_error_soap_req.xml
  src/core/apim_nodo_services_01_decoupler.tf
  src/domains/nodo-app/04_apim_nodo_fragment.tf
  src/domains/nodo-app/api_product/nodo_pagamenti_api/env/dev/ndphost_header.xml
  src/domains/nodo-app/api_product/nodo_pagamenti_api/env/prod/ndphost_header.xml
  src/domains/nodo-app/api_product/nodo_pagamenti_api/env/uat/ndphost_header.xml
  src/domains/nodo-app/api_product/nodo_pagamenti_api/ndphost_header.xml.tpl
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#2531 [PAGOPA-2060] silandro flows: env variable creation for reporting
  src/domains/gps-app/.terraform.lock.hcl
  src/domains/gps-app/00_data.tf
  src/domains/gps-app/05_gpd_reporting_functions.tf
  src/domains/gps-app/README.md
Labels: status: applied :hand:

#2469 feat: Add private endpoint forwarder
  src/next-core/01_dns_private.tf
  src/next-core/06_node_forwarder.tf
  src/next-core/99_main.tf
  src/next-core/env/uat/terraform.tfvars
Labels: env: dev, env: uat, do not merge

#2534 feat: Upgrade velero module
  .pre-commit-config.yaml
  src/aks-platform/.terraform.lock.hcl
  src/aks-platform/01_network.tf
  src/aks-platform/02_aks.tf
  src/aks-platform/03_keda.tf
  src/aks-platform/05_monitoring.tf
  src/aks-platform/05_tls_checker.tf
  src/aks-platform/99_main.tf
  src/aks-platform/99_variables.tf
  src/aks-platform/README.md
  src/aks-platform/env/weu-dev/terraform.tfvars
  src/aks-platform/env/weu-prod/terraform.tfvars
  src/aks-platform/env/weu-uat/terraform.tfvars
  src/next-aks/.terraform.lock.hcl
  src/next-aks/00_key_vault.tf
  src/next-aks/01_velero.tf
  src/next-aks/99_locals.tf
  src/next-aks/99_main.tf
  src/next-aks/99_variables.tf
  src/next-aks/README.md
  src/next-aks/env/weu-dev/terraform.tfvars
  src/next-aks/env/weu-prod/terraform.tfvars
  src/next-aks/env/weu-uat/terraform.tfvars
Labels: env: dev, env: uat, env: prod

#2544 fix done
  src/domains/observability/04_datafactory_pipeline_smo.tf
  src/domains/observability/datafactory/pipelines/KPI_TNSPO.json
Labels: status: applied :hand:

#2550 feat: [PAYMCLOUD-141] Fix TLS Check deployments mismatch and enable workload identity
  src/aks-platform/.terraform.lock.hcl
  src/aks-platform/01_network.tf
  src/aks-platform/04_rbac.tf
  src/aks-platform/05_tls_checker.tf
  src/aks-platform/99_main.tf
  src/aks-platform/99_variables.tf
  src/aks-platform/README.md
  src/aks-platform/env/weu-dev/terraform.tfvars
  src/aks-platform/env/weu-prod/terraform.tfvars
  src/aks-platform/env/weu-uat/terraform.tfvars
Labels: env: dev, env: uat, env: prod, status: applied

#2551 feat: [PQ-218] add biz transaction service to assistenza apim product
  src/domains/bizevents-app/04_apim_bizevents.tf
  src/domains/bizevents-app/04_apim_lap.tf
Labels: status: applied :hand:

#2440 feat: GEC analytical_storage_enabled + Sops to afm domain
  src/domains/afm-common/00_azuread.tf
  src/domains/afm-common/02_keyvault.tf
  src/domains/afm-common/03_cosmosdb_afm.tf
  src/domains/afm-common/99_variables.tf
  src/domains/afm-common/README.md
  src/domains/afm-common/env/weu-dev/terraform.tfvars
  src/domains/afm-common/env/weu-prod/terraform.tfvars
  src/domains/afm-common/env/weu-uat/terraform.tfvars
  src/domains/afm-secrets/.terraform.lock.hcl
  src/domains/afm-secrets/99_locals.tf
  src/domains/afm-secrets/99_main.tf
  src/domains/afm-secrets/99_variables.tf
  src/domains/afm-secrets/README.md
  src/domains/afm-secrets/env/weu-dev/backend.ini
  src/domains/afm-secrets/env/weu-dev/backend.tfvars
  src/domains/afm-secrets/env/weu-dev/terraform.tfvars
  src/domains/afm-secrets/env/weu-prod/backend.ini
  src/domains/afm-secrets/env/weu-prod/backend.tfvars
  src/domains/afm-secrets/env/weu-prod/terraform.tfvars
  src/domains/afm-secrets/env/weu-uat/backend.ini
  src/domains/afm-secrets/env/weu-uat/backend.tfvars
  src/domains/afm-secrets/env/weu-uat/terraform.tfvars
  src/domains/afm-secrets/key_secret.tf
  src/domains/afm-secrets/secret/weu-dev/configs.json
  src/domains/afm-secrets/secret/weu-dev/noedit_secret_enc.json
  src/domains/afm-secrets/secret/weu-dev/secret.ini
  src/domains/afm-secrets/secret/weu-prod/configs.json
  src/domains/afm-secrets/secret/weu-prod/noedit_secret_enc.json
  src/domains/afm-secrets/secret/weu-prod/secret.ini
  src/domains/afm-secrets/secret/weu-uat/configs.json
  src/domains/afm-secrets/secret/weu-uat/noedit_secret_enc.json
  src/domains/afm-secrets/secret/weu-uat/secret.ini
  src/domains/afm-secrets/sops.sh
  src/domains/afm-secrets/terraform.sh
  src/domains/afm-secrets/terrasops.sh
Labels: status: applied :hand:

#2564 feat: Add grant 2 dev kv-biz
  src/domains/bizevents-common/02_security.tf
Labels: status: applied :hand:

#2538 feat: [PPANTT-178] Improve BO iban and CI cron job
  src/domains/selfcare-app/00_alert_backoffice.tf
  src/domains/selfcare-common/env/weu-dev/terraform.tfvars
Labels: status: applied :hand:

#2566 feat: [PAYMCLOUD-168] Refactor AKS-platform alerts configuration
  src/aks-platform/02_aks.tf
  src/aks-platform/99_locals.tf
  src/aks-platform/README.md
Labels: env: dev, env: uat, env: prod, status: applied

#2567 fix: [PAYMCLOUD-171]: Update metric configuration for monitoring pods of nodo-cron
  src/domains/nodo-app/00_monitor.tf
  src/domains/nodo-app/README.md
Labels: env: dev, env: uat, env: prod, status: applied

#2570 chore: [PAYMCLOUD-174] Update alert descriptions and configurations
  src/aks-platform/99_locals.tf
Labels: env: dev, env: uat, env: prod, status: applied

#2571 feat: wfesp dismantling in PROD PAGOPA-2374
  src/domains/nodo-app/env/weu-prod/terraform.tfvars
Labels: env: prod, status: applied :hand:

#2543 feat: [PAYMCLOUD-139] Add Opsgenie action group for production alerting
  src/aks-leonardo/00_monitor.tf
  src/aks-leonardo/03_aks_0.tf
  src/aks-leonardo/99_locals.tf
  src/aks-leonardo/README.md
Labels: env: dev, env: uat, env: prod, status: applied

#2586 chore: Pagopa 2400 bo selfcare chk alert opsgenie
  src/domains/selfcare-app/.terraform.lock.hcl
  src/domains/selfcare-app/00_alert_backoffice.tf
Labels: status: applied :hand:

#2585 [PAGOPA-2410] fix: incremented threshold on WIC errors
  src/domains/nodo-app/00_alert_wisp_dismantling.tf
  src/domains/nodo-app/README.md
Labels: status: applied :hand:

#2580 feat: [PAYMCLOUD-175] Add infra_opsgenie to action groups in alerts on next-core
  src/next-core/03_apim.tf
  src/next-core/04_appgw.tf
  src/next-core/04_appgw_integration.tf
  src/next-core/05_messages.tf
  src/next-core/06_node_forwarder.tf
  src/next-core/08_natgateway.tf
Labels: env: prod, status: applied

#2588 feat: [PQ-233] delete event excluded
  src/domains/observability/datafactory/pipelines/PDND_CDC_GEC_BUNDLES.json
  src/domains/observability/datafactory/pipelines/PDND_CDC_GEC_CIBUNDLES.json
  src/domains/observability/datafactory/pipelines/PDND_CDC_GEC_PAYMENTTYPES.json
  src/domains/observability/datafactory/pipelines/PDND_CDC_GEC_TOUCHPOINTS.json
Labels: status: applied :hand:

#2594 chore: [PAYMCLOUD-178] Update alert descriptions and parameters for better monitoring
  src/aks-leonardo/99_locals.tf
  src/next-core/03_apim.tf
  src/next-core/04_appgw.tf
  src/next-core/04_appgw_integration.tf
  src/next-core/08_natgateway.tf
Labels: env: prod, status: applied

#2598 chore: [PAGOPA-2264] secret apiconfig
  src/domains/apiconfig-common/02_security.tf
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#2599 [PAGOPA-2196] feat(aca-common): Create subkey for aca-service
  src/domains/aca-common/02_security.tf
  src/domains/aca-common/99_locals.tf
Labels: status: applied

#2582 feat: kv permissions devs and update lightbend key PAGOPA-2047
  src/domains/fdr-secret/02_security.tf
  src/domains/fdr-secret/secret/weu-prod/noedit_secret_enc.json
  src/domains/fdr-secret/secret/weu-uat/noedit_secret_enc.json
Labels: env: dev, env: uat, status: applied :hand:

#2609 chore: [PAGOPA-2362] cache export product
  src/domains/apiconfig-app/04_apim_product_apiconfig-cache_export.tf
  src/domains/apiconfig-app/99_locals.tf
Labels: env: dev, env: uat, env: prod, status: applied :hand:, apiconfig

#2620 chore: Fix payopt domain
  src/domains/paymentoptions-secrets/.terraform.lock.hcl
  src/domains/paymentoptions-secrets/secret/itn-dev/configs.json
  src/domains/paymentoptions-secrets/secret/itn-dev/noedit_secret_enc.json
  src/domains/paymentoptions-secrets/secret/itn-dev/secret.ini
  src/domains/paymentoptions-secrets/secret/itn-prod/configs.json
  src/domains/paymentoptions-secrets/secret/itn-prod/secret.ini
  src/domains/paymentoptions-secrets/secret/itn-uat/configs.json
  src/domains/paymentoptions-secrets/secret/itn-uat/noedit_secret_enc.json
  src/domains/paymentoptions-secrets/secret/itn-uat/secret.ini
Labels: status: applied :hand:
