Repository pagopa/pagopa-infra, pull requests merged in 2024-03, with the labels that each got.

#1773 chore: Switch prod ns02 ns04
  src/domains/bizevents-common/02_security.tf
  src/domains/qi-common/02_security.tf
Labels: status: applied :hand:

#1788 [PQI-66] feat: add PDND DataFactory KPI pipeline definitions
  src/domains/observability/04_datafactory_pipeline.tf
  src/domains/observability/datafactory/pipelines/PDND_KPI_DASPO.json
  src/domains/observability/datafactory/pipelines/PDND_KPI_LFDR.json
  src/domains/observability/datafactory/pipelines/PDND_KPI_LSPO.json
  src/domains/observability/datafactory/pipelines/PDND_KPI_NRFDR.json
  src/domains/observability/datafactory/pipelines/PDND_KPI_TNSPO.json
  src/domains/observability/datafactory/pipelines/PDND_KPI_TPNP.json
  src/domains/observability/datafactory/pipelines/PDND_KPI_WAFDR.json
  src/domains/observability/datafactory/pipelines/PDND_KPI_WPNFDR.json
Labels: status: applied :hand:

#1792 chore: Selfcare identity
  src/domains/selfcare-common/.terraform.lock.hcl
  src/domains/selfcare-common/02_security.tf
  src/domains/selfcare-common/10_github_identity.tf
  src/domains/selfcare-common/99_main.tf
  src/domains/selfcare-common/99_variables.tf
  src/domains/selfcare-common/README.md
  src/domains/selfcare-common/env/weu-dev/terraform.tfvars
  src/domains/selfcare-common/env/weu-prod/terraform.tfvars
  src/domains/selfcare-common/env/weu-uat/terraform.tfvars
Labels: status: applied :hand:

#1789 feat: [PAGOPA-1569] openapi for nav
  src/domains/gps-app/04_apim_gpd_core.tf
  src/domains/gps-app/api/gpd_api/debt-position-services/v1/_openapi.json.tpl
  src/domains/gps-app/api/gpd_api/debt-position-services/v2/_openapi.json.tpl
  src/domains/gps-app/api/gpd_api/v1/_openapi.json.tpl
  src/domains/gps-app/api/gpd_api/v2/_openapi.json.tpl
  src/domains/gps-app/api/pn-integration/_openapi.json.tpl
Labels: env: dev, env: uat, status: applied :hand:

#1796 PAGOPA-1495 adding api v2 afm calculator for node
  src/domains/afm-app/04_apim_afm_calculator.tf
  src/domains/afm-app/api/calculator-service/node/v2/_base_policy.xml
  src/domains/afm-app/api/calculator-service/node/v2/_openapi.json.tpl
Labels: env: dev, env: uat, status: applied :hand:

#1798 [VAS-506] Add backoffice helpdesk product
  src/domains/selfcare-app/04_apim_backoffice_external.tf
  src/domains/selfcare-app/README.md
Labels: status: applied :hand:, selfcare

#1809 Pqi 66 fix query on pdnd kpi pipeline
  src/domains/observability/datafactory/pipelines/PDND_KPI_TPNP.json
Labels: status: applied :hand:

#1791 chore: Remove `approval_required` for pagoPA BO products
  src/core/apim_nodo_services_auth_02_product.tf
  src/domains/bizevents-app/04_apim_bizevents.tf
  src/domains/fdr-app/04_apim_fdr_fase3.tf
  src/domains/gps-app/04_apim_gpd.tf
  src/domains/gps-app/04_apim_gpd_core.tf
  src/domains/gps-app/04_apim_gpd_payments.tf
  src/domains/gps-app/04_apim_gpd_reporting.tf
  src/domains/nodo-app/07_apim_v2_nodo_services_auth_02_product.tf
Labels: status: applied :hand:

#1811 chore: Stand-In Manager email in UAT
  src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
Labels: env: uat, status: applied :hand:

#1786 chore(CUP): adjust configuration [PAGOPA-1541]
  src/domains/canoneunico/02_function.tf
  src/domains/canoneunico/03_storage_account.tf
  src/domains/canoneunico/04_eventgrid.tf
  src/domains/canoneunico/env/weu-dev/terraform.tfvars
  src/domains/canoneunico/env/weu-prod/terraform.tfvars
  src/domains/canoneunico/env/weu-uat/terraform.tfvars
Labels: env: dev, env: uat, status: applied :hand:

#1816 [Selfcare Backoffice] Alert Opsgenie
  src/domains/selfcare-app/00_alert_backoffice.tf
  src/domains/selfcare-app/00_data.tf
  src/domains/selfcare-app/99_locals.tf
  src/domains/selfcare-app/README.md
Labels: status: applied :hand:, selfcare

#1805 feat: NOD-746 allineamento apim fdr fase 3
  src/domains/fdr-app/04_apim_fdr_fase3.tf
  src/domains/fdr-app/api/fdr-service-internal/v1/_openapi.json.tpl
  src/domains/fdr-app/api/fdr-service/org/v1/_openapi.json.tpl
  src/domains/fdr-app/api/fdr-service/psp/v1/_openapi.json.tpl
Labels: env: dev, status: applied :hand:

#1819 Fix backoffice alert opsgenie
  src/domains/selfcare-app/00_alert_backoffice.tf
Labels: status: applied :hand:

#1825 feat: NOD-724: add secret db nodo offline Nexi
  src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
Labels: env: dev, status: applied :hand:

#1820 Selfcare feature flags
  src/domains/selfcare-app/00_alert_backoffice.tf
  src/domains/selfcare-app/04_apim_backoffice_external.tf
  src/domains/selfcare-common/04_app_configuration_feature.tf
  src/domains/selfcare-common/README.md
Labels: env: dev, env: uat, env: prod, status: applied :hand:, selfcare

#1834 chore: Add role-ass to app-conf selfcare
  src/domains/selfcare-common/04_app_configuration_feature.tf
  src/domains/selfcare-common/README.md
Labels: status: applied :hand:

#1827 [VAS-853] feat: Split backoffice external API products
  src/domains/selfcare-app/04_apim_backoffice_external.tf
Labels: env: dev, env: uat, env: prod, status: applied :hand:, selfcare

#1835 role data owner
  src/domains/selfcare-common/04_app_configuration_feature.tf
Labels: status: applied :hand:

#1840 feat: add secret nodo offline
  src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
Labels: env: uat, env: prod, status: applied :hand:

#1843 feat: Updated postgres backup retention period
  src/domains/fdr-common/env/weu-prod/terraform.tfvars
  src/domains/gps-common/env/weu-prod/terraform.tfvars
  src/domains/nodo-common/env/weu-prod/terraform.tfvars
Labels: status: applied :hand:

#1829 feat: [NOD-726] WISP Converter storage and cosmos
  src/domains/nodo-common/01_network.tf
  src/domains/nodo-common/02_security.tf
  src/domains/nodo-common/03_cosmosdb_wisp_converter.tf
  src/domains/nodo-common/03_storage_account_wisp_converter.tf
  src/domains/nodo-common/10_github_identity.tf
  src/domains/nodo-common/99_variables.tf
  src/domains/nodo-common/env/weu-dev/terraform.tfvars
Labels: env: dev, status: applied :hand:

#1832 feat: Checkout app v3
  src/domains/checkout-app/.terraform.lock.hcl
  src/domains/checkout-app/01_monitor.tf
  src/domains/checkout-app/01_network.tf
  src/domains/checkout-app/04_apim_checkout.tf
  src/domains/checkout-app/04_apim_checkout_ec.tf
  src/domains/checkout-app/05_checkout_fe.tf
  src/domains/checkout-app/05_checkout_function.tf
  src/domains/checkout-app/05_pagopa_proxy.tf
  src/domains/checkout-app/99_locals.tf
  src/domains/checkout-app/99_main.tf
  src/domains/checkout-app/99_variables.tf
  src/domains/checkout-app/env/weu-dev/terraform.tfvars
  src/domains/checkout-app/env/weu-prod/terraform.tfvars
  src/domains/checkout-app/env/weu-uat/terraform.tfvars
Labels: status: applied :hand:

#1842 [VAS-869] feat: Introduce Payments Pull APIM and Kibana configs
  src/domains/gps-app/04_apim_payments_pull.tf
  src/domains/gps-app/README.md
  src/domains/gps-app/api_product/payments-pull/_base_policy.xml
  src/elk-monitoring/05_elastic_stack.tf
Labels: env: dev, env: uat, status: applied :hand:

#1852 [GPD Payments Pull] gh identity
  src/domains/gps-common/.terraform.lock.hcl
  src/domains/gps-common/10_github_identity.tf
  src/domains/gps-common/README.md
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#1830 feat: New critical app service zone balanced DIS-45
  src/domains/checkout-app/01_network.tf
  src/domains/checkout-app/05_pagopa_proxy_ha.tf
  src/domains/checkout-app/99_variables.tf
  src/domains/checkout-app/env/weu-dev/terraform.tfvars
  src/domains/checkout-app/env/weu-prod/terraform.tfvars
  src/domains/checkout-app/env/weu-uat/terraform.tfvars
  src/domains/shared-app/01_app_service_pdf_engine_ha.tf
  src/domains/shared-app/99_variables.tf
  src/domains/shared-app/README.md
  src/domains/shared-app/env/weu-dev/terraform.tfvars
  src/domains/shared-app/env/weu-prod/terraform.tfvars
  src/domains/shared-app/env/weu-uat/terraform.tfvars
  src/next-core/00_acr.tf
  src/next-core/00_apim.tf
  src/next-core/00_key_vault.tf
  src/next-core/00_monitor.tf
  src/next-core/00_network.tf
  src/next-core/03_tools_cae.tf
  src/next-core/06_node_forwarder.tf
  src/next-core/99_variables.tf
  src/next-core/README.md
  src/next-core/env/dev/terraform.tfvars
  src/next-core/env/prod/terraform.tfvars
  src/next-core/env/uat/terraform.tfvars
Labels: env: dev, status: applied

#1860 fix: add sondrio psp to psps list config
  src/domains/ecommerce-app/env/weu-dev/terraform.tfvars
  src/domains/ecommerce-app/env/weu-uat/terraform.tfvars
Labels: env: dev, env: uat, status: applied :hand:

#1861 chore: Upd api biz
  src/domains/bizevents-app/api/bizevents-helpdesk/v1/_openapi.json.tpl
  src/domains/bizevents-app/api/bizevents-service/v1/_openapi.json.tpl
  src/domains/bizevents-app/api/transaction-service/v1/_openapi.json.tpl
Labels: status: applied :hand:

#1859 fix(CUP): Update SFTP homeDirectory
  src/domains/canoneunico/03_storage_account.tf
Labels: status: applied :hand:

#1868 feat: add x-client-id for payment-wallet policy
  src/domains/wallet-app/api/payment-wallet/v1/_base_policy.xml.tpl
Labels: env: dev, env: uat, status: applied :hand:

#1870 chore: Add gha identity afm
  src/domains/afm-common/10_github_identity.tf
  src/domains/afm-common/README.md
Labels: status: applied :hand:

#1871 chore: Upd cup 2024 sc prod
  src/domains/canoneunico/env/weu-prod/terraform.tfvars
Labels: status: applied :hand:

#1872 chore: Pagopa 1635 remove agid 97735020584 from verificatore
  src/core/env/dev/terraform.tfvars
  src/core/env/uat/terraform.tfvars
  src/next-core/env/dev/terraform.tfvars
  src/next-core/env/uat/terraform.tfvars
Labels: status: applied :hand:

#1846 feat: CHK-2616 add new collection for wallet
  src/domains/wallet-common/03_cosmosdb.tf
Labels: env: dev, env: uat, status: applied :hand:

#1876 feat: add alerts on CUP functions
  src/domains/canoneunico/00_alert.tf
  src/domains/canoneunico/00_data.tf
  src/domains/canoneunico/02_function.tf
  src/domains/canoneunico/99_variables.tf
  src/domains/canoneunico/README.md
  src/domains/canoneunico/env/weu-prod/terraform.tfvars
  src/domains/gps-app/99_variables.tf
Labels: status: applied :hand:
