Repository pagopa/pagopa-infra, pull requests merged in 2025-08, with the labels that each got.

#3289 fix: PAGOPA-3209 Fix alert query typo
  src/domains/nodo-app/00_alert_locals.tf
Labels: status: applied :hand:

#3290 feat: Add pagopa checkposition synthetics
  src/synthetic-monitoring/monitoring_configuration.json.tpl
Labels: do not merge

#3291 PAGOPA-3209 fix: Update backend_urls filter
  src/domains/nodo-app/00_alert_nodo_pagopa.tf
Labels: env: prod

#3292 fix: filter nodo dashboard
  src/grafana-monitoring/env/weu-prod/dashboard/nodo/dashboard_node-for-ecommerce-v1.json
  src/grafana-monitoring/env/weu-prod/dashboard/nodo/dashboard_node-for-io-auth.json
  src/grafana-monitoring/env/weu-prod/dashboard/nodo/dashboard_node-for-io.json
  src/grafana-monitoring/env/weu-prod/dashboard/nodo/dashboard_node-for-psp-auth.json
  src/grafana-monitoring/env/weu-prod/dashboard/nodo/dashboard_node-for-psp.json
  src/grafana-monitoring/env/weu-prod/dashboard/nodo/dashboard_nodo-per-ecommerce-v2.json
  src/grafana-monitoring/env/weu-prod/dashboard/nodo/dashboard_nodo-per-pa-auth.json
  src/grafana-monitoring/env/weu-prod/dashboard/nodo/dashboard_nodo-per-pa.json
  src/grafana-monitoring/env/weu-prod/dashboard/nodo/dashboard_nodo-per-psp-auth.json
  src/grafana-monitoring/env/weu-prod/dashboard/nodo/dashboard_nodo-per-psp.json
Labels: status: applied :hand:

#3297 feat: PIDM-875 enrich psp kpi ingestion with total sample and total fault
  src/domains/observability/datafactory/pipelines/PDND_KPI_DASPO.json
  src/domains/observability/datafactory/pipelines/PDND_KPI_LFDR.json
  src/domains/observability/datafactory/pipelines/PDND_KPI_LSPO.json
  src/domains/observability/datafactory/pipelines/PDND_KPI_NRFDR.json
  src/domains/observability/datafactory/pipelines/PDND_KPI_TNSPO.json
  src/domains/observability/datafactory/pipelines/PDND_KPI_TPNP.json
  src/domains/observability/datafactory/pipelines/PDND_KPI_WAFDR.json
  src/domains/observability/datafactory/pipelines/PDND_KPI_WPNFDR.json
Labels: status: applied :hand:, qi-observability

#3295 fix: [PIDM-822] Fix GitHub runner bot token
  src/domains/apiconfig-app/.terraform.lock.hcl
  src/domains/apiconfig-app/07_gh_runner.tf
  src/domains/apiconfig-app/99_main.tf
  src/domains/fdr-app/.terraform.lock.hcl
  src/domains/fdr-app/07_gh_runner.tf
  src/domains/fdr-app/99_main.tf
Labels: status: applied :hand:, fdr, apiconfig
