Repository pagopa/pagopa-infra, pull requests merged in 2025-06, with the labels that each got.

#3074 feat: Add UAT crusc8 infra
  src/domains/cruscotto-app/04_apim.tf
  src/domains/cruscotto-app/env/itn-uat/terraform.tfvars
  src/domains/cruscotto-common/env/itn-dev/terraform.tfvars
  src/domains/cruscotto-common/env/itn-uat/terraform.tfvars
  src/domains/cruscotto-secrets/env/itn-uat/terraform.tfvars
  src/domains/cruscotto-secrets/secret/itn-uat/configs.json
  src/domains/cruscotto-secrets/secret/itn-uat/noedit_secret_enc.json
Labels: env: uat, status: applied :hand:

#3082 [PAGOPA] fix: Patch alert to avoid FP
  src/domains/gps-app/00_alert_gpd_core.tf
Labels: status: applied :hand:

#3084 chore: Add smo grp 2 kv-qi
  src/domains/qi-common/00_azuread.tf
  src/domains/qi-common/02_security.tf
  src/domains/qi-common/README.md
Labels: status: applied :hand:

#3079 chore: [PAGOPA-3082] Added pagopa-decoupler repo
  src/domains/nodo-app/07_gh_runner.tf
  src/domains/nodo-common/10_github_identity.tf
Labels: env: dev, status: applied :hand:

#3090 chore: Fix typo nodo-app
  src/domains/nodo-app/07_gh_runner.tf
Labels: status: applied :hand:

#3093 feat: [PAYMCLOUD-430] Removed prod elk instance
  src/elk-monitoring/.terraform.lock.hcl
  src/elk-monitoring/00_azuread.tf
  src/elk-monitoring/00_monitor.tf
  src/elk-monitoring/00_network.tf
  src/elk-monitoring/00_secret.tf
  src/elk-monitoring/01_aks.tf
  src/elk-monitoring/02_namespace.tf
  src/elk-monitoring/02_security.tf
  src/elk-monitoring/03_ingress.tf
  src/elk-monitoring/05_ecommerce_namespace.tf
  src/elk-monitoring/05_elastic_stack.tf
  src/elk-monitoring/05_kibana_dashboard_ndp.tf
  src/elk-monitoring/05_kibana_dashboard_pagopa.tf
  src/elk-monitoring/05_kibana_dashboard_pagopaecommerce.tf
  src/elk-monitoring/05_kibana_dashboard_pagopafdr.tf
  src/elk-monitoring/05_kibana_dashboard_pagopaprintit.tf
  src/elk-monitoring/05_kibana_dashboard_pagopawallet.tf
  src/elk-monitoring/05_kibana_log_default.tf
  src/elk-monitoring/05_kibana_log_ndp.tf
  src/elk-monitoring/05_kibana_log_ndp_stand_in_manager.tf
  src/elk-monitoring/05_kibana_log_ndp_tech_support.tf
  src/elk-monitoring/05_kibana_log_pagopa_general.tf
  src/elk-monitoring/05_kibana_log_pagopa_gpd.tf
  src/elk-monitoring/05_kibana_log_pagopafdr.tf
  src/elk-monitoring/05_kibana_log_pagopaprintit.tf
  src/elk-monitoring/05_paywallet_namespace.tf
  src/elk-monitoring/05_storage.tf
  src/elk-monitoring/06_aks_middleware_tools.tf
  src/elk-monitoring/99_main.tf
  src/elk-monitoring/README.md
  src/next-core/00_key_vault.tf
  src/next-core/01_dns_public.tf
  src/next-core/04_appgw.tf
  src/next-core/99_variables.tf
  src/next-core/README.md
  src/next-core/env/dev/terraform.tfvars
  src/next-core/env/prod/terraform.tfvars
  src/next-core/env/uat/terraform.tfvars
Labels: env: prod, status: applied :hand:

#3067 feat: Add pagopa-itn-github-runner-cae-italy
  src/domains/shared-app/env/weu-uat/terraform.tfvars
  src/domains/shared-common/01_github_runner_itn.tf
  src/domains/shared-common/99_variables.tf
  src/domains/shared-common/README.md
  src/domains/shared-common/env/weu-dev/terraform.tfvars
  src/domains/shared-common/env/weu-prod/terraform.tfvars
  src/domains/shared-common/env/weu-uat/terraform.tfvars
Labels: env: dev, env: uat, status: applied :hand:

#3111 feat: Dns private link postgres to italy
  src/core-itn/00_dns_private.tf
  src/core-itn/02_dns_private_link.tf
  src/core-itn/README.md
  src/domains/cruscotto-secrets/secret/itn-uat/noedit_secret_enc.json
  src/domains/shared-common/README.md
Labels: status: applied :hand:

#3113 chore: Upd uat crusc8 secrets
  src/domains/cruscotto-secrets/gen_jwt_key.sh
  src/domains/cruscotto-secrets/secret/itn-uat/noedit_secret_enc.json
Labels: status: applied :hand:

#3115 feat: [PAGOPA-3105] [SHARED] Add anonymizer sub key to shared keyvault
  src/domains/shared-common/01_github_runner_itn.tf
  src/domains/shared-common/02_security.tf
  src/domains/shared-common/03_cosmosdb_authorizer.tf
  src/domains/shared-common/99_locals.tf
  src/domains/shared-common/README.md
Labels: status: applied :hand:, shared

#2967 feat: add postgresql dashboard to terraform
  src/domains/gps-common/03_postgresql_gpd_db.tf
  src/domains/gps-common/README.md
  src/domains/gps-common/dashboards/debt-positions-postgres-db-usage.json
Labels: status: needs review

#3086 chore: Decoupler IPG-154
  src/core/api_product/nodo_pagamenti_api/decoupler/cfg/dev/decoupler-configuration.xml
  src/core/api_product/nodo_pagamenti_api/decoupler/cfg/dev/decoupler_configuration.json
  src/core/api_product/nodo_pagamenti_api/decoupler/cfg/uat/decoupler-configuration.xml
  src/core/api_product/nodo_pagamenti_api/decoupler/cfg/uat/decoupler_configuration.json
  src/core/api_product/nodo_pagamenti_api/decoupler/decoupler-activate-inbound.xml
  src/core/api_product/nodo_pagamenti_api/decoupler/decoupler-algorithm.xml
  src/core/api_product/nodo_pagamenti_api/on_error_soap_req.xml
  src/core/apim_nodo_services_auth_02_product.tf
  src/next-core/03_apim_named_values.tf
  src/next-core/env/dev/terraform.tfvars
  src/next-core/env/uat/terraform.tfvars
Labels: env: dev, env: uat, status: applied :hand:

#3098 chore: create new storage account for MBD PAGOPA-3018
  src/domains/nodo-common/02_security.tf
  src/domains/nodo-common/03_storage_account_mbd.tf
  src/domains/nodo-common/99_variables.tf
  src/domains/nodo-common/README.md
  src/domains/nodo-common/env/weu-dev/terraform.tfvars
  src/domains/nodo-common/env/weu-prod/terraform.tfvars
  src/domains/nodo-common/env/weu-uat/terraform.tfvars
  src/domains/nodo-secret/storageaccount.tf
Labels: status: applied :hand:

#3110 feat: Change pagopa wisp conv path 4 WL
  src/domains/nodo-app/04_apim_wisp_dismantling_policies.tf
  src/domains/shared-app/04_apim_statuspage.tf
Labels: status: applied :hand:

#3116 feat(openapi): [CHK-4200] add event queues apis to commands-service
  src/domains/ecommerce-app/api/ecommerce-helpdesk-commands-api/v1/_openapi.json.tpl
Labels: env: dev, status: ready to apply, status: needs review

#3153 feat: Update rmbd-sftp-pem-key
  src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
Labels: env: dev, env: uat, status: applied :hand:

#3136 chore: [PAGOPA-3101] Switch prod NDP PostgreSQL [IPG-154]
  src/core/api_product/nodo_pagamenti_api/decoupler/cfg/prod/decoupler-configuration.xml
  src/core/api_product/nodo_pagamenti_api/decoupler/cfg/prod/decoupler_configuration.json
  src/core/env/prod/terraform.tfvars
Labels: nodo

#3164 feat: Add aws ses cfg cruscotto
  src/domains/cruscotto-secrets/secret/itn-dev/noedit_secret_enc.json
  src/domains/cruscotto-secrets/secret/itn-prod/noedit_secret_enc.json
  src/domains/cruscotto-secrets/secret/itn-uat/noedit_secret_enc.json
Labels: status: applied :hand:

#3165 chore: Apiconfig secret - slack channel
  src/domains/apiconfig-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/apiconfig-secret/secret/weu-prod/noedit_secret_enc.json
  src/domains/apiconfig-secret/secret/weu-uat/noedit_secret_enc.json
Labels: status: applied :hand:

#3180 chore: Rollback Nexi postgres to 2%
  src/core/api_product/nodo_pagamenti_api/decoupler/cfg/prod/decoupler-configuration.xml
  src/core/api_product/nodo_pagamenti_api/decoupler/cfg/prod/decoupler_configuration.json
Labels: env: prod, status: applied :hand:, nodo

#3182 chore: Fix verificatore policy
  src/core/api/nodopagamenti_api/nodeForPsp/v1/activate_nm3.xml
  src/core/api/nodopagamenti_api/nodeForPsp/v2/activate_nm3.xml
  src/core/api_product/nodo_pagamenti_api/decoupler/base_policy.xml.tpl
  src/core/api_product/nodo_pagamenti_api/decoupler/cfg/prod/decoupler-configuration.xml
  src/core/api_product/nodo_pagamenti_api/decoupler/cfg/prod/decoupler_configuration.json
  src/core/api_product/nodo_pagamenti_api/decoupler/cfg/uat/decoupler-configuration.xml
  src/core/api_product/nodo_pagamenti_api/decoupler/cfg/uat/decoupler_configuration.json
  src/core/api_product/nodo_pagamenti_api/decoupler/decoupler-activate-outbound.xml
  src/core/api_product/nodo_pagamenti_api/decoupler/decoupler-algorithm.xml
  src/next-core/02_redis.tf
Labels: env: prod, status: applied :hand:

#3198 fix: change-bearer-token
  src/domains/qi-secrets/secret/weu-dev/noedit_secret_enc.json
  src/domains/qi-secrets/secret/weu-prod/noedit_secret_enc.json
  src/domains/qi-secrets/secret/weu-uat/noedit_secret_enc.json
Labels: env: dev, env: uat, env: prod, status: applied

#3202 feat: Update-azure-devops-token-secret
  src/domains/receipts-secrets/secret/weu-dev/noedit_secret_enc.json
  src/domains/receipts-secrets/secret/weu-prod/noedit_secret_enc.json
  src/domains/receipts-secrets/secret/weu-uat/noedit_secret_enc.json
Labels: status: applied :hand:

#3201 chore: update marketplace openapi PIDM-709
  src/domains/afm-app/api/marketplace-service/v1/_openapi.json.tpl
Labels: status: applied :hand:

#3193 chore: [PAGOPA-3156] APIM cache management
  src/domains/nodo-app/.terraform.lock.hcl
  src/domains/nodo-app/04_apim_cfg_for_node.tf
  src/domains/nodo-app/99_main.tf
  src/domains/nodo-app/README.md
  src/domains/nodo-app/api/internal-service/v1/apim_cache_base_policy.xml
  src/domains/nodo-app/api/internal-service/v1/apim_cache_openapi.json
  src/domains/nodo-app/api/internal-service/v1/delete_cache_v1_policy.xml
  src/domains/nodo-app/api/internal-service/v1/get_cache_v1_policy.xml
  src/domains/nodo-app/api/internal-service/v1/set_cache_v1_policy.xml
Labels: env: dev, env: uat, env: prod, status: applied :hand:
