Repository pagopa/pagopa-infra, pull requests merged in 2025-01, with the labels that each got.

#2701 feat: [PAYMCLOUD-189] Deploy kubernetes event exporter in aks-prod
  src/aks-platform/05_monitoring.tf
  src/aks-platform/README.md
Labels: env: prod, status: applied

#2706 chore(printit): Alert revision
  src/domains/printit-app/00_alerts.tf
  src/domains/printit-app/README.md
Labels: status: applied :hand:, printit

#2707 feat: Add perf test key MBD
  src/domains/ebollo-app/05_subkey.tf
  src/domains/ebollo-app/06_keyvault.tf
Labels: status: applied :hand:

#2709 fix: Agent-elk-itn-leonardo
  src/aks-leonardo/03_monitoring.tf
Labels: status: applied :hand:

#2711 fix: Storage data-cold-nodes elk
  src/elk-monitoring/env/weu-prod/terraform.tfvars
Labels: status: applied :hand:

#2716 add new holidays to the calendar
  src/domains/observability/datafactory/pipelines/KPI_FDR_IMPORT_ESITI.json
Labels: status: applied :hand:

#2719 feat: Add slack-webhook-url ebollo
  src/domains/ebollo-secrets/secret/itn-dev/noedit_secret_enc.json
  src/domains/ebollo-secrets/secret/itn-prod/noedit_secret_enc.json
  src/domains/ebollo-secrets/secret/itn-uat/noedit_secret_enc.json
Labels: status: applied :hand:

#2714 fix(on-error): [MAIN-14] fix content-type
  src/core/api_product/nodo_pagamenti_api/on_error_soap_req.xml
Labels: status: applied :hand:

#2723 fix: [MAIN-29] fix gpd product for integration tests
  src/domains/ebollo-app/00_data.tf
  src/domains/ebollo-app/05_subkey.tf
  src/domains/ebollo-app/06_keyvault.tf
  src/domains/gps-app/04_apim_payments_pull.tf
Labels: status: applied :hand:

#2727 fix: IP filter product-policy gps-mbd serivice
  src/domains/gps-app/04_apim_gps_spontaneus_payments_services.tf
Labels: status: applied :hand:

#2681 feat: [PAGOPA-2479] - GPD v3 api
  src/domains/gps-app/04_apim_gpd.tf
  src/domains/gps-app/04_apim_gpd_core.tf
  src/domains/gps-app/README.md
  src/domains/gps-app/api/gpd_api/debt-position-services/_base_policy.xml
  src/domains/gps-app/api/gpd_api/debt-position-services/v3/_openapi.json.tpl
Labels: status: applied :hand:, gpd

#2729 feat(fdr-common): enable Alerts for FDR NDP (fase 1)
  src/domains/fdr-app/00_alert_fdr_fase1.tf
  src/domains/fdr-app/README.md
  src/domains/fdr-common/03_postgresql_replica.tf
  src/domains/fdr-common/README.md
  src/domains/fdr-common/env/weu-prod/terraform.tfvars
Labels: status: applied :hand:, fdr

#2740 chore: [PAGOPA-2582] Added mock pm to UAT
  src/domains/nodo-app/04_apim_mock_pm.tf
  src/domains/nodo-app/api/mock-pm-service/v1/_base_policy.xml
Labels: env: uat, status: applied :hand:

#2747 feat(FdR): [PAGOPA-2597] Replace history storage accounts with mongo collections
  src/domains/fdr-common/03_cosmos_mongodb_fdr_re.tf
  src/domains/fdr-common/README.md
Labels: env: dev, status: applied :hand:

#2755 feat: Add secrets service now QI
  src/domains/qi-app/.terraform.lock.hcl
  src/domains/qi-app/02_security.tf
Labels: status: applied :hand:
