Repository pagopa/pagopa-infra, pull requests merged in 2025-10, with the labels that each got.

#3391 chore: [PIDM-1039] Increase PDF Engine (JAVA) autoscaling
  src/domains/shared-app/01_app_service_pdf_engine.tf
Labels: status: applied :hand:

#3365 chore: add v2 api for gpd-upload PAGOPA-3285
  src/domains/aca-app/04_apim_aca_upload.tf
  src/domains/aca-app/04_apim_gpd_for_aca.tf
  src/domains/aca-app/99_locals.tf
  src/domains/aca-app/README.md
  src/domains/gps-app/04_apim_gpd_upload.tf
  src/domains/gps-app/README.md
  src/domains/gps-app/api/gpd-upload-service/v1/_openapi_v1.json
  src/domains/gps-app/api/gpd-upload-service/v2/_base_policy.xml
  src/domains/gps-app/api/gpd-upload-service/v2/_openapi_v2.json
Labels: env: dev, env: uat, status: applied :hand:

#3375 feat: New apiconfig cache external product
  src/domains/apiconfig-app/00_alert_apiconfig_cache.tf
  src/domains/apiconfig-app/04_apim_api_apiconfig-cache-external.tf
  src/domains/apiconfig-app/04_apim_api_apiconfig-cache-node.tf
  src/domains/apiconfig-app/04_apim_api_apiconfig-cache-replica-node.tf
  src/domains/apiconfig-app/04_apim_product_apiconfig-cache.tf
  src/domains/apiconfig-app/05_subkey.tf
  src/domains/apiconfig-app/README.md
  src/domains/apiconfig-app/api/apiconfig-cache/external/_base_policy.xml
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#3400 feat: Add `pagopa-standin-api-key-value` 4 crusc8
  src/domains/cruscotto-common/02_security.tf
Labels: status: applied :hand:

#3403 chore: [PIDM-875] kpi psp pipeline change date range
  src/domains/observability/datafactory/pipelines/PDND_KPI_DASPO.json
  src/domains/observability/datafactory/pipelines/PDND_KPI_LFDR.json
  src/domains/observability/datafactory/pipelines/PDND_KPI_LSPO.json
  src/domains/observability/datafactory/pipelines/PDND_KPI_NRFDR.json
  src/domains/observability/datafactory/pipelines/PDND_KPI_TNSPO.json
  src/domains/observability/datafactory/pipelines/PDND_KPI_TPNP.json
  src/domains/observability/datafactory/pipelines/PDND_KPI_WAFDR.json
  src/domains/observability/datafactory/pipelines/PDND_KPI_WPNFDR.json
Labels: status: applied :hand:, qi-observability
