Repository pagopa/pagopa-infra, pull requests merged in 2025-05, with the labels that each got.

#2998 chore: [PAGOPA-3000] fdr legacy - added nodoInviaFlussoRendicontazione to fdr-legacy product
  src/core/99_variables.tf
  src/domains/fdr-app/04_apim_fdr_legacy_nodo_nexi.tf
  src/domains/fdr-app/README.md
  src/domains/fdr-app/api/fdr-legacy/v1/NodoPerPa.wsdl
  src/domains/fdr-app/api/fdr-legacy/v1/NodoPerPsp.wsdl
  src/domains/fdr-app/api/fdr-legacy/v1/_base_policy.xml
  src/domains/fdr-app/api_product/fdr-legacy/_base_policy.xml
  src/domains/fdr-app/api_product/nodoPerPa/_base_policy.xml
  src/next-core/99_variables.tf
  src/next-core/README.md
  src/next-core/env/uat/terraform.tfvars
Labels: status: applied :hand:, fdr

#3009 feat: PIDM-450 add alert and update openapi
  src/domains/gps-app/00_alert_gpd_core.tf
  src/domains/gps-app/00_monitor.tf
  src/domains/gps-app/05_debezium_connect.tf
  src/domains/gps-app/99_locals.tf
  src/domains/gps-app/README.md
  src/domains/gps-app/api/gpd_api/v1/_openapi.json.tpl
  src/domains/gps-app/api/gpd_api/v2/_openapi.json.tpl
Labels: status: applied :hand:, gpd

#3026 chore: Remove-subkey-from-cruscotto-prod
  src/domains/cruscotto-app/04_apim.tf
Labels: status: applied :hand:

#3008 feat(new-api): [CHK-4107] add get transaction outcome api
  src/domains/ecommerce-app/04_apim_ecommerce_checkout.tf
  src/domains/ecommerce-app/04_apim_ecommerce_webview.tf
  src/domains/ecommerce-app/README.md
  src/domains/ecommerce-app/api/ecommerce-checkout/v1/_base_policy.xml.tpl
  src/domains/ecommerce-app/api/ecommerce-checkout/v1/_openapi.json.tpl
  src/domains/ecommerce-app/api/ecommerce-io/v2/_outcome_info.xml.tpl
  src/domains/ecommerce-app/api/ecommerce-transactions-service/v1/_openapi.json.tpl
  src/domains/ecommerce-app/api/ecommerce-webview/v2/_openapi.json.tpl
Labels: env: uat, status: ready to apply, status: needs review

#3029 fix: [PAGOPA-3049] DEV Data Explorer secrets
  src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
Labels: env: dev, status: applied :hand:

#3032 feat: Enable auto mitigation for forwarder alerts
  src/next-core/06_node_forwarder.tf
Labels: env: prod, status: applied

#3028 chore: [PAGOPA-2837] Nodo secrets
  src/domains/nodo-common/01_events.tf
  src/domains/nodo-common/01_network.tf
  src/domains/nodo-common/02_security.tf
  src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
  src/next-core/env/dev/terraform.tfvars
  src/next-core/env/prod/terraform.tfvars
  src/next-core/env/uat/terraform.tfvars
Labels: status: applied :hand:, nodo

#3030 feat: [PAYMCLOUD-396] Upgrade module references with minimal_tls_version TLS12
  src/domains/nodo-common/02_security.tf
  src/domains/nodo-common/README.md
  src/domains/shared-common/.terraform.lock.hcl
  src/domains/shared-common/03_cosmosdb_authorizer.tf
  src/domains/shared-common/03_cosmosdb_iuvgenerator.tf
  src/domains/shared-common/README.md
Labels: env: dev, status: partially applied

#3021 chore: [PAGOPA-3035] eventhub namespace
  src/domains/gps-common/.terraform.lock.hcl
  src/domains/gps-common/00_data.tf
  src/domains/gps-common/00_monitor.tf
  src/domains/gps-common/01_network.tf
  src/domains/gps-common/05_rtp_eventhub.tf
  src/domains/gps-common/99_locals.tf
  src/domains/gps-common/99_main.tf
  src/domains/gps-common/99_variables.tf
  src/domains/gps-common/env/weu-dev/terraform.tfvars
  src/domains/gps-common/env/weu-prod/terraform.tfvars
  src/domains/gps-common/env/weu-uat/terraform.tfvars
Labels: status: applied :hand:, rtp

#3023 chore: [PAGOPA-3031] (GPD): Update PayPaymentOptionModel model
  src/domains/gps-app/api/gpd_api/v1/_openapi.json.tpl
  src/domains/gps-app/api/gpd_api/v2/_openapi.json.tpl
Labels: status: applied :hand:, gpd

#3036 chore: Upd secret dataexp
  src/domains/gps-common/05_rtp_eventhub.tf
  src/domains/gps-common/99_locals.tf
  src/domains/gps-common/README.md
  src/domains/gps-common/env/weu-prod/terraform.tfvars
  src/domains/gps-common/env/weu-uat/terraform.tfvars
  src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
Labels: status: applied :hand:, nodo

#3031 chore: Swap appgw certificate@dev
  src/next-core-secrets/secret/prod/noedit_secret_enc.json
  src/next-core/env/dev/terraform.tfvars
  src/synthetic-monitoring/00_data.tf
  src/synthetic-monitoring/01_analytics_workspace.tf
  src/synthetic-monitoring/README.md
Labels: env: dev, status: applied

#3019 chore: adding wl identity apiconfig PIDM-487
  src/domains/apiconfig-app/.terraform.lock.hcl
  src/domains/apiconfig-app/02_namespace.tf
  src/domains/apiconfig-app/05_aks_middleware_tools.tf
  src/domains/apiconfig-app/07_gh_runner.tf
  src/domains/apiconfig-app/99_main.tf
  src/domains/apiconfig-app/README.md
  src/domains/apiconfig-common/.terraform.lock.hcl
  src/domains/apiconfig-common/02_security.tf
  src/domains/apiconfig-common/03_storage_account.tf
  src/domains/apiconfig-common/10_github_identity.tf
  src/domains/apiconfig-common/99_main.tf
  src/domains/apiconfig-common/README.md
Labels: status: applied :hand:, apiconfig

#3012 [PIDM-486] feat: add WL identity ( afm )
  src/domains/afm-app/.terraform.lock.hcl
  src/domains/afm-app/02_namespace.tf
  src/domains/afm-app/05_aks_middleware_tools.tf
  src/domains/afm-app/99_main.tf
  src/domains/afm-app/README.md
  src/domains/afm-common/.terraform.lock.hcl
  src/domains/afm-common/02_keyvault.tf
  src/domains/afm-common/03_cosmosdb_afm.tf
  src/domains/afm-common/03_storage_account_afm.tf
  src/domains/afm-common/10_github_identity.tf
  src/domains/afm-common/99_locals.tf
  src/domains/afm-common/99_main.tf
  src/domains/afm-common/README.md
Labels: status: applied :hand:

#3044 chore: Add smo opsgenie grp 2 newconnout (aka) forwarder, ndp and gps domains
  src/domains/gps-app/00_alert_gpd_core.tf
  src/domains/gps-app/00_alert_gpd_ingestion.tf
  src/domains/gps-app/00_alert_gpd_payments.tf
  src/domains/gps-app/00_alert_gpd_payments_pull.tf
  src/domains/gps-app/00_alert_gpd_upload.tf
  src/domains/gps-app/00_monitor.tf
  src/domains/gps-app/README.md
  src/domains/nodo-app/00_alert_faultcode.tf
  src/domains/nodo-app/00_monitor.tf
  src/domains/nodo-app/README.md
  src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json
  src/next-core-secrets/secret/prod/noedit_secret_enc.json
  src/next-core/00_key_vault.tf
  src/next-core/02_monitor.tf
  src/next-core/06_node_forwarder.tf
  src/next-core/README.md
Labels: status: applied :hand:, smo-alerts

#3052 chore: Added secret to nodo
  src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json
Labels: env: prod, status: applied :hand:

#3055 chore: Add db-fdr3-password-read secret
  src/domains/fdr-secret/secret/weu-prod/noedit_secret_enc.json
Labels: status: applied :hand:

#3056 chore: Add db-fdr3-password-read secret uat
  src/domains/fdr-secret/secret/weu-uat/noedit_secret_enc.json
Labels: status: applied :hand:

#3060 chore: Add dev db-fdr3-password-read
  src/domains/fdr-secret/secret/weu-dev/noedit_secret_enc.json
Labels: status: applied :hand:

#3057 feat: Application Gateway & APIM certificate -stable
  src/next-core-secrets/secret/dev/noedit_secret_enc.json
  src/next-core-secrets/secret/prod/noedit_secret_enc.json
  src/next-core-secrets/secret/uat/noedit_secret_enc.json
  src/next-core/04_appgw_integration.tf
  src/next-core/99_variables.tf
  src/next-core/README.md
  src/next-core/env/uat/terraform.tfvars
  src/synthetic-monitoring/01_analytics_workspace.tf
Labels: env: uat, status: applied :hand:

#3054 fix: [PAGOPA-3078] PostgreSQL CDC DEV/UAT
  src/domains/gps-app/env/weu-dev/terraform.tfvars
  src/domains/gps-common/env/weu-dev/terraform.tfvars
  src/domains/gps-common/env/weu-prod/terraform.tfvars
  src/domains/gps-common/env/weu-uat/terraform.tfvars
Labels: env: dev, env: uat, status: applied

#3013 chore: [PIDM-492] [GPS] Add repos to github identity list
  src/domains/gps-app/07_gh_runner.tf
  src/domains/gps-common/10_github_identity.tf
Labels: status: applied :hand:, gpd

#2640 feat: [PAGOPA-3078] add healthcheck job for Debezium connector
  src/domains/gps-app/04_apim_gpd_debezium.tf
  src/domains/gps-app/05_debezium_connect.tf
  src/domains/gps-app/api/debezium-api/v1/_base_policy.xml
  src/domains/gps-app/api/debezium-api/v1/_openapi.json.tpl
  src/domains/gps-app/api_product/debezium-api/_base_policy.xml
  src/domains/gps-app/yaml/debezium-health-checker-cron.yaml
  src/domains/gps-app/yaml/debezium-ingress.yaml
  src/domains/gps-app/yaml/debezium-network-policy.yaml
  src/domains/gps-app/yaml/healthchecker-config-map.yaml
  src/synthetic-monitoring/00_data.tf
  src/synthetic-monitoring/02_monitoring.tf
  src/synthetic-monitoring/99_locals.tf
  src/synthetic-monitoring/README.md
  src/synthetic-monitoring/monitoring_configuration.json.tpl
Labels: env: dev, env: uat, status: applied :hand:

#3065 chore: Upd ru receipts and crusc8 cdn default index
  src/domains/cruscotto-app/06_cruscotto-fe.tf
  src/domains/receipts-common/env/weu-prod/terraform.tfvars
Labels: status: applied :hand:

#3068 chore: Fix synthetic-monitoring 4 debeziumConnectorPostgres
  src/synthetic-monitoring/monitoring_configuration.json.tpl
Labels: status: applied :hand:

#3069 feat: Add action group cert diff
  src/next-core-secrets/secret/dev/noedit_secret_enc.json
  src/next-core-secrets/secret/prod/noedit_secret_enc.json
  src/next-core-secrets/secret/uat/noedit_secret_enc.json
  src/next-core/00_key_vault.tf
  src/next-core/02_monitor.tf
  src/next-core/README.md
  src/synthetic-monitoring/01_analytics_workspace.tf
  src/synthetic-monitoring/README.md
Labels: status: applied :hand:
