Repository pagopa/pagopa-infra, pull requests merged in 2025-07, with the labels that each got.

#3141 [PAGOPA-3110] feat: Add infra configuration for ACA-Payments
  src/domains/gps-common/00_data.tf
  src/domains/gps-common/02_security.tf
  src/domains/gps-common/README.md
  src/next-core/env/dev/terraform.tfvars
  src/next-core/env/prod/terraform.tfvars
  src/next-core/env/uat/terraform.tfvars
Labels: status: applied

#3207 chore: [PAGOPA-3163] add RTP integration tests secrets
  src/domains/gps-app/.terraform.lock.hcl
  src/domains/gps-app/07_gh_runner.tf
  src/domains/gps-app/99_main.tf
  src/domains/gps-app/README.md
  src/domains/gps-common/02_security.tf
  src/domains/gps-common/README.md
  src/domains/gps-common/env/weu-dev/terraform.tfvars
  src/domains/gps-common/env/weu-uat/terraform.tfvars
  src/domains/gps-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/gps-secret/secret/weu-prod/noedit_secret_enc.json
  src/domains/gps-secret/secret/weu-uat/noedit_secret_enc.json
Labels: status: applied :hand:

#3224 fix: Removing two CIs from Decoupler configuration
  src/core/api_product/nodo_pagamenti_api/decoupler/cfg/prod/decoupler-configuration.xml
  src/core/api_product/nodo_pagamenti_api/decoupler/cfg/prod/decoupler_configuration.json
Labels: status: applied :hand:

#3225 feat(wallet): use afm calculate fees multi api
  src/domains/pay-wallet-app/api/webview-payment-wallet/v1/get_psps_policy.xml.tpl
Labels: env: dev, env: uat, status: applied :hand:

#3210 chore: adding new collections on cosmos afm PAGOPA-3130
  src/domains/afm-app/api/calculator-service/v2/_openapi.json.tpl
  src/domains/afm-common/.terraform.lock.hcl
  src/domains/afm-common/03_cosmosdb_afm.tf
Labels: env: dev, status: applied :hand:

#3235 chore: update openapi gmp
  src/domains/afm-app/README.md
  src/domains/afm-app/api/calculator-service/v1/_openapi.json.tpl
  src/domains/afm-app/api/calculator-service/v1/prod/_openapi.json.tpl
  src/domains/afm-app/api/calculator-service/v2/_openapi.json.tpl
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#3242 feat: Add payments cloud github token secrets and updated cron grom workflow
  src/domains/nodo-app/00_monitor.tf
  src/next-core-secrets/secret/dev/noedit_secret_enc.json
  src/next-core-secrets/secret/prod/noedit_secret_enc.json
  src/next-core-secrets/secret/uat/noedit_secret_enc.json
Labels: env: dev, status: applied

#3248 feat: [PIDM-809] Including PAT CD token for domain printit
  src/domains/printit-secrets/.terraform.lock.hcl
  src/domains/printit-secrets/secret/itn-dev/noedit_secret_enc.json
  src/domains/printit-secrets/secret/itn-prod/noedit_secret_enc.json
  src/domains/printit-secrets/secret/itn-uat/noedit_secret_enc.json
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#3255 feat : PIDM-833 biz-service-identifier- `NDP004PROD` MITIGATION 😏
  src/domains/bizevents-app/api/lap-service/v1/_base_policy-jwt.xml
  src/domains/bizevents-app/api/lap-service/v1/_base_policy.xml
Labels: status: applied :hand:

#3258 fix: [PIDM-834] Defining mitigation for sFTP's FdR if not found on default Nodo instance
  src/domains/fdr-app/api/fdr-fase1/nodoPerPa/v1/fdr_pagopa_nodoChiediFlussoRendicontazione.xml.tpl
  src/domains/fdr-app/api/fdr-legacy/v1/_base_policy.xml
Labels: fdr

#3251 chore: [PAGOPA-3134] Add secrets for GMP integration tests
  src/domains/afm-app/02_security.tf
Labels: env: dev, env: uat, status: applied :hand:

#3275 chore(pagopa-proxy): CHK-4337 bye bye pagopaproxy
  src/domains/checkout-app/01_network.tf
  src/domains/checkout-app/04_apim_checkout.tf
  src/domains/checkout-app/05_checkout_function.tf
  src/domains/checkout-app/05_pagopa_proxy.tf
  src/domains/checkout-app/05_pagopa_proxy_ha.tf
  src/domains/checkout-app/99_variables.tf
  src/domains/checkout-app/env/weu-dev/terraform.tfvars
  src/domains/checkout-app/env/weu-prod/terraform.tfvars
  src/domains/checkout-app/env/weu-uat/terraform.tfvars
  src/domains/checkout-common/01_network.tf
  src/domains/checkout-common/03_redis.tf
Labels: env: dev, env: uat, status: partially applied

#3277 chore: [PIDM-841] update wallet session token validation context root
  src/domains/shared-app/api/session-wallet/v1/_base_policy.xml.tpl
Labels: env: dev, env: uat, env: prod, status: applied
