Repository pagopa/pagopa-infra, pull requests merged in 2025-03, with the labels that each got.

#2845 feat: [PAGOPA-2704] Updating PSP list in production environment for roll-out first phase
  src/domains/fdr-app/env/weu-prod/terraform.tfvars
Labels: env: prod, status: applied :hand:, fdr

#2849 fix: [PAGOPA] (fdr) Register for validation error-handling
  src/domains/fdr-app/04_apim_fdr_fase1_auth.tf
  src/domains/fdr-app/README.md
  src/domains/fdr-app/api/fdr-fase1/nodoPerPsp/v1/fdr_nodoinvia_flussorendicontazione_flow.xml
  src/domains/fdr-app/env/weu-prod/terraform.tfvars
Labels: env: dev, env: uat, env: prod, status: applied :hand:, fdr

#2844 fix: [PAGOPA-2703] Minor fix on FDR1 dashboard
  src/domains/fdr-app/dashboard/dashboard-apim-fdr.tpl
Labels: env: prod, status: applied :hand:

#2619 fix: [PQ-242] fix policy for integration test nodo
  src/domains/afm-app/.terraform.lock.hcl
  src/domains/afm-app/04_apim_afm_calculator.tf
  src/domains/afm-app/api/calculator-service/node/v1/_base_policy.xml
  src/domains/afm-app/api/calculator-service/node/v1/_base_policy_test.xml
Labels: status: applied :hand:

#2668 feat: [PQ-257] add ebollo configuration to checkout policy apim
  src/domains/checkout-app/api/checkout/checkout_carts_auth/v1/_base_policy.xml.tpl
Labels: status: applied :hand:

#2855 feat: Upd new prod env cert-2025 forwarder
  src/next-core/06_node_forwarder.tf
Labels: status: applied :hand:

#2852 feat: [PAGOPA-2720] Refactoring FdR Storage account
  src/domains/fdr-app/env/weu-dev/terraform.tfvars
  src/domains/fdr-app/env/weu-uat/terraform.tfvars
  src/domains/fdr-common/.terraform.lock.hcl
  src/domains/fdr-common/02_security.tf
  src/domains/fdr-common/03_storage_account_fdr.tf
  src/domains/fdr-common/99_variables.tf
  src/domains/fdr-common/README.md
  src/domains/fdr-common/env/weu-dev/terraform.tfvars
  src/domains/fdr-common/env/weu-prod/terraform.tfvars
  src/domains/fdr-common/env/weu-uat/terraform.tfvars
Labels: status: applied :hand:, fdr

#2860 feat: [PQ-356] add secret for ai service principal
  src/domains/qi-secrets/secret/weu-dev/noedit_secret_enc.json
  src/domains/qi-secrets/secret/weu-prod/noedit_secret_enc.json
  src/domains/qi-secrets/secret/weu-uat/noedit_secret_enc.json
Labels: status: applied :hand:, qi-observability

#2829 feat: [PAGOPA-2684] Setting wildcard on PSP whitelist for traffic switch on FdR-Fase1
  src/domains/fdr-app/00_data.tf
  src/domains/fdr-app/04_apim_aux.tf
  src/domains/fdr-app/README.md
  src/domains/fdr-app/env/weu-prod/terraform.tfvars
Labels: status: applied :hand:, fdr

#2818 chore: [PAGOPA-2681] Adding alerts for event hub ns-04
  src/next-core/05_messages.tf
  src/next-core/99_variables.tf
  src/next-core/README.md
  src/next-core/env/dev/terraform.tfvars
  src/next-core/env/prod/terraform.tfvars
  src/next-core/env/uat/terraform.tfvars
Labels: status: applied :hand:

#2863 fix: Excluding `registerForValidation` API calls for FTP-related `nodoInviaFlussoRendicontazione`
  src/domains/fdr-app/00_data.tf
  src/domains/fdr-app/04_apim_aux.tf
  src/domains/fdr-app/99_variables.tf
  src/domains/fdr-app/README.md
  src/domains/fdr-app/api/fdr-fase1/nodoPerPa/v1/fdr_pagopa_nodoChiediElencoFlussiRendicontazione.xml.tpl
  src/domains/fdr-app/api/fdr-fase1/nodoPerPsp/v1/fdr_nodoinvia_flussorendicontazione_flow.xml
  src/domains/fdr-app/env/weu-dev/terraform.tfvars
  src/domains/fdr-app/env/weu-prod/terraform.tfvars
  src/domains/fdr-app/env/weu-uat/terraform.tfvars
Labels: status: applied :hand:

#2870 feat: add gha identity for pagopa-qa repo
  src/domains/qi-common/10_github_identity.tf
Labels: status: applied :hand:, pagopa-qa

#2874 feat(aca): [PIDM-270] gpd for aca api group availability alert
  src/domains/aca-common/00_alerts.tf
  src/domains/aca-common/00_monitor.tf
  src/domains/aca-common/99_locals.tf
  src/domains/aca-common/README.md
Labels: status: applied :hand:

#2882 feat: [PQ-363] observability bdi opnapi improvement
  src/domains/qi-app/api/qi-observability-perf-kpi/v1/_openapi.yaml.tpl
Labels: status: applied :hand:, qi-observability

#2886 feat: Add quickisght dashboard env in selfcare-secrets for UAT & PROD
  src/domains/selfcare-secret/secret/weu-prod/noedit_secret_enc.json
  src/domains/selfcare-secret/secret/weu-uat/noedit_secret_enc.json
Labels: status: applied :hand:

#2887 feat: Add 2 connection eventhub data exp
  src/domains/observability/01_observability.tf
  src/domains/observability/README.md
Labels: status: applied :hand:

#2889 fix mv-expand field all dates fdr
  src/domains/observability/datafactory/pipelines/KPI_FDR_RENDICONTAZIONI.json
Labels: status: applied :hand:

#2853 chore: [PIDM-35][PIDM-42] Update openapi GPD-Core
  src/domains/aca-app/04_apim_gpd_for_aca.tf
  src/domains/aca-app/api/aca-gpd-like/v1/_openapi.json.tpl
  src/domains/gps-app/04_apim_gpd_core.tf
  src/domains/gps-app/04_apim_gpd_for_pn_aca.tf
  src/domains/gps-app/api/gpd_api/debt-position-services/v1/_openapi.json.tpl
  src/domains/gps-app/api/gpd_api/debt-position-services/v2/_openapi.json.tpl
  src/domains/gps-app/api/gpd_api/debt-position-services/v3/_openapi.json.tpl
  src/domains/gps-app/api/gpd_api/v1/_openapi.json.tpl
  src/domains/gps-app/api/gpd_api/v2/_openapi.json.tpl
  src/domains/gps-app/api/pn-integration/_openapi.json.tpl
Labels: env: dev, env: uat, gpd

#2893 chore: Db fdr1 password read
  src/domains/fdr-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/fdr-secret/secret/weu-prod/noedit_secret_enc.json
  src/domains/fdr-secret/secret/weu-uat/noedit_secret_enc.json
Labels: status: applied :hand:

#2891 feat: [PAGOPA-2750] Introduced workload identity NODO domain
  src/domains/nodo-app/.terraform.lock.hcl
  src/domains/nodo-app/02_namespace.tf
  src/domains/nodo-app/06_aks_middleware_tools.tf
  src/domains/nodo-app/99_main.tf
  src/domains/nodo-app/README.md
  src/domains/nodo-common/10_github_identity.tf
Labels: nodo

#2899 fix: [NODO] New runner configuration and MBD fixes
  src/domains/nodo-app/04_apim_mbd.tf
  src/domains/nodo-app/07_gh_runner.tf
  src/domains/nodo-app/README.md
  src/domains/nodo-app/env/weu-prod/terraform.tfvars
Labels: status: applied :hand:, nodo

#2873 feat: [PAGOPA-2721] Update AFM Calculator openapi
  src/domains/afm-app/api/calculator-service/node/v1/_openapi.json.tpl
  src/domains/afm-app/api/calculator-service/node/v2/_openapi.json.tpl
  src/domains/afm-app/api/calculator-service/v1/_openapi.json.tpl
  src/domains/afm-app/api/calculator-service/v1/prod/_openapi.json.tpl
  src/domains/afm-app/api/calculator-service/v2/_openapi.json.tpl
Labels: status: applied :hand:

#2918 chore: Refact fdr1 alert `PPT_SYSTEM_ERROR`
  src/domains/fdr-app/00_alert.tf
  src/domains/fdr-app/00_alert_fdr_fase1.tf
Labels: status: applied :hand:

#2924 feat: [PIDM-265] Introducing `pagopa-biz-events-sync-nodo` service and its infrastructure
  src/domains/bizevents-app/.terraform.lock.hcl
  src/domains/bizevents-app/02_namespace.tf
  src/domains/bizevents-app/05_aks_middleware_tools.tf
  src/domains/bizevents-app/07_gh_runner.tf
  src/domains/bizevents-app/99_main.tf
  src/domains/bizevents-app/README.md
  src/domains/bizevents-common/02_security.tf
  src/domains/bizevents-common/10_github_identity.tf
  src/domains/bizevents-common/README.md
  src/domains/bizevents-common/env/weu-prod/terraform.tfvars
  src/domains/bizevents-secrets/secret/weu-dev/noedit_secret_enc.json
  src/domains/bizevents-secrets/secret/weu-prod/noedit_secret_enc.json
  src/domains/bizevents-secrets/secret/weu-uat/noedit_secret_enc.json
Labels: status: applied :hand:

#2923 [PIDM-328] new event hub consumer
  src/domains/bizevents-common/01_events.tf
  src/domains/bizevents-common/02_security.tf
  src/next-core/env/dev/terraform.tfvars
  src/next-core/env/prod/terraform.tfvars
  src/next-core/env/uat/terraform.tfvars
Labels: status: applied :hand:

#2704 feat: [PPANTT-216] configured gps domain for workload identity
  src/domains/gps-app/.terraform.lock.hcl
  src/domains/gps-app/00_data.tf
  src/domains/gps-app/02_namespace.tf
  src/domains/gps-app/05_subkey.tf
  src/domains/gps-app/06_aks_middleware_tools.tf
  src/domains/gps-app/99_main.tf
  src/domains/gps-app/README.md
  src/domains/gps-common/10_github_identity.tf
  src/domains/gps-common/99_main.tf
Labels: status: applied :hand:, gpd

#2929 feat: [PIDM-265] Defining new product for `pagopa-biz-events-sync-nodo` application
  src/domains/bizevents-app/04_apim_bizevents.tf
  src/domains/bizevents-app/README.md
  src/domains/bizevents-app/api_product/nodo-sync/_base_policy.xml
Labels: env: dev, env: uat, env: prod, status: applied :hand:

#2925 feat: New ip in dns and route - oracle Nodo
  src/domains/nodo-app/env/weu-prod/terraform.tfvars
  src/next-core/env/prod/terraform.tfvars
Labels: status: applied :hand:

#2930 fix: Fix route table
  src/next-core/env/prod/terraform.tfvars
Labels: status: applied :hand:

#2901 chore: [PAGOPA-2470] Activities for fdr conversion fn
  src/domains/fdr-app/00_alert_fdr_xmltojson.tf
  src/domains/fdr-app/00_data.tf
  src/domains/fdr-app/04_apim_fdr_xml_to_json.tf
  src/domains/fdr-app/05_fdr_xml_to_json_fn.tf
  src/domains/fdr-app/07_gh_runner.tf
  src/domains/fdr-app/api/fdr-xml-to-json/v1/_base_policy.xml.tpl
  src/domains/fdr-app/api/fdr-xml-to-json/v1/_openapi.json.tpl
  src/domains/fdr-common/10_github_identity.tf
  src/domains/fdr-common/99_variables.tf
  src/domains/fdr-common/README.md
  src/domains/fdr-common/env/weu-dev/terraform.tfvars
  src/domains/fdr-common/env/weu-prod/terraform.tfvars
  src/domains/fdr-common/env/weu-uat/terraform.tfvars
Labels: status: applied :hand:, fdr

#2931 chore: Update Backoffice UAT AWS quicksight dashboard env
  src/domains/selfcare-secret/secret/weu-uat/noedit_secret_enc.json
Labels: status: applied :hand:

#2936 chore: Rotate-pwd-fdr3-db-uat-dev
  src/domains/fdr-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/fdr-secret/secret/weu-uat/noedit_secret_enc.json
Labels: status: applied :hand:

#2928 feat: [PAGOPA-2640] [FDR] Moved fdr3 DB migration scripts to pagopa-fdr
  .devops/fdr-fase3-db-migration-pipelines.yml
  .devops/fdr-fase3-db-schema-pipelines.yml
  src/psql/fdr/README.md
  src/psql/fdr/liquibase/changelog/fdr3/0/db.changelog-0.xml
  src/psql/fdr/liquibase/changelog/fdr3/db.changelog-master-0.xml
  src/psql/fdr/liquibase/changelog/fdr3/db.changelog-master-1.0.0.xml
  src/psql/fdr/liquibase/properties/fdr.properties
  src/psql/fdr/liquibase/run.sh
Labels: status: needs review, fdr
