Repository pagopa/pagopa-infra, pull requests merged in 2025-04, with the labels that each got.

#2937 fix: [PIDM-391] Avoid false positives on GPD alerts
  src/domains/aca-common/00_alerts.tf
Labels: status: applied :hand:

#2938 feat: QI wl
  src/domains/qi-app/.terraform.lock.hcl
  src/domains/qi-app/02_namespace.tf
  src/domains/qi-app/05_aks_middleware_tools.tf
  src/domains/qi-app/07_gh_runner.tf
  src/domains/qi-app/99_main.tf
  src/domains/qi-app/99_variables.tf
  src/domains/qi-app/README.md
  src/domains/qi-app/env/weu-prod/terraform.tfvars
  src/domains/qi-common/10_github_identity.tf
  src/domains/qi-common/README.md
Labels: status: applied :hand:

#2935 chore: update openapi fdr1 internal PAGOPA-2753
  src/domains/fdr-app/04_apim_fdr_fase1_internal.tf
  src/domains/fdr-app/README.md
  src/domains/fdr-app/api/fdr-fase1-internal/v1/_openapi.json.tpl
Labels: status: applied :hand:, fdr

#2953 chore: FdR fix secrets
  src/domains/fdr-secret/secret/weu-uat/noedit_secret_enc.json
Labels: env: uat, status: applied :hand:, fdr

#2934 chore: [PAGOPA-2710][PAGOPA-2766] FdR Alert
  src/domains/fdr-app/00_alert.tf
  src/domains/fdr-app/00_alert_fdr_fase1.tf
  src/domains/fdr-app/00_alert_fdr_fase3.tf
  src/domains/fdr-app/00_alert_fdr_json_to_xml.tf
  src/domains/fdr-app/00_alert_fdr_to_eventhub.tf
  src/domains/fdr-app/00_alert_fdr_xml_to_json.tf
  src/domains/fdr-app/00_alert_fdr_xmltojson.tf
  src/domains/fdr-app/00_monitor.tf
  src/domains/fdr-app/99_locals.tf
  src/domains/fdr-app/README.md
  src/domains/shared-common/00_data.tf
  src/domains/shared-common/70_slack.tf
  src/domains/shared-secrets/secret/weu-dev/noedit_secret_enc.json
  src/domains/shared-secrets/secret/weu-prod/noedit_secret_enc.json
  src/domains/shared-secrets/secret/weu-uat/noedit_secret_enc.json
Labels: status: applied :hand:, fdr

#2957 fix(FdR): PAGOPA-2766 Update fdr_json2xml alert
  src/domains/fdr-app/00_alert_fdr_json_to_xml.tf
Labels: status: applied :hand:, fdr

#2946 chore: Fix apim_ecommerce_helpdesk_api_v2 `coso`
  src/domains/bizevents-common/02_security.tf
  src/domains/bizevents-common/README.md
  src/domains/bizevents-secrets/secret/weu-dev/noedit_secret_enc.json
  src/domains/bizevents-secrets/secret/weu-prod/noedit_secret_enc.json
  src/domains/bizevents-secrets/secret/weu-uat/noedit_secret_enc.json
Labels: status: applied :hand:

#2956 feat(fdr): Create new FDR general dashboard
  src/domains/fdr-app/00_monitor.tf
  src/domains/fdr-app/README.md
  src/domains/fdr-app/dashboard/dashboard-general-fdr.json
Labels: status: applied :hand:, fdr

#2947 [PIDM-388] - Retrieve FDR flows exposed through APIM
  src/domains/fdr-app/04_apim_fdr_2_event_hub.tf
  src/domains/fdr-app/04_apim_fdr_fase1.tf
  src/domains/fdr-app/04_apim_fdr_fase1_auth.tf
  src/domains/fdr-app/99_locals.tf
  src/domains/fdr-app/README.md
  src/domains/fdr-app/api/fdr-2-event-hub/v1/_base_policy.xml.tpl
  src/domains/fdr-app/api/fdr-2-event-hub/v1/openapi_helpdesk.json.tpl
  src/domains/fdr-app/api_product/fdr-2-event-hub/_base_policy.xml
Labels: status: applied :hand:, fdr

#2958 chore: Fdr3 fix prod
  src/domains/fdr-app/00_alert_fdr_fase3.tf
  src/domains/fdr-app/99_variables.tf
  src/domains/fdr-app/README.md
  src/domains/fdr-app/env/weu-dev/terraform.tfvars
  src/domains/fdr-app/env/weu-prod/terraform.tfvars
  src/domains/fdr-app/env/weu-uat/terraform.tfvars
  src/domains/fdr-common/env/weu-prod/terraform.tfvars
Labels: status: applied :hand:, fdr

#2959 feat: refactoring FdR-related check statuses
  src/domains/shared-app/04_apim_statuspage.tf
Labels: status: applied :hand:, fdr

#2961 Fix dashboard fdr
  src/domains/fdr-app/00_monitor.tf
  src/domains/fdr-app/dashboard/dashboard-general-fdr.json
Labels: status: applied :hand:

#2964 fix: modify retry nodoInviaFlusso to nexi FdR PAGOPA-2985
  src/core/api_product/nodo_pagamenti_api/on_error_soap_req.xml
Labels: status: applied :hand:

#2965 fix(GPD): [PIDM-404] Update authorizer policy
  src/domains/gps-app/api/gpd_api/segregation_codes_fragment.xml
Labels: status: applied :hand:, gpd

#2940 chore: Fix nodo secret - Evt hub
  src/domains/fdr-common/00_data.tf
  src/domains/fdr-common/02_security.tf
  src/domains/fdr-common/env/weu-prod/terraform.tfvars
  src/domains/nodo-common/01_events.tf
  src/domains/nodo-common/02_security.tf
  src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
  src/next-core/env/dev/terraform.tfvars
  src/next-core/env/prod/terraform.tfvars
  src/next-core/env/uat/terraform.tfvars
Labels: nodo

#2954 feat: Biz View sa
  src/domains/bizevents-common/02_security.tf
  src/domains/bizevents-common/03_storage_account_fn.tf
  src/domains/bizevents-common/README.md
Labels: status: applied :hand:

#2948 feat: [PIDM-355] Add new receipt io message container
  src/domains/bizevents-common/02_security.tf
  src/domains/receipts-common/.terraform.lock.hcl
  src/domains/receipts-common/03_cosmosdb.tf
  src/domains/receipts-common/03_storage.tf
  src/domains/receipts-common/10_github_identity.tf
  src/domains/receipts-common/99_main.tf
  src/domains/receipts-common/README.md
  src/domains/receipts-common/env/weu-prod/terraform.tfvars
  src/domains/receipts-common/terraform.sh
Labels: status: applied :hand:

#2972 chore: Add secrets qi jira snow
  src/domains/qi-secrets/secret/weu-prod/noedit_secret_enc.json
  src/domains/qi-secrets/secret/weu-uat/noedit_secret_enc.json
Labels: status: applied :hand:

#2973 feat: add secret to hold NPG google pay api keys
  src/domains/ecommerce-common/02_security.tf
  src/domains/ecommerce-common/README.md
Labels: released

#2980 feat(cosmosdb): add readonly connection string to key vault
  src/domains/nodo-common/03_cosmosdb_standin.tf
  src/domains/nodo-common/README.md
Labels: status: applied :hand:, nodo

#2989 chore: [PIDM-480] [PRINTIT] Implemented domain workload identity
  src/domains/printit-app/.terraform.lock.hcl
  src/domains/printit-app/02_namespace.tf
  src/domains/printit-app/05_aks_middleware_tools.tf
  src/domains/printit-app/99_main.tf
  src/domains/printit-app/README.md
  src/domains/printit-common/.terraform.lock.hcl
  src/domains/printit-common/03_cosmos_mongodb_notices.tf
  src/domains/printit-common/03_eventhub.tf
  src/domains/printit-common/03_storage_account_institutions.tf
  src/domains/printit-common/03_storage_account_notices.tf
  src/domains/printit-common/03_storage_account_templates.tf
  src/domains/printit-common/10_github_identity.tf
  src/domains/printit-common/99_main.tf
  src/domains/printit-common/README.md
Labels: status: applied :hand:, printit

#2991 chore: [PIDM-482] [RECEIPT] Implemented domain workload identity
  src/domains/receipts-app/.terraform.lock.hcl
  src/domains/receipts-app/00_alert.tf
  src/domains/receipts-app/02_namespace.tf
  src/domains/receipts-app/05_aks_middleware_tools.tf
  src/domains/receipts-app/99_main.tf
  src/domains/receipts-app/README.md
  src/domains/receipts-common/10_github_identity.tf
Labels: status: applied :hand:, receipts

#3000 feat: including connection string for EventHub TX on NS03
  src/domains/bizevents-common/02_security.tf
  src/domains/bizevents-common/README.md
Labels: status: applied :hand:

#2993 feat(aca): add WL identity initialization
  src/domains/aca-app/.terraform.lock.hcl
  src/domains/aca-app/05_aks_middleware_tools.tf
  src/domains/aca-app/99_main.tf
  src/domains/aca-app/README.md
  src/domains/aca-common/.terraform.lock.hcl
  src/domains/aca-common/02_security.tf
  src/domains/aca-common/10_workload_identity.tf
  src/domains/aca-common/99_locals.tf
  src/domains/aca-common/99_main.tf
  src/domains/aca-common/README.md
Labels: status: applied :hand:

#2994 Pidm 485 remove pod identity
  src/domains/aca-app/05_aks_middleware_tools.tf
  src/domains/aca-app/README.md
Labels: status: applied :hand:

#2999 feat: remove pod identity
  src/domains/selfcare-app/02_namespace.tf
  src/domains/selfcare-app/README.md
  src/domains/selfcare-common/.terraform.lock.hcl
Labels: status: applied :hand:

#3004 chore: Remove pod-identity printit
  src/domains/canoneunico/00_alert.tf
  src/domains/printit-app/02_namespace.tf
  src/domains/printit-app/README.md
Labels: status: applied :hand:

#3007 feat: Add dev pgflex 4 cruscotto
  src/domains/cruscotto-common/00_monitor.tf
  src/domains/cruscotto-common/00_network.tf
  src/domains/cruscotto-common/03_postgresql.tf
  src/domains/cruscotto-common/99_locals.tf
  src/domains/cruscotto-common/99_variables.tf
  src/domains/cruscotto-common/env/itn-dev/terraform.tfvars
  src/domains/cruscotto-secrets/secret/itn-dev/noedit_secret_enc.json
Labels: env: dev, status: applied :hand:

#3005 [PIDM-450] secret(GPD): Add SEND client api-key
  src/domains/gps-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/gps-secret/secret/weu-uat/noedit_secret_enc.json
Labels: status: applied, gpd

#3010 feat : Add secrets & CDN cruscotto
  src/domains/cruscotto-app/04_apim.tf
  src/domains/cruscotto-app/04_apim_TODO.tf
  src/domains/cruscotto-app/06_cruscotto-fe.tf
  src/domains/cruscotto-app/99_locals.tf
  src/domains/cruscotto-app/99_variables.tf
  src/domains/cruscotto-common/02_security.tf
  src/domains/cruscotto-common/99_locals.tf
  src/domains/cruscotto-secrets/secret/itn-dev/noedit_secret_enc.json
Labels: env: dev, status: applied :hand:

#3011 chore: Nodo secrets
  src/domains/nodo-app/07_observability_stand_in.tf
  src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json
  src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
Labels: status: applied :hand:
